// packages/angular-radix/src/column-header-menu/column-header-menu.component.ts
import { Component, ChangeDetectionStrategy, signal, computed, Input } from '@angular/core';
import { getColumnHeaderMenuItems, type ColumnHeaderMenuHandlers } from '@alaarab/ogrid-angular';

/**
 * Column header dropdown menu for pin/unpin, sort, and autosize actions.
 * Uses native HTML elements with lightweight styling.
 */
@Component({
  selector: 'column-header-menu',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="ogrid-header-menu" (click)="$event.stopPropagation()">
      <button
        class="ogrid-header-menu__trigger"
        [attr.aria-label]="'Column options for ' + columnId"
        (click)="toggleMenu($event)"
      >
        &#8942;
      </button>

      @if (isOpen()) {
        <div class="ogrid-header-menu__dropdown">
          @for (item of menuItems(); track item.id) {
            <button
              class="ogrid-header-menu__item"
              [disabled]="item.disabled"
              (click)="handleMenuItemClick(item.id)"
            >
              {{ item.label }}
            </button>
            @if (item.divider) {
              <div class="ogrid-header-menu__divider"></div>
            }
          }
        </div>
      }
    </div>
  `,
  styles: [`
    .ogrid-header-menu {
      position: relative;
      display: inline-flex;
    }
    .ogrid-header-menu__trigger {
      width: 20px;
      height: 20px;
      padding: 0;
      border: none;
      border-radius: 2px;
      background: transparent;
      color: var(--ogrid-fg-secondary, rgba(0, 0, 0, 0.6));
      cursor: pointer;
      font-size: 14px;
      display: flex;
      align-items: center;
      justify-content: center;
      line-height: 1;
    }
    .ogrid-header-menu__trigger:hover {
      background: var(--ogrid-hover-bg, rgba(0, 0, 0, 0.04));
    }
    .ogrid-header-menu__dropdown {
      position: absolute;
      top: 100%;
      right: 0;
      z-index: 1000;
      min-width: 140px;
      background: var(--ogrid-bg, #ffffff);
      border: 1px solid var(--ogrid-border, rgba(0, 0, 0, 0.12));
      border-radius: 4px;
      box-shadow: 0 4px 12px rgba(0, 0, 0, 0.15);
      padding: 4px 0;
    }
    .ogrid-header-menu__item {
      display: block;
      width: 100%;
      padding: 6px 12px;
      border: none;
      background: transparent;
      color: var(--ogrid-fg, #242424);
      font-size: 13px;
      text-align: left;
      cursor: pointer;
      transition: background 0.15s ease;
    }
    .ogrid-header-menu__item:hover:not(:disabled) {
      background: var(--ogrid-hover-bg, rgba(0, 0, 0, 0.04));
    }
    .ogrid-header-menu__item:disabled {
      opacity: 0.4;
      cursor: not-allowed;
    }
    .ogrid-header-menu__divider {
      height: 1px;
      margin: 4px 0;
      background: var(--ogrid-border, rgba(0, 0, 0, 0.12));
    }
  `],
  host: {
    '(document:click)': 'onDocumentClick($event)',
  },
})
export class ColumnHeaderMenuComponent {
  @Input({ required: true }) columnId!: string;
  @Input() canPinLeft: boolean = true;
  @Input() canPinRight: boolean = true;
  @Input() canUnpin: boolean = false;
  @Input() currentSort: 'asc' | 'desc' | null = null;
  @Input() isSortable: boolean = true;
  @Input() isResizable: boolean = true;

  @Input() handlers: Partial<ColumnHeaderMenuHandlers> = {};

  readonly isOpen = signal(false);

  readonly menuItems = computed(() =>
    getColumnHeaderMenuItems({
      canPinLeft: this.canPinLeft,
      canPinRight: this.canPinRight,
      canUnpin: this.canUnpin,
      currentSort: this.currentSort,
      isSortable: this.isSortable,
      isResizable: this.isResizable,
    })
  );

  toggleMenu(event: MouseEvent): void {
    event.stopPropagation();
    this.isOpen.update(v => !v);
  }

  handleMenuItemClick(itemId: string): void {
    const h = this.handlers;
    const actionMap: Record<string, (() => void) | undefined> = {
      pinLeft: h.onPinLeft,
      pinRight: h.onPinRight,
      unpin: h.onUnpin,
      sortAsc: h.onSortAsc,
      sortDesc: h.onSortDesc,
      clearSort: h.onClearSort,
      autosizeThis: h.onAutosizeThis,
      autosizeAll: h.onAutosizeAll,
    };
    const action = actionMap[itemId];
    if (action) {
      action();
      h.onClose?.();
    }
    this.isOpen.set(false);
  }

  onDocumentClick(event: MouseEvent): void {
    const el = event.target as HTMLElement;
    if (!el.closest('column-header-menu')) {
      this.isOpen.set(false);
    }
  }
}

// packages/vue-radix/src/ColumnHeaderMenu/ColumnHeaderMenu.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
import { getColumnHeaderMenuItems } from '@alaarab/ogrid-vue';
import type { ColumnHeaderMenuProps } from './types';

const props = defineProps<ColumnHeaderMenuProps>();

const menuRef = ref<HTMLDivElement | null>(null);

const items = computed(() =>
  getColumnHeaderMenuItems({
    canPinLeft: props.canPinLeft,
    canPinRight: props.canPinRight,
    canUnpin: props.canUnpin,
    currentSort: props.currentSort,
    isSortable: props.isSortable,
    isResizable: props.isResizable,
  })
);

const handlers: Record<string, () => void> = {
  pinLeft: props.onPinLeft,
  pinRight: props.onPinRight,
  unpin: props.onUnpin,
  sortAsc: props.onSortAsc,
  sortDesc: props.onSortDesc,
  clearSort: props.onClearSort,
  autosizeThis: props.onAutosizeThis,
  autosizeAll: props.onAutosizeAll,
};

const handleClick = (itemId: string, disabled: boolean) => {
  if (!disabled && handlers[itemId]) {
    handlers[itemId]();
  }
};

const handleClickOutside = (e: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(e.target as Node)) {
    props.onClose();
  }
};

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});
</script>

<template>
  <div
    v-if="isOpen && anchorElement"
    ref="menuRef"
    role="menu"
    aria-label="Column options"
    class="ogrid-column-header-menu"
    :style="{
      top: `${anchorElement.getBoundingClientRect().bottom + 4}px`,
      left: `${anchorElement.getBoundingClientRect().left}px`,
    }"
  >
    <template v-for="(item, index) in items" :key="item.id">
      <div
        v-if="item.divider && index > 0"
        class="ogrid-column-header-menu-divider"
        role="separator"
      ></div>
      <div
        role="menuitem"
        :aria-disabled="item.disabled ? 'true' : undefined"
        :class="['ogrid-column-header-menu-item', { disabled: item.disabled }]"
        @click="handleClick(item.id, item.disabled ?? false)"
      >
        {{ item.label }}
      </div>
    </template>
  </div>
</template>

<style scoped>
.ogrid-column-header-menu {
  position: fixed;
  z-index: 9999;
  background-color: var(--ogrid-bg, #ffffff);
  color: var(--ogrid-fg, rgba(0, 0, 0, 0.87));
  border: 1px solid var(--ogrid-border, rgba(0, 0, 0, 0.12));
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  min-width: 160px;
  padding: 4px 0;
}

.ogrid-column-header-menu-item {
  display: flex;
  align-items: center;
  padding: 6px 12px;
  cursor: pointer;
  font-size: 0.875rem;
  color: var(--ogrid-fg, rgba(0, 0, 0, 0.87));
}

.ogrid-column-header-menu-item:hover:not(.disabled) {
  background-color: var(--ogrid-hover-bg, rgba(0, 0, 0, 0.04));
}

.ogrid-column-header-menu-item.disabled {
  cursor: default;
  opacity: 0.4;
}

.ogrid-column-header-menu-divider {
  height: 1px;
  background-color: var(--ogrid-border, rgba(0, 0, 0, 0.12));
  margin: 4px 0;
}
</style>
