// packages/fluent/src/ColumnHeaderFilter/MultiSelectFilterPopover.tsx
import * as React from 'react';
import { Input, Checkbox, Spinner } from '@fluentui/react-components';
import { SearchRegular } from '@fluentui/react-icons';
import styles from './ColumnHeaderFilter.module.scss';

export interface MultiSelectFilterPopoverProps {
  searchText: string;
  onSearchChange: (value: string) => void;
  options: string[];
  filteredOptions: string[];
  selected: Set<string>;
  onOptionToggle: (option: string, checked: boolean) => void;
  onSelectAll: () => void;
  onClearSelection: () => void;
  onApply: () => void;
  isLoading: boolean;
  onPopoverClick: (e: React.MouseEvent) => void;
  onInputFocus: (e: React.FocusEvent) => void;
  onInputMouseDown: (e: React.MouseEvent) => void;
  onInputClick: (e: React.MouseEvent) => void;
  onInputKeyDown: (e: React.KeyboardEvent) => void;
}

export const MultiSelectFilterPopover: React.FC<MultiSelectFilterPopoverProps> = ({
  searchText,
  onSearchChange,
  options,
  filteredOptions,
  selected,
  onOptionToggle,
  onSelectAll,
  onClearSelection,
  onApply,
  isLoading,
  onPopoverClick,
  onInputFocus,
  onInputMouseDown,
  onInputClick,
  onInputKeyDown,
}) => (
  <>
    <div className={styles.popoverSearch} onClick={onPopoverClick}>
      <Input
        placeholder="Search..."
        value={searchText}
        onChange={(e, data) => onSearchChange(data.value ?? '')}
        onFocus={onInputFocus}
        onMouseDown={onInputMouseDown}
        onClick={onInputClick}
        onKeyDown={onInputKeyDown}
        autoComplete="off"
        className={styles.searchInput}
        contentBefore={<SearchRegular />}
      />
      <div className={styles.resultCount}>
        {filteredOptions.length} of {options.length} options
      </div>
    </div>
    <div className={styles.selectAllRow} onClick={onPopoverClick}>
      <button type="button" className={styles.selectAllButton} onClick={onSelectAll}>
        Select All ({filteredOptions.length})
      </button>
      <button type="button" className={styles.selectAllButton} onClick={onClearSelection}>
        Clear
      </button>
    </div>
    <div className={styles.popoverOptions} onClick={onPopoverClick}>
      {isLoading ? (
        <div className={styles.loadingContainer}>
          <Spinner size="small" label="Loading..." />
        </div>
      ) : filteredOptions.length === 0 ? (
        <div className={styles.noResults}>No options found</div>
      ) : (
        filteredOptions.map((option) => (
          <div key={option} className={styles.popoverOption}>
            <Checkbox
              label={option}
              checked={selected.has(option)}
              onChange={(ev, data) => {
                ev.stopPropagation();
                onOptionToggle(option, data.checked === true);
              }}
            />
          </div>
        ))
      )}
    </div>
    <div className={styles.popoverActions} onClick={onPopoverClick}>
      <button type="button" className={styles.clearButton} onClick={onClearSelection}>
        Clear
      </button>
      <button type="button" className={styles.applyButton} onClick={onApply}>
        Apply
      </button>
    </div>
  </>
);

MultiSelectFilterPopover.displayName = 'MultiSelectFilterPopover';

// packages/vue-radix/src/ColumnHeaderFilter/MultiSelectFilterPopover.vue
<script setup lang="ts">
export interface MultiSelectFilterPopoverProps {
  searchText: string;
  onSearchChange: (value: string) => void;
  options: string[];
  filteredOptions: string[];
  selected: Set<string>;
  onOptionToggle: (option: string, checked: boolean) => void;
  onSelectAll: () => void;
  onClearSelection: () => void;
  onApply: () => void;
  isLoading: boolean;
}

const props = defineProps<MultiSelectFilterPopoverProps>();
</script>

<template>
  <div>
    <div class="popover-search">
      <input
        type="text"
        class="search-input"
        placeholder="Search..."
        :value="searchText"
        @input="onSearchChange(($event.target as HTMLInputElement).value)"
        autocomplete="off"
      />
      <div class="result-count">
        {{ filteredOptions.length }} of {{ options.length }} options
      </div>
    </div>
    <div class="select-all-row">
      <button type="button" class="select-all-button" @click="onSelectAll">
        Select All ({{ filteredOptions.length }})
      </button>
      <button type="button" class="select-all-button" @click="onClearSelection">
        Clear
      </button>
    </div>
    <div class="popover-options">
      <div v-if="isLoading" class="loading-container">Loading...</div>
      <div v-else-if="filteredOptions.length === 0" class="no-results">
        No options found
      </div>
      <div
        v-else
        v-for="option in filteredOptions"
        :key="option"
        class="popover-option"
      >
        <input
          type="checkbox"
          :checked="selected.has(option)"
          @change="onOptionToggle(option, ($event.target as HTMLInputElement).checked)"
          class="filter-checkbox"
        />
        <label style="margin-left: 8px; cursor: pointer; font-size: 13px">{{ option }}</label>
      </div>
    </div>
    <div class="popover-actions">
      <button type="button" class="clear-button" @click="onClearSelection">
        Clear
      </button>
      <button type="button" class="apply-button" @click="onApply">
        Apply
      </button>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import './ColumnHeaderFilter.module.scss';
</style>
