// packages/react-radix/src/ColumnHeaderFilter/MultiSelectFilterPopover.tsx
import * as React from 'react';
import * as Checkbox from '@radix-ui/react-checkbox';
import { useListVirtualizer } from '@alaarab/ogrid-react';
import styles from './ColumnHeaderFilter.module.scss';

const ITEM_HEIGHT = 32;

export interface MultiSelectFilterPopoverProps {
  searchText: string;
  onSearchChange: (value: string) => void;
  options: string[];
  filteredOptions: string[];
  selected: Set<string>;
  onOptionToggle: (option: string, checked: boolean) => void;
  onSelectAll: () => void;
  onClearSelection: () => void;
  onApply: () => void;
  isLoading: boolean;
}

export const MultiSelectFilterPopover: React.FC<MultiSelectFilterPopoverProps> = ({
  searchText,
  onSearchChange,
  options,
  filteredOptions,
  selected,
  onOptionToggle,
  onSelectAll,
  onClearSelection,
  onApply,
  isLoading,
}) => {
  const virt = useListVirtualizer({ count: filteredOptions.length, itemHeight: ITEM_HEIGHT });

  return (
    <>
      <div className={styles.popoverSearch}>
        <input
          type="text"
          className={styles.searchInput}
          placeholder="Search..."
          value={searchText}
          onChange={(e) => onSearchChange(e.target.value)}
          autoComplete="off"
        />
        <div className={styles.resultCount}>
          {filteredOptions.length} of {options.length} options
        </div>
      </div>
      <div className={styles.selectAllRow}>
        <button type="button" className={styles.selectAllButton} onClick={onSelectAll}>
          Select All ({filteredOptions.length})
        </button>
        <button type="button" className={styles.selectAllButton} onClick={onClearSelection}>
          Clear
        </button>
      </div>
      <div ref={virt.containerRef} onScroll={virt.onScroll} className={styles.popoverOptions}>
        {isLoading ? (
          <div className={styles.loadingContainer}>Loading...</div>
        ) : filteredOptions.length === 0 ? (
          <div className={styles.noResults}>No options found</div>
        ) : (
          <div style={{ height: virt.totalHeight, position: 'relative' }}>
            {virt.visibleItems.map(({ index, offsetTop }) => {
              const option = filteredOptions[index];
              return (
                <div key={option} className={styles.popoverOption} style={{ position: 'absolute', top: offsetTop, width: '100%', boxSizing: 'border-box' }}>
                  <Checkbox.Root
                    checked={selected.has(option)}
                    onCheckedChange={(c: boolean | 'indeterminate') =>
                      onOptionToggle(option, c === true)
                    }
                    className={styles.filterCheckbox}
                  >
                    <Checkbox.Indicator>✓</Checkbox.Indicator>
                  </Checkbox.Root>
                  <label style={{ marginLeft: 8, cursor: 'pointer' }}>{option}</label>
                </div>
              );
            })}
          </div>
        )}
      </div>
      <div className={styles.popoverActions}>
        <button type="button" className={styles.clearButton} onClick={onClearSelection}>
          Clear
        </button>
        <button type="button" className={styles.applyButton} onClick={onApply}>
          Apply
        </button>
      </div>
    </>
  );
};

MultiSelectFilterPopover.displayName = 'MultiSelectFilterPopover';

// packages/vue-radix/src/ColumnHeaderFilter/MultiSelectFilterPopover.vue
<script setup lang="ts">
export interface MultiSelectFilterPopoverProps {
  searchText: string;
  onSearchChange: (value: string) => void;
  options: string[];
  filteredOptions: string[];
  selected: Set<string>;
  onOptionToggle: (option: string, checked: boolean) => void;
  onSelectAll: () => void;
  onClearSelection: () => void;
  onApply: () => void;
  isLoading: boolean;
}

const props = defineProps<MultiSelectFilterPopoverProps>();
</script>

<template>
  <div>
    <div class="popover-search">
      <input
        type="text"
        class="search-input"
        placeholder="Search..."
        :value="searchText"
        @input="onSearchChange(($event.target as HTMLInputElement).value)"
        autocomplete="off"
      />
      <div class="result-count">
        {{ filteredOptions.length }} of {{ options.length }} options
      </div>
    </div>
    <div class="select-all-row">
      <button type="button" class="select-all-button" @click="onSelectAll">
        Select All ({{ filteredOptions.length }})
      </button>
      <button type="button" class="select-all-button" @click="onClearSelection">
        Clear
      </button>
    </div>
    <div class="popover-options">
      <div v-if="isLoading" class="loading-container">Loading...</div>
      <div v-else-if="filteredOptions.length === 0" class="no-results">
        No options found
      </div>
      <div
        v-else
        v-for="option in filteredOptions"
        :key="option"
        class="popover-option"
      >
        <input
          type="checkbox"
          :checked="selected.has(option)"
          @change="onOptionToggle(option, ($event.target as HTMLInputElement).checked)"
          class="filter-checkbox"
        />
        <label style="margin-left: 8px; cursor: pointer">{{ option }}</label>
      </div>
    </div>
    <div class="popover-actions">
      <button type="button" class="clear-button" @click="onClearSelection">
        Clear
      </button>
      <button type="button" class="apply-button" @click="onApply">
        Apply
      </button>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import './ColumnHeaderFilter.module.scss';
</style>
