// packages/vue-radix/src/ColumnHeaderMenu/ColumnHeaderMenu.vue
<script setup lang="ts">
import { ref, computed, onMounted, onBeforeUnmount } from 'vue';
import { getColumnHeaderMenuItems } from '@alaarab/ogrid-vue';
import type { ColumnHeaderMenuProps } from './types';

const props = defineProps<ColumnHeaderMenuProps>();

const menuRef = ref<HTMLDivElement | null>(null);

const items = computed(() =>
  getColumnHeaderMenuItems({
    canPinLeft: props.canPinLeft,
    canPinRight: props.canPinRight,
    canUnpin: props.canUnpin,
    currentSort: props.currentSort,
    isSortable: props.isSortable,
    isResizable: props.isResizable,
  })
);

const handlers: Record<string, () => void> = {
  pinLeft: props.onPinLeft,
  pinRight: props.onPinRight,
  unpin: props.onUnpin,
  sortAsc: props.onSortAsc,
  sortDesc: props.onSortDesc,
  clearSort: props.onClearSort,
  autosizeThis: props.onAutosizeThis,
  autosizeAll: props.onAutosizeAll,
};

const handleClick = (itemId: string, disabled: boolean) => {
  if (!disabled && handlers[itemId]) {
    handlers[itemId]();
  }
};

const handleClickOutside = (e: MouseEvent) => {
  if (menuRef.value && !menuRef.value.contains(e.target as Node)) {
    props.onClose();
  }
};

onMounted(() => {
  document.addEventListener('mousedown', handleClickOutside);
});

onBeforeUnmount(() => {
  document.removeEventListener('mousedown', handleClickOutside);
});
</script>

<template>
  <Teleport to="body">
  <div
    v-if="isOpen && anchorElement"
    ref="menuRef"
    role="menu"
    aria-label="Column options"
    class="ogrid-column-header-menu"
    :style="{
      position: 'fixed',
      zIndex: 9999,
      top: `${anchorElement.getBoundingClientRect().bottom + 4}px`,
      left: `${anchorElement.getBoundingClientRect().left}px`,
    }"
  >
    <template v-for="(item, index) in items" :key="item.id">
      <div
        v-if="item.divider && index > 0"
        class="ogrid-column-header-menu-divider"
        role="separator"
      ></div>
      <div
        role="menuitem"
        :aria-disabled="item.disabled ? 'true' : undefined"
        :class="['ogrid-column-header-menu-item', { disabled: item.disabled }]"
        @click="handleClick(item.id, item.disabled ?? false)"
      >
        {{ item.label }}
      </div>
    </template>
  </div>
  </Teleport>
</template>

<style scoped>
.ogrid-column-header-menu {
  position: fixed;
  z-index: 9999;
  background-color: var(--ogrid-bg, #ffffff);
  color: var(--ogrid-fg, rgba(0, 0, 0, 0.87));
  border: 1px solid var(--ogrid-border, rgba(0, 0, 0, 0.12));
  border-radius: 4px;
  box-shadow: 0 2px 8px rgba(0, 0, 0, 0.15);
  min-width: 160px;
  padding: 4px 0;
}

.ogrid-column-header-menu-item {
  display: flex;
  align-items: center;
  padding: 6px 12px;
  cursor: pointer;
  font-size: 0.875rem;
  color: var(--ogrid-fg, rgba(0, 0, 0, 0.87));
}

.ogrid-column-header-menu-item:hover:not(.disabled) {
  background-color: var(--ogrid-hover-bg, rgba(0, 0, 0, 0.04));
}

.ogrid-column-header-menu-item.disabled {
  cursor: default;
  opacity: 0.4;
}

.ogrid-column-header-menu-divider {
  height: 1px;
  background-color: var(--ogrid-border, rgba(0, 0, 0, 0.12));
  margin: 4px 0;
}
</style>

// packages/react-fluent/src/ColumnHeaderMenu/ColumnHeaderMenu.tsx
import React, { useMemo, useEffect, useState } from 'react';
import { createPortal } from 'react-dom';
import { getColumnHeaderMenuItems } from '@alaarab/ogrid-core';
import type { ColumnHeaderMenuInput } from '@alaarab/ogrid-core';
import styles from './ColumnHeaderMenu.module.scss';

export interface ColumnHeaderMenuProps {
  isOpen: boolean;
  anchorElement: HTMLElement | null;
  onClose: () => void;
  onPinLeft: () => void;
  onPinRight: () => void;
  onUnpin: () => void;
  onSortAsc: () => void;
  onSortDesc: () => void;
  onClearSort: () => void;
  onAutosizeThis: () => void;
  onAutosizeAll: () => void;
  canPinLeft: boolean;
  canPinRight: boolean;
  canUnpin: boolean;
  currentSort: 'asc' | 'desc' | null;
  isSortable: boolean;
  isResizable: boolean;
}

/**
 * Column header dropdown menu for pin/sort/autosize actions.
 * Uses positioned div with portal rendering.
 */
export function ColumnHeaderMenu(props: ColumnHeaderMenuProps) {
  const {
    isOpen,
    anchorElement,
    onClose,
    onPinLeft,
    onPinRight,
    onUnpin,
    onSortAsc,
    onSortDesc,
    onClearSort,
    onAutosizeThis,
    onAutosizeAll,
    canPinLeft,
    canPinRight,
    canUnpin,
    currentSort,
    isSortable,
    isResizable,
  } = props;

  const [position, setPosition] = useState<{ top: number; left: number } | null>(null);

  useEffect(() => {
    if (!isOpen || !anchorElement) {
      setPosition(null);
      return;
    }

    const rect = anchorElement.getBoundingClientRect();
    setPosition({
      top: rect.bottom + 4,
      left: rect.left,
    });

    const handleClickOutside = (e: MouseEvent) => {
      const target = e.target as Node;
      if (anchorElement && !anchorElement.contains(target)) {
        onClose();
      }
    };

    const handleEscape = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        onClose();
      }
    };

    document.addEventListener('mousedown', handleClickOutside);
    document.addEventListener('keydown', handleEscape);

    return () => {
      document.removeEventListener('mousedown', handleClickOutside);
      document.removeEventListener('keydown', handleEscape);
    };
  }, [isOpen, anchorElement, onClose]);

  const menuInput: ColumnHeaderMenuInput = useMemo(
    () => ({
      canPinLeft,
      canPinRight,
      canUnpin,
      currentSort,
      isSortable,
      isResizable,
    }),
    [canPinLeft, canPinRight, canUnpin, currentSort, isSortable, isResizable]
  );

  const items = useMemo(() => getColumnHeaderMenuItems(menuInput), [menuInput]);

  const handlers: Record<string, () => void> = {
    pinLeft: onPinLeft,
    pinRight: onPinRight,
    unpin: onUnpin,
    sortAsc: onSortAsc,
    sortDesc: onSortDesc,
    clearSort: onClearSort,
    autosizeThis: onAutosizeThis,
    autosizeAll: onAutosizeAll,
  };

  if (!isOpen || !position) return null;

  // Portal into the closest FluentProvider so --ogrid-* bridged variables are available
  const portalTarget = anchorElement?.closest('.fui-FluentProvider') as HTMLElement ?? document.body;

  return createPortal(
    <div
      className={styles.content}
      style={{
        position: 'fixed',
        top: position.top,
        left: position.left,
        zIndex: 1000,
      }}
    >
      {items.map((item, idx) => (
        <React.Fragment key={item.id}>
          <button
            className={styles.item}
            disabled={item.disabled}
            onClick={() => {
              handlers[item.id]();
              onClose();
            }}
          >
            {item.label}
          </button>
          {item.divider && idx < items.length - 1 && (
            <div className={styles.separator} />
          )}
        </React.Fragment>
      ))}
    </div>,
    portalTarget
  );
}
