// packages/angular-radix/src/column-chooser/column-chooser.component.ts
import { Component, input, output, signal, computed, ChangeDetectionStrategy } from '@angular/core';
import type { IColumnDefinition } from '@alaarab/ogrid-angular';

export interface IColumnChooserProps {
  columns: IColumnDefinition[];
  visibleColumns: Set<string>;
  onVisibilityChange: (columnKey: string, visible: boolean) => void;
}

/**
 * Column visibility chooser dropdown for Angular Radix (lightweight styling).
 * Standalone component with inline template and CSS variables for theming.
 */
@Component({
  selector: 'ogrid-column-chooser',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="ogrid-column-chooser">
      <button
        class="ogrid-column-chooser__trigger"
        (click)="toggle()"
        [attr.aria-expanded]="isOpen()"
        aria-haspopup="listbox"
      >
        ☰ Columns ({{ visibleCount() }}/{{ totalCount() }})
        <span class="ogrid-column-chooser__caret">{{ isOpen() ? '▲' : '▼' }}</span>
      </button>

      @if (isOpen()) {
        <div class="ogrid-column-chooser__dropdown" (click)="$event.stopPropagation()">
          <div class="ogrid-column-chooser__header">
            Select Columns ({{ visibleCount() }} of {{ totalCount() }})
          </div>

          <div class="ogrid-column-chooser__list">
            @for (col of columns(); track col.columnId) {
              <label class="ogrid-column-chooser__item">
                <input
                  type="checkbox"
                  [checked]="visibleColumns().has(col.columnId)"
                  (change)="onCheckboxChange(col.columnId, $event)"
                />
                <span>{{ col.name }}</span>
              </label>
            }
          </div>

          <div class="ogrid-column-chooser__footer">
            <button class="ogrid-column-chooser__btn" (click)="clearAll()">Clear All</button>
            <button class="ogrid-column-chooser__btn ogrid-column-chooser__btn--primary" (click)="selectAll()">Select All</button>
          </div>
        </div>
      }
    </div>
  `,
  styles: [`
    :host { display: inline-flex; position: relative; }
    .ogrid-column-chooser { position: relative; }
    .ogrid-column-chooser__trigger {
      display: inline-flex;
      align-items: center;
      gap: 6px;
      padding: 6px 12px;
      border: 1px solid var(--ogrid-border, #e0e0e0);
      border-radius: 4px;
      background: var(--ogrid-bg, #ffffff);
      color: var(--ogrid-fg, #242424);
      cursor: pointer;
      font-size: 14px;
      font-weight: 600;
      text-transform: none;
      white-space: nowrap;
      transition: all 0.15s ease;
    }
    .ogrid-column-chooser__trigger:hover {
      background: var(--ogrid-hover-bg, #f0f0f0);
      border-color: var(--ogrid-active-border, #0078d4);
    }
    .ogrid-column-chooser__caret {
      font-size: 10px;
      opacity: 0.7;
    }
    .ogrid-column-chooser__dropdown {
      position: absolute;
      top: 100%;
      right: 0;
      z-index: 1000;
      min-width: 220px;
      margin-top: 4px;
      background: var(--ogrid-bg, #ffffff);
      border: 1px solid var(--ogrid-border, #e0e0e0);
      border-radius: 4px;
      box-shadow: 0 4px 12px rgba(0,0,0,0.15);
    }
    .ogrid-column-chooser__header {
      padding: 8px 12px;
      font-size: 14px;
      font-weight: 600;
      color: var(--ogrid-fg, #242424);
      border-bottom: 1px solid var(--ogrid-border, #e0e0e0);
      background: var(--ogrid-header-bg, #f5f5f5);
    }
    .ogrid-column-chooser__list {
      max-height: 320px;
      overflow-y: auto;
      padding: 4px 0;
    }
    .ogrid-column-chooser__item {
      display: flex;
      align-items: center;
      gap: 8px;
      padding: 6px 12px;
      min-height: 32px;
      cursor: pointer;
      font-size: 14px;
      color: var(--ogrid-fg, #242424);
      transition: background 0.15s ease;
    }
    .ogrid-column-chooser__item:hover {
      background: var(--ogrid-hover-bg, #f0f0f0);
    }
    .ogrid-column-chooser__item input[type="checkbox"] {
      cursor: pointer;
    }
    .ogrid-column-chooser__footer {
      display: flex;
      justify-content: flex-end;
      gap: 8px;
      padding: 8px 12px;
      border-top: 1px solid var(--ogrid-border, #e0e0e0);
      background: var(--ogrid-header-bg, #f5f5f5);
    }
    .ogrid-column-chooser__btn {
      padding: 6px 12px;
      border: 1px solid var(--ogrid-border, #e0e0e0);
      border-radius: 4px;
      background: var(--ogrid-bg, #ffffff);
      color: var(--ogrid-fg, #242424);
      cursor: pointer;
      font-size: 13px;
      text-transform: none;
      transition: all 0.15s ease;
    }
    .ogrid-column-chooser__btn:hover {
      background: var(--ogrid-hover-bg, #f0f0f0);
    }
    .ogrid-column-chooser__btn--primary {
      background: var(--ogrid-active-border, #0078d4);
      color: #ffffff;
      border-color: var(--ogrid-active-border, #0078d4);
    }
    .ogrid-column-chooser__btn--primary:hover {
      opacity: 0.9;
    }
  `],
  host: {
    '(document:click)': 'onDocumentClick($event)',
  },
})
export class ColumnChooserComponent {
  readonly columns = input.required<IColumnDefinition[]>();
  readonly visibleColumns = input.required<Set<string>>();

  readonly visibilityChange = output<{ columnKey: string; visible: boolean }>();

  readonly isOpen = signal(false);

  readonly visibleCount = computed(() => this.visibleColumns().size);
  readonly totalCount = computed(() => this.columns().length);

  toggle(): void {
    this.isOpen.update((v) => !v);
  }

  onCheckboxChange(columnKey: string, event: Event): void {
    const checked = (event.target as HTMLInputElement).checked;
    this.visibilityChange.emit({ columnKey, visible: checked });
  }

  selectAll(): void {
    for (const col of this.columns()) {
      if (!this.visibleColumns().has(col.columnId)) {
        this.visibilityChange.emit({ columnKey: col.columnId, visible: true });
      }
    }
  }

  clearAll(): void {
    for (const col of this.columns()) {
      if (this.visibleColumns().has(col.columnId)) {
        this.visibilityChange.emit({ columnKey: col.columnId, visible: false });
      }
    }
  }

  onDocumentClick(event: MouseEvent): void {
    // Close dropdown when clicking outside
    const el = event.target as HTMLElement;
    if (!el.closest('ogrid-column-chooser')) {
      this.isOpen.set(false);
    }
  }
}

// packages/fluent/src/ColumnChooser/ColumnChooser.tsx
import * as React from 'react';
import { useRef, useEffect } from 'react';
import {
  Checkbox,
  makeStyles,
  tokens,
  mergeClasses,
  CheckboxOnChangeData,
} from '@fluentui/react-components';
import { TableSettingsRegular, ChevronDownRegular, ChevronUpRegular } from '@fluentui/react-icons';
import type { IColumnDefinition } from '@alaarab/ogrid-core';
import { useColumnChooserState } from '@alaarab/ogrid-core';

const useStyles = makeStyles({
  container: {
    position: 'relative',
    display: 'inline-flex',
  },
  triggerButton: {
    display: 'inline-flex',
    alignItems: 'center',
    gap: '6px',
    padding: '6px 12px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusMedium,
    backgroundColor: tokens.colorNeutralBackground1,
    cursor: 'pointer',
    fontSize: tokens.fontSizeBase300,
    fontWeight: tokens.fontWeightSemibold,
    color: tokens.colorNeutralForeground1,
    transitionDuration: '0.15s',
    transitionProperty: 'all',
    transitionTimingFunction: 'ease',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      border: `1px solid ${tokens.colorNeutralStroke1Hover}`,
    },
  },
  triggerButtonOpen: {
    border: `1px solid ${tokens.colorBrandStroke1}`,
  },
  buttonIcon: {
    fontSize: '16px',
  },
  chevron: {
    fontSize: '12px',
    color: tokens.colorNeutralForeground3,
  },
  dropdown: {
    position: 'absolute',
    top: 'calc(100% + 4px)',
    right: '0',
    zIndex: 10000,
    minWidth: '220px',
    backgroundColor: tokens.colorNeutralBackground1,
    borderRadius: tokens.borderRadiusMedium,
    boxShadow: tokens.shadow16,
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    display: 'flex',
    flexDirection: 'column',
  },
  header: {
    padding: '8px 12px',
    borderBottom: `1px solid ${tokens.colorNeutralStroke2}`,
    fontWeight: tokens.fontWeightSemibold,
    fontSize: tokens.fontSizeBase300,
    color: tokens.colorNeutralForeground1,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  optionsList: {
    maxHeight: '320px',
    overflowY: 'auto',
    padding: 0,
  },
  optionItem: {
    padding: '4px 12px',
    display: 'flex',
    alignItems: 'center',
    minHeight: '32px',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
    },
  },
  actions: {
    display: 'flex',
    justifyContent: 'flex-end',
    gap: '8px',
    padding: '8px 12px',
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground2,
  },
  clearButton: {
    padding: '6px 12px',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorNeutralBackground1,
    color: tokens.colorNeutralForeground2,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightRegular,
    cursor: 'pointer',
    transitionDuration: '0.15s',
    transitionProperty: 'all',
    ':hover': {
      backgroundColor: tokens.colorNeutralBackground1Hover,
      color: tokens.colorNeutralForeground1,
      border: `1px solid ${tokens.colorNeutralStroke1Hover}`,
    },
  },
  selectAllButton: {
    padding: '6px 16px',
    border: 'none',
    borderRadius: tokens.borderRadiusSmall,
    backgroundColor: tokens.colorBrandBackground,
    color: tokens.colorNeutralForegroundOnBrand,
    fontSize: tokens.fontSizeBase200,
    fontWeight: tokens.fontWeightSemibold,
    cursor: 'pointer',
    transitionDuration: '0.15s',
    transitionProperty: 'all',
    ':hover': {
      backgroundColor: tokens.colorBrandBackgroundHover,
    },
  },
});

export type { IColumnDefinition };

export interface IColumnChooserProps {
  columns: IColumnDefinition[];
  visibleColumns: Set<string>;
  onVisibilityChange: (columnKey: string, visible: boolean) => void;
  className?: string;
}

export const ColumnChooser: React.FC<IColumnChooserProps> = (props) => {
  const { columns, visibleColumns, onVisibilityChange, className } = props;
  const classes = useStyles();
  const buttonRef = useRef<HTMLButtonElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const {
    open: isOpen,
    handleToggle,
    handleClose,
    handleCheckboxChange: setColumnVisible,
    handleSelectAll,
    handleClearAll,
    visibleCount,
    totalCount,
  } = useColumnChooserState({ columns, visibleColumns, onVisibilityChange });

  useEffect(() => {
    if (!isOpen) return;
    const handleClickOutside = (event: MouseEvent): void => {
      const target = event.target as Node;
      const isOutsideDropdown = dropdownRef.current && !dropdownRef.current.contains(target);
      const isOutsideButton = buttonRef.current && !buttonRef.current.contains(target);
      if (isOutsideDropdown && isOutsideButton) {
        handleClose();
      }
    };
    const timeoutId = setTimeout(() => {
      document.addEventListener('mousedown', handleClickOutside);
    }, 0);
    return () => {
      clearTimeout(timeoutId);
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [isOpen, handleClose]);

  const handleCheckboxChange = (columnKey: string) => {
    return (ev: React.ChangeEvent<HTMLInputElement>, data: CheckboxOnChangeData) => {
      ev.stopPropagation();
      setColumnVisible(columnKey)(data.checked === true);
    };
  };

  const handleDropdownClick = (e: React.MouseEvent): void => {
    e.stopPropagation();
  };

  return (
    <div className={`${classes.container} ${className || ''}`}>
      <button
        type="button"
        ref={buttonRef}
        className={mergeClasses(classes.triggerButton, isOpen && classes.triggerButtonOpen)}
        onClick={handleToggle}
        aria-expanded={isOpen}
        aria-haspopup="listbox"
      >
        <TableSettingsRegular className={classes.buttonIcon} />
        <span>Column Visibility ({visibleCount} of {totalCount})</span>
        {isOpen ? <ChevronUpRegular className={classes.chevron} /> : <ChevronDownRegular className={classes.chevron} />}
      </button>

      {isOpen && (
        <div className={classes.dropdown} ref={dropdownRef} onClick={handleDropdownClick}>
          <div className={classes.header}>
            Select Columns ({visibleCount} of {totalCount})
          </div>
          <div className={classes.optionsList}>
            {columns.map(column => (
              <div key={column.columnId} className={classes.optionItem}>
                <Checkbox
                  label={column.name}
                  checked={visibleColumns.has(column.columnId)}
                  onChange={handleCheckboxChange(column.columnId)}
                />
              </div>
            ))}
          </div>
          <div className={classes.actions}>
            <button type="button" className={classes.clearButton} onClick={handleClearAll}>
              Clear All
            </button>
            <button type="button" className={classes.selectAllButton} onClick={handleSelectAll}>
              Select All
            </button>
          </div>
        </div>
      )}
    </div>
  );
};
