// packages/examples/src/radix/main.tsx
import React from 'react';
import { createRoot } from 'react-dom/client';
import { OGrid } from '@alaarab/ogrid';
import { makeDemoProjects, makeDemoColumns, getRowId } from '../shared/demoData';
import type { Project } from '../shared/demoData';

const projects = makeDemoProjects(75);
const columns = makeDemoColumns<Project>();

function App() {
  return (
    <div style={{ padding: 24, maxWidth: 1200, margin: '0 auto' }}>
      <h1>OGrid - Radix UI Example</h1>
      <p style={{ color: '#666', marginBottom: 16 }}>
        A fully featured data table powered by <code>@alaarab/ogrid</code>.
        Includes sorting, multi-select &amp; text filtering, column chooser, and pagination.
      </p>
      <OGrid<Project>
        data={projects}
        columns={columns}
        getRowId={getRowId}
        entityLabelPlural="projects"
        title={<h2 style={{ margin: 0 }}>Projects</h2>}
        defaultPageSize={20}
      />
    </div>
  );
}

createRoot(document.getElementById('root')!).render(<App />);

// packages/examples/src/angular-radix/main.ts
import { bootstrapApplication } from '@angular/platform-browser';
import { Component } from '@angular/core';
import { OGridComponent } from '@alaarab/ogrid-angular-radix';
import { makeDemoProjects, makeDemoColumns, getRowId } from '../shared/demoData';
import type { Project } from '../shared/demoData';

const projects = makeDemoProjects(75);
const columns = makeDemoColumns<Project>();

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [OGridComponent],
  template: `
    <div style="padding: 24px; max-width: 1200px; margin: 0 auto;">
      <h1>OGrid - Angular Radix Example</h1>
      <p style="color: #666; margin-bottom: 16px;">
        A fully featured data table powered by <code>@alaarab/ogrid-angular-radix</code>.
        Includes sorting, multi-select &amp; text filtering, column chooser, and pagination.
      </p>
      <ogrid
        [data]="projects"
        [columns]="columns"
        [getRowId]="getRowId"
        entityLabelPlural="projects"
        [defaultPageSize]="25"
      />
    </div>
  `,
})
export class AppComponent {
  projects = projects;
  columns = columns;
  getRowId = getRowId;
}

bootstrapApplication(AppComponent).catch((err) => console.error(err));
