// packages/material/src/PaginationControls/PaginationControls.tsx
import * as React from 'react';
import { useMemo, useCallback } from 'react';
import {
  IconButton, Button, Select, MenuItem, Box, Typography,
} from '@mui/material';
import type { SelectChangeEvent } from '@mui/material';
import {
  FirstPage as FirstPageIcon,
  LastPage as LastPageIcon,
  ChevronLeft as ChevronLeftIcon,
  ChevronRight as ChevronRightIcon,
} from '@mui/icons-material';
import { getPaginationViewModel } from '@alaarab/ogrid-core';

export interface IPaginationControlsProps {
  currentPage: number;
  pageSize: number;
  totalCount: number;
  onPageChange: (page: number) => void;
  onPageSizeChange: (pageSize: number) => void;
  pageSizeOptions?: number[];
  entityLabelPlural?: string;
  className?: string;
}

export const PaginationControls: React.FC<IPaginationControlsProps> = React.memo((props) => {
  const {
    currentPage,
    pageSize,
    totalCount,
    onPageChange,
    onPageSizeChange,
    pageSizeOptions,
    entityLabelPlural,
    className,
  } = props;
  const labelPlural = entityLabelPlural ?? 'items';

  const vm = useMemo(
    () => getPaginationViewModel(currentPage, pageSize, totalCount, pageSizeOptions ? { pageSizeOptions } : undefined),
    [currentPage, pageSize, totalCount, pageSizeOptions]
  );

  const handlePageSizeChange = useCallback(
    (event: SelectChangeEvent<number>) => {
      onPageSizeChange(Number(event.target.value));
    },
    [onPageSizeChange],
  );

  if (!vm) {
    return null;
  }

  const { pageNumbers, showStartEllipsis, showEndEllipsis, totalPages, startItem, endItem } = vm;

  return (
    <Box
      className={className}
      role="navigation"
      aria-label="Pagination"
      sx={{
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        flexWrap: 'wrap',
        gap: 2,
        px: 1.5,
        width: '100%',
        minWidth: 0,
        boxSizing: 'border-box',
      }}
    >
      <Typography variant="body2" color="text.secondary">
        Showing {startItem} to {endItem} of {totalCount.toLocaleString()} {labelPlural}
      </Typography>

      <Box sx={{ display: 'flex', alignItems: 'center', gap: 0.5 }}>
        <IconButton
          size="small"
          onClick={() => onPageChange(1)}
          disabled={currentPage === 1}
          aria-label="First page"
        >
          <FirstPageIcon fontSize="small" />
        </IconButton>
        <IconButton
          size="small"
          onClick={() => onPageChange(currentPage - 1)}
          disabled={currentPage === 1}
          aria-label="Previous page"
        >
          <ChevronLeftIcon fontSize="small" />
        </IconButton>

        {showStartEllipsis && (
          <>
            <Button
              variant="outlined"
              size="small"
              onClick={() => onPageChange(1)}
              aria-label="Page 1"
              sx={{ minWidth: 32, px: 0.5 }}
            >
              1
            </Button>
            <Typography variant="body2" color="text.secondary" sx={{ mx: 0.5 }} aria-hidden>
              …
            </Typography>
          </>
        )}

        {pageNumbers.map((pageNum) => (
          <Button
            key={pageNum}
            variant={currentPage === pageNum ? 'contained' : 'outlined'}
            size="small"
            onClick={() => onPageChange(pageNum)}
            aria-label={`Page ${pageNum}`}
            aria-current={currentPage === pageNum ? 'page' : undefined}
            sx={{ minWidth: 32, px: 0.5 }}
          >
            {pageNum}
          </Button>
        ))}

        {showEndEllipsis && (
          <>
            <Typography variant="body2" color="text.secondary" sx={{ mx: 0.5 }} aria-hidden>
              …
            </Typography>
            <Button
              variant="outlined"
              size="small"
              onClick={() => onPageChange(totalPages)}
              aria-label={`Page ${totalPages}`}
              sx={{ minWidth: 32, px: 0.5 }}
            >
              {totalPages}
            </Button>
          </>
        )}

        <IconButton
          size="small"
          onClick={() => onPageChange(currentPage + 1)}
          disabled={currentPage >= totalPages}
          aria-label="Next page"
        >
          <ChevronRightIcon fontSize="small" />
        </IconButton>
        <IconButton
          size="small"
          onClick={() => onPageChange(totalPages)}
          disabled={currentPage >= totalPages}
          aria-label="Last page"
        >
          <LastPageIcon fontSize="small" />
        </IconButton>
      </Box>

      <Box sx={{ display: 'flex', alignItems: 'center', gap: 1 }}>
        <Typography variant="body2" color="text.secondary">
          Rows
        </Typography>
        <Select
          value={pageSize}
          onChange={handlePageSizeChange}
          size="small"
          aria-label="Rows per page"
          sx={{ minWidth: 70 }}
        >
          {vm.pageSizeOptions.map((n) => (
            <MenuItem key={n} value={n}>
              {n}
            </MenuItem>
          ))}
        </Select>
      </Box>
    </Box>
  );
});

// packages/angular-primeng/src/pagination-controls/pagination-controls.component.ts
import { Component, input, output, computed } from '@angular/core';
import { CommonModule } from '@angular/common';
import { getPaginationViewModel } from '@alaarab/ogrid-core';

@Component({
  selector: 'ogrid-primeng-pagination-controls',
  standalone: true,
  imports: [CommonModule],
  template: `
    @if (vm()) {
      <div style="display:flex;align-items:center;justify-content:space-between;gap:12px;flex-wrap:wrap;font-size:13px;color:var(--ogrid-fg, #242424)">
        <div>
          Showing {{ vm()!.startItem }} to {{ vm()!.endItem }} of {{ totalCount().toLocaleString() }} {{ labelPlural() }}
        </div>

        <div style="display:flex;align-items:center;gap:4px" role="navigation" aria-label="Pagination">
          <button
            type="button"
            class="p-button p-button-text p-button-sm"
            [disabled]="currentPage() === 1"
            (click)="pageChange.emit(1)"
            aria-label="First page"
            style="min-width:32px;padding:4px 8px"
          >&laquo;</button>
          <button
            type="button"
            class="p-button p-button-text p-button-sm"
            [disabled]="currentPage() === 1"
            (click)="pageChange.emit(currentPage() - 1)"
            aria-label="Previous page"
            style="min-width:32px;padding:4px 8px"
          >&lsaquo;</button>

          @if (vm()!.showStartEllipsis) {
            <button
              type="button"
              class="p-button p-button-text p-button-sm"
              (click)="pageChange.emit(1)"
              aria-label="Page 1"
              style="min-width:32px;padding:4px 8px"
            >1</button>
            <span aria-hidden style="padding:0 4px">&hellip;</span>
          }

          @for (pageNum of vm()!.pageNumbers; track pageNum) {
            <button
              type="button"
              class="p-button p-button-sm"
              [class.p-button-outlined]="currentPage() !== pageNum"
              (click)="pageChange.emit(pageNum)"
              [attr.aria-label]="'Page ' + pageNum"
              [attr.aria-current]="currentPage() === pageNum ? 'page' : null"
              style="min-width:32px;padding:4px 8px"
            >{{ pageNum }}</button>
          }

          @if (vm()!.showEndEllipsis) {
            <span aria-hidden style="padding:0 4px">&hellip;</span>
            <button
              type="button"
              class="p-button p-button-text p-button-sm"
              (click)="pageChange.emit(vm()!.totalPages)"
              [attr.aria-label]="'Page ' + vm()!.totalPages"
              style="min-width:32px;padding:4px 8px"
            >{{ vm()!.totalPages }}</button>
          }

          <button
            type="button"
            class="p-button p-button-text p-button-sm"
            [disabled]="currentPage() >= vm()!.totalPages"
            (click)="pageChange.emit(currentPage() + 1)"
            aria-label="Next page"
            style="min-width:32px;padding:4px 8px"
          >&rsaquo;</button>
          <button
            type="button"
            class="p-button p-button-text p-button-sm"
            [disabled]="currentPage() >= vm()!.totalPages"
            (click)="pageChange.emit(vm()!.totalPages)"
            aria-label="Last page"
            style="min-width:32px;padding:4px 8px"
          >&raquo;</button>
        </div>

        <div style="display:flex;align-items:center;gap:6px">
          <span style="font-size:12px">Rows</span>
          <select
            [value]="'' + pageSize()"
            (change)="onPageSizeChange($any($event.target).value)"
            aria-label="Rows per page"
            style="padding:4px 6px;border:1px solid var(--ogrid-border, #e0e0e0);border-radius:4px;background:var(--ogrid-bg, #fff);color:var(--ogrid-fg, #242424)"
          >
            @for (opt of vm()!.pageSizeOptions; track opt) {
              <option [value]="opt">{{ opt }}</option>
            }
          </select>
        </div>
      </div>
    }
  `,
})
export class PaginationControlsComponent {
  readonly currentPage = input.required<number>();
  readonly pageSize = input.required<number>();
  readonly totalCount = input.required<number>();
  readonly pageSizeOptions = input<number[] | undefined>(undefined);
  readonly entityLabelPlural = input<string>('items');

  readonly pageChange = output<number>();
  readonly pageSizeChange = output<number>();

  protected readonly labelPlural = computed(() => this.entityLabelPlural() ?? 'items');

  protected readonly vm = computed(() =>
    getPaginationViewModel(
      this.currentPage(),
      this.pageSize(),
      this.totalCount(),
      this.pageSizeOptions() ? { pageSizeOptions: this.pageSizeOptions()! } : undefined,
    ),
  );

  onPageSizeChange(value: string): void {
    this.pageSizeChange.emit(Number(value));
  }
}
