// packages/angular-material/src/datagrid-table/datagrid-table.component.ts
import {
  Component, input, ElementRef, viewChild,
  ChangeDetectionStrategy,
} from '@angular/core';
import {
  BaseDataGridTableComponent,
  DataGridStateService,
  MarchingAntsOverlayComponent,
  CHECKBOX_COLUMN_WIDTH,
  ROW_NUMBER_COLUMN_WIDTH,
} from '@alaarab/ogrid-angular';
import type {
  IOGridDataGridProps,
} from '@alaarab/ogrid-angular';
import { ColumnHeaderFilterComponent } from '../column-header-filter/column-header-filter.component';
import { ColumnHeaderMenuComponent } from '../column-header-menu/column-header-menu.component';
import { InlineCellEditorComponent } from './inline-cell-editor.component';
import { PopoverCellEditorComponent } from './popover-cell-editor.component';

/**
 * DataGridTable component using native HTML table with Material Design-inspired styling.
 * Standalone component — this is the workhorse of the grid.
 */
@Component({
  selector: 'ogrid-datagrid-table',
  standalone: true,
  imports: [ColumnHeaderFilterComponent, ColumnHeaderMenuComponent, MarchingAntsOverlayComponent, InlineCellEditorComponent, PopoverCellEditorComponent],
  providers: [DataGridStateService],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="ogrid-datagrid-root">
      <div
        #wrapperEl
        class="ogrid-datagrid-wrapper"
        [class.ogrid-datagrid-wrapper--fit]="layoutModeFit()"
        [class.ogrid-datagrid-wrapper--overflow-x]="allowOverflowX()"
        tabindex="0"
        role="region"
        [attr.aria-label]="ariaLabel()"
        [attr.aria-labelledby]="ariaLabelledBy()"
        (mousedown)="onWrapperMouseDown($event)"
        (keydown)="onGridKeyDown($event)"
        (scroll)="onWrapperScroll($event)"
        (contextmenu)="$event.preventDefault()"
        [attr.data-overflow-x]="allowOverflowX() ? 'true' : 'false'"
      >
        <div class="ogrid-datagrid-scroll-wrapper">
          <div [style.minWidth.px]="allowOverflowX() ? minTableWidth() : undefined">
            <div [class.ogrid-datagrid-table-wrapper--loading]="isLoading() && items().length > 0" #tableContainerEl>
              <table class="ogrid-datagrid-table" [style.minWidth.px]="minTableWidth()"
                [attr.data-freeze-rows]="freezeRows()"
                [attr.data-freeze-cols]="freezeCols()"
              >
                <thead class="ogrid-datagrid-thead">
                  @for (row of headerRows(); track $index; let rowIdx = $index) {
                    <tr class="ogrid-datagrid-header-row">
                      @if (rowIdx === headerRows().length - 1 && hasCheckboxCol()) {
                        <th class="ogrid-datagrid-th ogrid-datagrid-checkbox-col" [attr.rowSpan]="headerRows().length > 1 ? 1 : null">
                          <div class="ogrid-datagrid-checkbox-wrapper">
                            <input
                              type="checkbox"
                              [checked]="allSelected()"
                              [indeterminate]="someSelected()"
                              (change)="onSelectAllChange($event)"
                              aria-label="Select all rows"
                            />
                          </div>
                        </th>
                      }
                      @if (rowIdx === 0 && rowIdx < headerRows().length - 1 && hasCheckboxCol()) {
                        <th [attr.rowSpan]="headerRows().length - 1" class="ogrid-datagrid-th" style="width: 48px; min-width: 48px; padding: 0;"></th>
                      }
                      @if (rowIdx === headerRows().length - 1 && hasRowNumbersCol()) {
                        <th class="ogrid-datagrid-th ogrid-row-number-header" [attr.rowSpan]="headerRows().length > 1 ? 1 : null">
                          <div class="ogrid-row-number-header-content">#</div>
                        </th>
                      }
                      @if (rowIdx === 0 && rowIdx < headerRows().length - 1 && hasRowNumbersCol()) {
                        <th [attr.rowSpan]="headerRows().length - 1" class="ogrid-datagrid-th" [style.width.px]="50" [style.min-width.px]="50" style="padding: 0;"></th>
                      }
                      @for (cell of row; track $index; let cellIdx = $index) {
                        @if (cell.isGroup) {
                          <th [attr.colSpan]="cell.colSpan" scope="colgroup" class="ogrid-datagrid-th ogrid-datagrid-group-header">
                            {{ cell.label }}
                          </th>
                        } @else {
                          @let col = asColumnDef(cell.columnDef);
                          @let colIdx = visibleColIndex(col);
                          @let isFreezeCol = freezeCols() != null && (freezeCols() ?? 0) >= 1 && colIdx < (freezeCols() ?? 0);
                          @let colW = getColumnWidth(col);
                          @let pinned = isPinned(col.columnId);
                          @let pinnedLeft = pinned === 'left' || (isFreezeCol && colIdx === 0);
                          @let pinnedRight = pinned === 'right';
                          <th scope="col"
                            class="ogrid-datagrid-th"
                            [class.ogrid-datagrid-th--pinned-left]="pinnedLeft"
                            [class.ogrid-datagrid-th--pinned-right]="pinnedRight"
                            [attr.rowSpan]="headerRows().length > 1 ? headerRows().length - rowIdx : null"
                            [attr.data-column-id]="col.columnId"
                            [style.minWidth.px]="col.minWidth ?? 80"
                            [style.width.px]="colW"
                            [style.maxWidth.px]="colW"
                            [style.cursor]="columnReorderService.isDragging() ? 'grabbing' : 'grab'"
                            (mousedown)="onHeaderMouseDown(col.columnId, $event)"
                          >
                            <div style="display:flex;align-items:center;gap:4px;">
                              <ogrid-column-header-filter
                                [columnKey]="col.columnId"
                                [columnName]="col.name"
                                [filterType]="getFilterConfig(col).filterType"
                                [isSorted]="getFilterConfig(col).isSorted"
                                [isSortedDescending]="getFilterConfig(col).isSortedDescending"
                                [onSort]="getFilterConfig(col).onSort"
                                [selectedValues]="getFilterConfig(col).selectedValues"
                                [onFilterChange]="getFilterConfig(col).onFilterChange"
                                [options]="getFilterConfig(col).options"
                                [isLoadingOptions]="getFilterConfig(col).isLoadingOptions ?? false"
                                [textValue]="getFilterConfig(col).textValue ?? ''"
                                [onTextChange]="getFilterConfig(col).onTextChange"
                                [selectedUser]="getFilterConfig(col).selectedUser"
                                [onUserChange]="getFilterConfig(col).onUserChange"
                                [peopleSearch]="getFilterConfig(col).peopleSearch"
                                [dateValue]="getFilterConfig(col).dateValue"
                                [onDateChange]="getFilterConfig(col).onDateChange"
                              />
                              @let pinState = getPinState(col.columnId);
                              <column-header-menu
                                [columnId]="col.columnId"
                                [onPinLeft]="() => onPinColumn(col.columnId, 'left')"
                                [onPinRight]="() => onPinColumn(col.columnId, 'right')"
                                [onUnpin]="() => onUnpinColumn(col.columnId)"
                                [canPinLeft]="pinState.canPinLeft"
                                [canPinRight]="pinState.canPinRight"
                                [canUnpin]="pinState.canUnpin"
                              />
                            </div>
                            <div class="ogrid-datagrid-resize-handle" (mousedown)="onResizeStart($event, col)"></div>
                          </th>
                        }
                      }
                    </tr>
                  }
                </thead>
                @if (!showEmptyInGrid()) {
                  <tbody>
                    @if (vsEnabled() && vsTopSpacerHeight() > 0) {
                      <tr class="ogrid-datagrid-vs-spacer" [style.height.px]="vsTopSpacerHeight()"></tr>
                    }
                    @for (item of vsVisibleItems(); track getRowId()(item); let localIdx = $index) {
                      @let rowIndex = vsStartIndex() + localIdx;
                      @let rowId = getRowId()(item);
                      @let isSelected = selectedRowIds().has(rowId);
                      <tr
                        class="ogrid-datagrid-row"
                        [class.ogrid-datagrid-row--selected]="isSelected"
                        [attr.data-row-id]="rowId"
                        (click)="onRowClick($event, rowId)"
                      >
                        @if (hasCheckboxCol()) {
                          <td class="ogrid-datagrid-td ogrid-datagrid-checkbox-col">
                            <div
                              class="ogrid-datagrid-checkbox-wrapper"
                              [attr.data-row-index]="rowIndex"
                              [attr.data-col-index]="0"
                              (click)="$event.stopPropagation()"
                            >
                              <input
                                type="checkbox"
                                [checked]="isSelected"
                                (change)="onRowCheckboxChange(rowId, $event, rowIndex)"
                                [attr.aria-label]="'Select row ' + (rowIndex + 1)"
                              />
                            </div>
                          </td>
                        }
                        @if (hasRowNumbersCol()) {
                          <td class="ogrid-datagrid-td ogrid-row-number-cell">
                            <div class="ogrid-row-number-cell-content">
                              {{ rowNumberOffset() + rowIndex + 1 }}
                            </div>
                          </td>
                        }
                        @for (colLayout of columnLayouts(); track colLayout.col.columnId; let colIdx = $index) {
                          <td
                            class="ogrid-datagrid-td"
                            [class.ogrid-datagrid-td--pinned-left]="colLayout.pinnedLeft"
                            [class.ogrid-datagrid-td--pinned-right]="colLayout.pinnedRight"
                            [style.minWidth.px]="colLayout.minWidth"
                            [style.width.px]="colLayout.width"
                            [style.maxWidth.px]="colLayout.width"
                          >
                            @let descriptor = getCellDescriptor(item, colLayout.col, rowIndex, colIdx);
                            @if (descriptor.mode === 'editing-inline') {
                              <ogrid-mat-inline-cell-editor
                                [value]="descriptor.value"
                                [item]="item"
                                [column]="colLayout.col"
                                [rowIndex]="rowIndex"
                                [editorType]="descriptor.editorType ?? 'text'"
                                (commit)="commitEdit(item, colLayout.col.columnId, descriptor.value, $event, rowIndex, descriptor.globalColIndex)"
                                (cancel)="cancelEdit()"
                              ></ogrid-mat-inline-cell-editor>
                            } @else if (descriptor.mode === 'editing-popover') {
                              @let editorProps = buildPopoverEditorProps(item, colLayout.col, descriptor);
                              <ogrid-mat-popover-cell-editor
                                [item]="item"
                                [column]="colLayout.col"
                                [rowIndex]="rowIndex"
                                [globalColIndex]="descriptor.globalColIndex"
                                [displayValue]="descriptor.displayValue"
                                [editorProps]="editorProps"
                                [onCancel]="() => cancelEdit()"
                              ></ogrid-mat-popover-cell-editor>
                            } @else {
                              @let content = resolveCellContent(colLayout.col, item, descriptor.displayValue);
                              @let cellStyle = resolveCellStyleFn(colLayout.col, item);
                              <div
                                class="ogrid-datagrid-cell"
                                [class.ogrid-datagrid-cell--active]="descriptor.isActive && !descriptor.isInRange"
                                [class.ogrid-datagrid-cell--in-range]="descriptor.isInRange"
                                [class.ogrid-datagrid-cell--in-cut-range]="descriptor.isInCutRange"
                                [class.ogrid-datagrid-cell--editable]="descriptor.canEditAny"
                                [class.ogrid-datagrid-cell--numeric]="colLayout.col.type === 'numeric'"
                                [class.ogrid-datagrid-cell--boolean]="colLayout.col.type === 'boolean'"
                                [attr.data-row-index]="rowIndex"
                                [attr.data-col-index]="descriptor.globalColIndex"
                                [attr.data-in-range]="descriptor.isInRange ? 'true' : null"
                                [attr.tabindex]="descriptor.isActive ? 0 : -1"
                                (mousedown)="onCellMouseDown($event, rowIndex, descriptor.globalColIndex)"
                                (click)="onCellClick(rowIndex, descriptor.globalColIndex)"
                                (contextmenu)="onCellContextMenu($event)"
                                (dblclick)="descriptor.canEditAny ? onCellDblClick(descriptor.rowId, colLayout.col.columnId) : null"
                                [attr.role]="descriptor.canEditAny ? 'button' : null"
                                [style]="cellStyle ?? undefined"
                              >
                                {{ content }}
                                @if (descriptor.canEditAny && descriptor.isSelectionEndCell) {
                                  <div
                                    class="ogrid-datagrid-fill-handle"
                                    (mousedown)="onFillHandleMouseDown($event)"
                                    aria-label="Fill handle"
                                  ></div>
                                }
                              </div>
                            }
                          </td>
                        }
                      </tr>
                    }
                    @if (vsEnabled() && vsBottomSpacerHeight() > 0) {
                      <tr class="ogrid-datagrid-vs-spacer" [style.height.px]="vsBottomSpacerHeight()"></tr>
                    }
                  </tbody>
                }
              </table>

              <ogrid-marching-ants-overlay
                [containerEl]="tableContainerEl()"
                [selectionRange]="state().interaction.selectionRange"
                [copyRange]="state().interaction.copyRange"
                [cutRange]="state().interaction.cutRange"
                [colOffset]="state().layout.colOffset"
                [columnSizingVersion]="columnSizingVersion()"
              ></ogrid-marching-ants-overlay>

              @if (showEmptyInGrid() && emptyState()) {
                <div class="ogrid-datagrid-empty">
                  <div class="ogrid-datagrid-empty__title">No results found</div>
                  <div class="ogrid-datagrid-empty__message">
                    @if (emptyState()!.message != null) {
                      {{ emptyState()!.message }}
                    } @else if (emptyState()!.hasActiveFilters) {
                      No items match your current filters. Try adjusting your search or
                      <button class="ogrid-datagrid-empty__clear" (click)="emptyState()!.onClearAll?.()">clear all filters</button>
                      to see all items.
                    } @else {
                      There are no items available at this time.
                    }
                  </div>
                </div>
              }
            </div>
          </div>
        </div>

        @if (columnReorderService.isDragging() && columnReorderService.dropIndicatorX() !== null) {
          <div class="ogrid-datagrid-drop-indicator" [style.left.px]="columnReorderService.dropIndicatorX()"></div>
        }

        @if (menuPosition()) {
          <div
            class="ogrid-datagrid-context-menu-overlay"
            (click)="closeContextMenu()"
            (contextmenu)="$event.preventDefault(); closeContextMenu()"
          >
            <ogrid-grid-context-menu
              [x]="menuPosition()!.x"
              [y]="menuPosition()!.y"
              [hasSelection]="hasCellSelection()"
              [canUndo]="canUndo()"
              [canRedo]="canRedo()"
              (undoAction)="onUndo()"
              (redoAction)="onRedo()"
              (copyAction)="handleCopy()"
              (cutAction)="handleCut()"
              (pasteAction)="handlePaste()"
              (selectAllAction)="handleSelectAllCells()"
              (closeAction)="closeContextMenu()"
            />
          </div>
        }
      </div>

      @if (statusBarConfig()) {
        <ogrid-status-bar
          [totalCount]="statusBarConfig()!.totalCount"
          [filteredCount]="statusBarConfig()!.filteredCount"
          [selectedCount]="statusBarConfig()!.selectedCount ?? selectedRowIds().size"
          [selectedCellCount]="selectionCellCount()"
          [aggregation]="statusBarConfig()!.aggregation"
          [suppressRowCount]="statusBarConfig()!.suppressRowCount"
        />
      }

      @if (isLoading()) {
        <div class="ogrid-datagrid-loading-overlay">
          <div class="ogrid-datagrid-loading-inner">
            <div class="ogrid-datagrid-spinner"></div>
            <span>{{ loadingMessage() }}</span>
          </div>
        </div>
      }
    </div>
  `,
  styles: [`
    :host { display: block; }
    .ogrid-datagrid-root { position: relative; flex: 1; min-height: 0; display: flex; flex-direction: column; }
    .ogrid-datagrid-wrapper {
      position: relative; flex: 1; min-height: 0; width: 100%; max-width: 100%;
      overflow-x: hidden; overflow-y: auto; background: #fff;
      will-change: scroll-position; outline: none;
    }
    .ogrid-datagrid-wrapper [data-drag-range] { background: rgba(33, 115, 70, 0.12) !important; }
    .ogrid-datagrid-wrapper--fit { width: fit-content; }
    .ogrid-datagrid-wrapper--overflow-x { overflow-x: auto; }
    .ogrid-datagrid-scroll-wrapper { display: flex; flex-direction: column; min-height: 100%; }
    .ogrid-datagrid-table-wrapper--loading { position: relative; opacity: 0.6; }
    .ogrid-datagrid-table {
      width: 100%; border-collapse: collapse; overflow: hidden; table-layout: fixed;
    }
    .ogrid-datagrid-thead {
      position: sticky; top: 0; z-index: 8; background: rgba(0,0,0,0.04);
    }
    .ogrid-datagrid-thead th { background: rgba(0,0,0,0.04); }
    .ogrid-datagrid-header-row { background: rgba(0,0,0,0.04); }
    .ogrid-datagrid-th {
      font-weight: 600; position: relative; padding: 6px 10px; text-align: left;
      font-size: 14px; border-bottom: 1px solid rgba(0,0,0,0.12);
    }
    .ogrid-datagrid-th--pinned-left {
      position: sticky; left: 0; z-index: 9; background: rgba(0,0,0,0.04); will-change: transform;
      border-left: 2px solid var(--mat-sys-primary, #1976d2);
    }
    .ogrid-datagrid-th--pinned-right {
      position: sticky; right: 0; z-index: 9; background: rgba(0,0,0,0.04); will-change: transform;
      border-right: 2px solid var(--mat-sys-primary, #1976d2);
    }
    .ogrid-datagrid-group-header {
      text-align: center; font-weight: 600; border-bottom: 2px solid rgba(0,0,0,0.12); padding: 6px;
    }
    .ogrid-datagrid-checkbox-col {
      width: ${CHECKBOX_COLUMN_WIDTH}px; min-width: ${CHECKBOX_COLUMN_WIDTH}px;
      max-width: ${CHECKBOX_COLUMN_WIDTH}px; text-align: center;
    }
    .ogrid-datagrid-checkbox-wrapper { display: flex; align-items: center; justify-content: center; }
    .ogrid-row-number-header, .ogrid-row-number-cell {
      width: ${ROW_NUMBER_COLUMN_WIDTH}px; min-width: ${ROW_NUMBER_COLUMN_WIDTH}px;
      max-width: ${ROW_NUMBER_COLUMN_WIDTH}px; text-align: center;
      background: rgba(0,0,0,0.04); font-weight: 600;
      font-variant-numeric: tabular-nums; color: rgba(0,0,0,0.6);
      position: sticky; left: 0; z-index: 3;
    }
    .ogrid-row-number-header { z-index: 4; }
    .ogrid-row-number-header-content, .ogrid-row-number-cell-content {
      display: flex; align-items: center; justify-content: center;
    }
    .ogrid-datagrid-row { }
    .ogrid-datagrid-row:hover { background: rgba(0,0,0,0.04); }
    .ogrid-datagrid-row--selected { background: rgba(25,118,210,0.08); }
    .ogrid-datagrid-td { position: relative; padding: 0; height: 1px; border-bottom: 1px solid rgba(0,0,0,0.06); }
    .ogrid-datagrid-td--pinned-left {
      position: sticky; left: 0; z-index: 6; background: #fff; will-change: transform;
      border-left: 2px solid var(--mat-sys-primary, #1976d2);
    }
    .ogrid-datagrid-td--pinned-right {
      position: sticky; right: 0; z-index: 6; background: #fff; will-change: transform;
      border-right: 2px solid var(--mat-sys-primary, #1976d2);
    }
    .ogrid-datagrid-cell {
      width: 100%; height: 100%; display: flex; align-items: center; min-width: 0;
      padding: 6px 10px; box-sizing: border-box; overflow: hidden;
      text-overflow: ellipsis; white-space: nowrap; user-select: none; outline: none;
      font-size: 14px;
    }
    .ogrid-datagrid-cell--numeric { justify-content: flex-end; text-align: right; }
    .ogrid-datagrid-cell--boolean { justify-content: center; text-align: center; }
    .ogrid-datagrid-cell--editable { cursor: cell; }
    .ogrid-datagrid-cell--active {
      outline: 2px solid var(--ogrid-selection, #217346); outline-offset: -1px;
      z-index: 2; position: relative; overflow: visible;
    }
    .ogrid-datagrid-cell--in-range { background: var(--ogrid-bg-range, rgba(33, 115, 70, 0.12)); }
    .ogrid-datagrid-cell--in-cut-range { background: rgba(0,0,0,0.04); opacity: 0.7; }
    .ogrid-datagrid-cell--editing { padding: 0; }
    .ogrid-datagrid-editor-input {
      width: 100%; height: 100%; padding: 6px 10px; border: 2px solid var(--ogrid-selection, #217346);
      box-sizing: border-box; font-size: 14px; outline: none; font-family: inherit; line-height: inherit;
    }
    .ogrid-datagrid-cell--numeric .ogrid-datagrid-editor-input {
      text-align: right;
    }
    .ogrid-datagrid-editor-select {
      width: 100%; height: 100%; padding: 4px 8px; border: 2px solid var(--ogrid-selection, #217346);
      box-sizing: border-box; font-size: 14px;
    }
    .ogrid-datagrid-fill-handle {
      position: absolute; right: -3px; bottom: -3px; width: 7px; height: 7px;
      background: var(--ogrid-selection, #217346);
      border: 1px solid var(--ogrid-bg, #fff); border-radius: 1px;
      cursor: crosshair; pointer-events: auto; z-index: 3;
    }
    .ogrid-datagrid-resize-handle {
      position: absolute; top: 0; right: -3px; bottom: 0; width: 8px;
      cursor: col-resize; user-select: none;
    }
    .ogrid-datagrid-resize-handle::after {
      content: ''; position: absolute; top: 0; right: 3px; bottom: 0; width: 2px;
    }
    .ogrid-datagrid-resize-handle:hover::after { background: var(--mat-sys-primary, #1976d2); }
    .ogrid-datagrid-resize-handle:active::after { background: var(--mat-sys-primary, #1565c0); }
    .ogrid-datagrid-empty {
      padding: 32px 16px; text-align: center; border-top: 1px solid rgba(0,0,0,0.12);
      background: rgba(0,0,0,0.04);
    }
    .ogrid-datagrid-empty__title { font-size: 18px; font-weight: 600; margin-bottom: 8px; }
    .ogrid-datagrid-empty__message { font-size: 14px; color: rgba(0,0,0,0.6); }
    .ogrid-datagrid-empty__clear {
      background: none; border: none; color: var(--mat-sys-primary, #1976d2);
      cursor: pointer; font-size: inherit; text-decoration: underline; padding: 0;
    }
    .ogrid-datagrid-loading-overlay {
      position: absolute; inset: 0; z-index: 2;
      display: flex; align-items: center; justify-content: center;
      background: rgba(255,255,255,0.7);
    }
    .ogrid-datagrid-loading-inner {
      display: flex; flex-direction: column; align-items: center; gap: 8px;
      padding: 16px; background: #fff; border: 1px solid rgba(0,0,0,0.12); border-radius: 4px;
    }
    .ogrid-datagrid-spinner {
      width: 24px; height: 24px; border: 3px solid rgba(0,0,0,0.12);
      border-top-color: var(--mat-sys-primary, #1976d2);
      border-radius: 50%; animation: ogrid-spin 0.8s linear infinite;
    }
    @keyframes ogrid-spin { to { transform: rotate(360deg); } }
    .ogrid-datagrid-drop-indicator {
      position: absolute; top: 0; bottom: 0; width: 3px;
      background: var(--ogrid-primary, #217346);
      pointer-events: none; z-index: 100; transition: left 0.05s;
    }
    .ogrid-datagrid-context-menu-overlay {
      position: fixed; inset: 0; z-index: 1000;
    }
  `],
})
export class DataGridTableComponent<T> extends BaseDataGridTableComponent<T> {
  readonly propsInput = input.required<IOGridDataGridProps<T>>({ alias: 'props' });

  private readonly wrapperRef = viewChild<ElementRef<HTMLElement>>('wrapperEl');
  private readonly tableContainerRef = viewChild<ElementRef<HTMLElement>>('tableContainerEl');

  constructor() {
    super();
    this.initBase();
  }

  protected getProps(): IOGridDataGridProps<T> | undefined {
    return this.propsInput();
  }

  protected getWrapperRef(): ElementRef<HTMLElement> | undefined {
    return this.wrapperRef();
  }

  protected getTableContainerRef(): ElementRef<HTMLElement> | undefined {
    return this.tableContainerRef();
  }
}

// packages/vue-radix/src/DataGridTable/DataGridTable.vue
<script setup lang="ts">
import { computed } from 'vue';
import {
  useDataGridTableSetup,
  getCellRenderDescriptor,
  resolveCellDisplayContent,
  buildHeaderRows,
  CHECKBOX_COLUMN_WIDTH,
  DEFAULT_MIN_COLUMN_WIDTH,
  type IOGridDataGridProps,
  type IColumnDef,
  type ICellEditorProps,
} from '@alaarab/ogrid-vue';
import ColumnHeaderFilter from '../ColumnHeaderFilter/ColumnHeaderFilter.vue';
import InlineCellEditor from './InlineCellEditor.vue';
import StatusBar from './StatusBar.vue';
import GridContextMenu from './GridContextMenu.vue';
import MarchingAntsOverlay from './MarchingAntsOverlay.vue';

const props = defineProps<{
  gridProps: IOGridDataGridProps<any>;
}>();

const propsRef = computed(() => props.gridProps);

const {
  wrapperRef,
  tableContainerRef,
  tableRef,
  lastMouseShift,
  state,
  columnReorder: { isDragging: isReorderDragging, dropIndicatorX, handleHeaderMouseDown: handleReorderMouseDown },
  virtualScroll: { containerRef: vsContainerRef, visibleRange, totalHeight, scrollToRow },
  virtualScrollEnabled,
  columnResize: { handleResizeStart, getColumnWidth },
} = useDataGridTableSetup({ props: propsRef });

// Computed state refs
const layout = computed(() => state.layout.value);
const rowSel = computed(() => state.rowSelection.value);
const editing = computed(() => state.editing.value);
const interaction = computed(() => state.interaction.value);
const ctxMenu = computed(() => state.contextMenu.value);
const viewModels = computed(() => state.viewModels.value);

const headerRows = computed(() => buildHeaderRows(props.gridProps.columns, props.gridProps.visibleColumns));

const handleSingleRowClick = (e: MouseEvent, rowId: string | number) => {
  if (props.gridProps.rowSelection !== 'single') return;
  const sel = rowSel.value.selectedRowIds;
  rowSel.value.updateSelection(sel.has(rowId) ? new Set() : new Set([rowId]));
};

const handleRowCheckboxChange = (rowId: string | number, checked: boolean, rowIndex: number) => {
  rowSel.value.handleRowCheckboxChange(rowId, checked, rowIndex, lastMouseShift.value);
};

const isRowSelected = (rowId: string | number) => {
  return rowSel.value.selectedRowIds.has(rowId);
};

const handleKeyDown = (e: KeyboardEvent) => {
  interaction.value.handleGridKeyDown(e);
};

const NOOP = () => {};

// Helper methods for template
const getCellRenderData = (item: any, col: IColumnDef<any>, rowIndex: number, colIndex: number) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);

  if (descriptor.renderMode === 'inline-editor' && descriptor.editorProps) {
    return { type: 'editor', props: descriptor.editorProps };
  }

  return { type: 'content', descriptor };
};

const getCellDisplayValue = (item: any, col: IColumnDef<any>, rowIndex: number, colIndex: number) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  return resolveCellDisplayContent(col, item, descriptor.displayValue);
};

const getCellClass = (rowIndex: number, colIndex: number, col: IColumnDef<any>, item: any) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  const classes = ['ogrid-cell'];

  if (descriptor.isActive && !descriptor.isInRange) {
    classes.push('ogrid-active-cell');
  }

  if (descriptor.isInRange) {
    classes.push('ogrid-selected-cell');
  }

  return classes.join(' ');
};

const getCellStyle = (rowIndex: number, colIndex: number, col: IColumnDef<any>) => {
  const descriptor = getCellRenderDescriptor(col, {}, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  const style: Record<string, string> = {
    width: `${getColumnWidth(col.columnId)}px`,
  };

  if (descriptor.canEditAny) {
    style.cursor = 'cell';
  }

  if (descriptor.isInCutRange) {
    style.backgroundColor = 'rgba(0,0,0,0.04)';
    style.opacity = '0.7';
  }

  return style;
};

const shouldShowFillHandle = (rowIndex: number, colIndex: number) => {
  const range = interaction.value.selectionRange;
  if (!range) return false;

  const descriptor = getCellRenderDescriptor({}, {}, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  return descriptor.canEditAny && rowIndex === range.endRow && colIndex === range.endCol;
};
</script>

<template>
  <div ref="wrapperRef" class="ogrid-wrapper">
    <!-- Loading State -->
    <div v-if="gridProps.isLoading" class="ogrid-loading">
      <div class="loading-spinner"></div>
      <div>{{ gridProps.loadingMessage || 'Loading...' }}</div>
    </div>

    <!-- Main Grid -->
    <div
      v-else
      ref="tableContainerRef"
      class="ogrid-table-container"
      tabindex="0"
      @keydown="handleKeyDown"
      @mousedown="(e) => { lastMouseShift = e.shiftKey; }"
      @contextmenu.prevent
    >
      <!-- Drop Indicator for Column Reorder -->
      <div
        v-if="isReorderDragging && dropIndicatorX !== null"
        class="ogrid-drop-indicator"
        :style="{ left: `${dropIndicatorX}px` }"
      ></div>

      <table
        ref="tableRef"
        class="ogrid-table"
        :style="{
          width: gridProps.layoutMode === 'content' ? 'auto' : '100%',
        }"
      >
        <!-- Header -->
        <thead>
          <tr
            v-for="(row, rowIdx) in headerRows"
            :key="rowIdx"
            class="ogrid-header-row"
          >
            <!-- Checkbox Header -->
            <th
              v-if="layout.hasCheckboxCol && rowIdx === 0"
              :rowspan="headerRows.length"
              class="ogrid-header-cell ogrid-selection-header"
              :style="{ width: `${CHECKBOX_COLUMN_WIDTH}px` }"
            >
              <input
                v-if="gridProps.rowSelection === 'multiple'"
                type="checkbox"
                :checked="rowSel.allSelected"
                @change="rowSel.handleSelectAll"
                aria-label="Select all rows"
                class="ogrid-checkbox"
              />
            </th>

            <!-- Header Cells -->
            <th
              v-for="cell in row"
              :key="cell.column?.columnId || `group-${rowIdx}`"
              :colspan="cell.colspan"
              :rowspan="cell.rowspan"
              class="ogrid-header-cell"
              :style="{
                width: cell.column ? `${getColumnWidth(cell.column.columnId)}px` : undefined,
              }"
              @mousedown="cell.column && !cell.isGroup ? (e) => handleReorderMouseDown(cell.column.columnId, e) : undefined"
            >
              <div class="ogrid-header-content">
                <span class="ogrid-header-label">
                  {{ cell.column?.name || cell.groupName }}
                </span>

                <ColumnHeaderFilter
                  v-if="cell.column && !cell.isGroup"
                  :columnKey="cell.column.columnId"
                  :columnName="cell.column.name"
                  :filterType="cell.column.filterable?.type || 'none'"
                  :isSorted="cell.column.isSorted"
                  :isSortedDescending="cell.column.isSortedDescending"
                  :onSort="cell.column.onSort"
                />
              </div>

              <!-- Resize Handle -->
              <div
                v-if="cell.column && cell.column.resizable !== false"
                class="ogrid-resize-handle"
                @mousedown="(e) => handleResizeStart(e, cell.column!.columnId)"
              ></div>
            </th>
          </tr>
        </thead>

        <!-- Body -->
        <tbody v-if="!viewModels.showEmptyInGrid">
          <tr
            v-for="(item, rowIndex) in gridProps.items"
            :key="gridProps.getRowId(item)"
            :data-row-id="gridProps.getRowId(item)"
            :class="{
              'ogrid-row': true,
              'ogrid-selected-row': isRowSelected(gridProps.getRowId(item)),
            }"
            @click="(e) => handleSingleRowClick(e, gridProps.getRowId(item))"
          >
            <!-- Checkbox Cell -->
            <td
              v-if="layout.hasCheckboxCol"
              class="ogrid-cell ogrid-selection-cell"
              @click.stop
            >
              <input
                type="checkbox"
                :checked="isRowSelected(gridProps.getRowId(item))"
                @change="(e) => handleRowCheckboxChange(gridProps.getRowId(item), (e.target as HTMLInputElement).checked, rowIndex)"
                :aria-label="`Select row ${rowIndex + 1}`"
                class="ogrid-checkbox"
              />
            </td>

            <!-- Data Cells -->
            <td
              v-for="(col, colIndex) in layout.visibleCols"
              :key="col.columnId"
              :data-row-index="rowIndex"
              :data-col-index="layout.colOffset + colIndex"
              :class="getCellClass(rowIndex, layout.colOffset + colIndex, col, item)"
              :style="getCellStyle(rowIndex, layout.colOffset + colIndex, col)"
              @mousedown="(e) => interaction.handleCellMouseDown(e, rowIndex, layout.colOffset + colIndex)"
              @contextmenu="(e) => ctxMenu.handleCellContextMenu(e, rowIndex, layout.colOffset + colIndex)"
            >
              <div class="ogrid-cell-content">
                <component
                  v-if="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).type === 'editor'"
                  :is="InlineCellEditor"
                  v-bind="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).props"
                />
                <template v-else>
                  {{ getCellDisplayValue(item, col, rowIndex, layout.colOffset + colIndex) }}

                  <!-- Fill Handle (on selection end cell) -->
                  <div
                    v-if="shouldShowFillHandle(rowIndex, layout.colOffset + colIndex)"
                    class="ogrid-fill-handle"
                    @mousedown="interaction.handleFillHandleMouseDown"
                    aria-label="Fill handle"
                  ></div>
                </template>
              </div>
            </td>
          </tr>
        </tbody>
      </table>

      <!-- Empty State -->
      <div v-if="viewModels.showEmptyInGrid && gridProps.emptyState" class="ogrid-empty-state">
        <div v-if="gridProps.emptyState.render">
          <!-- Custom render function -->
        </div>
        <div v-else>
          <div class="ogrid-empty-title">No results found</div>
          <div class="ogrid-empty-message">
            <template v-if="gridProps.emptyState.message">
              {{ gridProps.emptyState.message }}
            </template>
            <template v-else-if="gridProps.emptyState.hasActiveFilters">
              No items match your current filters. Try adjusting your search or
              <button
                class="ogrid-empty-clear-btn"
                @click="gridProps.emptyState.onClearAll"
              >
                clear all filters
              </button>
              to see all items.
            </template>
            <template v-else>
              No data available
            </template>
          </div>
        </div>
      </div>

      <!-- Marching Ants Overlay -->
      <MarchingAntsOverlay
        :containerRef="tableContainerRef"
        :selectionRange="interaction.selectionRange"
        :copyRange="interaction.copyRange"
        :cutRange="interaction.cutRange"
        :colOffset="layout.colOffset"
      />
    </div>

    <!-- Context Menu (Teleported to body) -->
    <Teleport to="body" v-if="ctxMenu.menuPosition">
      <GridContextMenu
        :x="ctxMenu.menuPosition.x"
        :y="ctxMenu.menuPosition.y"
        :hasSelection="!!interaction.selectionRange"
        :canUndo="interaction.canUndo"
        :canRedo="interaction.canRedo"
        :onUndo="interaction.onUndo || NOOP"
        :onRedo="interaction.onRedo || NOOP"
        :onCopy="interaction.handleCopy"
        :onCut="interaction.handleCut"
        :onPaste="() => interaction.handlePaste()"
        :onSelectAll="interaction.handleSelectAllCells"
        :onClose="ctxMenu.closeContextMenu"
      />
    </Teleport>

    <!-- Status Bar -->
    <StatusBar
      v-if="viewModels.statusBarConfig"
      :totalCount="viewModels.statusBarConfig.totalCount"
      :filteredCount="viewModels.statusBarConfig.filteredCount"
      :selectedCount="viewModels.statusBarConfig.selectedCount ?? rowSel.selectedRowIds.size"
      :selectedCellCount="interaction.selectionRange
        ? (Math.abs(interaction.selectionRange.endRow - interaction.selectionRange.startRow) + 1) *
          (Math.abs(interaction.selectionRange.endCol - interaction.selectionRange.startCol) + 1)
        : undefined"
      :aggregation="viewModels.statusBarConfig.aggregation"
      :suppressRowCount="viewModels.statusBarConfig.suppressRowCount"
    />
  </div>
</template>

<style scoped lang="scss">
@import './DataGridTable.module.scss';

.ogrid-wrapper {
  position: relative;
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.ogrid-loading {
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  padding: 48px;
  gap: 16px;
  color: var(--ogrid-muted, #888);
  font-size: 14px;
}

.loading-spinner {
  width: 32px;
  height: 32px;
  border: 3px solid var(--ogrid-border, #e0e0e0);
  border-top-color: var(--ogrid-primary, #0066cc);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}

.ogrid-table-container {
  flex: 1;
  overflow: auto;
  position: relative;
  outline: none;
}

.ogrid-drop-indicator {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 3px;
  background: var(--ogrid-primary, #217346);
  pointer-events: none;
  z-index: 100;
}

.ogrid-table {
  border-collapse: collapse;
  font-size: 14px;
  background: var(--ogrid-bg, #fff);
}

.ogrid-header-row {
  position: sticky;
  top: 0;
  z-index: 2;
}

.ogrid-header-cell {
  position: relative;
  background: var(--ogrid-header-bg, #f5f5f5);
  border-bottom: 1px solid var(--ogrid-border, #e0e0e0);
  border-right: 1px solid var(--ogrid-border, #e0e0e0);
  padding: 8px 12px;
  text-align: left;
  font-weight: 600;
  user-select: none;
  cursor: grab;

  &:last-child {
    border-right: none;
  }

  &:active {
    cursor: grabbing;
  }
}

.ogrid-header-content {
  display: flex;
  align-items: center;
  gap: 4px;
}

.ogrid-header-label {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ogrid-resize-handle {
  position: absolute;
  right: 0;
  top: 0;
  bottom: 0;
  width: 4px;
  cursor: col-resize;
  z-index: 10;

  &:hover {
    background: var(--ogrid-primary, #0066cc);
  }
}

.ogrid-row {
  &:hover {
    background: var(--ogrid-hover-bg, #f9f9f9);
  }
}

.ogrid-selected-row {
  background: var(--ogrid-selected-bg, #e3f2fd);
}

.ogrid-cell {
  padding: 0;
  border-bottom: 1px solid var(--ogrid-border, #e0e0e0);
  border-right: 1px solid var(--ogrid-border, #e0e0e0);
  position: relative;

  &:last-child {
    border-right: none;
  }
}

.ogrid-cell-content {
  padding: 8px 12px;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
  position: relative;
}

.ogrid-active-cell {
  outline: 2px solid var(--ogrid-active-border, #0078d4);
  outline-offset: -2px;
  z-index: 1;
}

.ogrid-selected-cell {
  background: var(--ogrid-bg-range, rgba(33, 115, 70, 0.12));
}

.ogrid-fill-handle {
  position: absolute;
  right: -3px;
  bottom: -3px;
  width: 7px;
  height: 7px;
  background-color: var(--ogrid-selection, #217346);
  border: 1px solid var(--ogrid-bg, #fff);
  border-radius: 1px;
  cursor: crosshair;
  pointer-events: auto;
  z-index: 3;
}

.ogrid-selection-header,
.ogrid-selection-cell {
  width: 40px;
  text-align: center;
  padding: 8px;
}

.ogrid-checkbox {
  cursor: pointer;
  width: 16px;
  height: 16px;
}

.ogrid-empty-state {
  padding: 32px 16px;
  text-align: center;
  border-top: 1px solid var(--ogrid-border, #e0e0e0);
  background: var(--ogrid-statusbar-bg, #f5f5f5);
}

.ogrid-empty-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: 8px;
}

.ogrid-empty-message {
  font-size: 0.875rem;
  color: var(--ogrid-muted, #888);
}

.ogrid-empty-clear-btn {
  background: none;
  border: none;
  color: var(--ogrid-primary, #0066cc);
  text-decoration: underline;
  cursor: pointer;
  padding: 0;
  font: inherit;

  &:hover {
    color: var(--ogrid-primary-hover, #005a9e);
  }
}
</style>
