// packages/radix/src/DataGridTable/InlineCellEditor.tsx
import * as React from 'react';
import * as Checkbox from '@radix-ui/react-checkbox';
import type { IColumnDef } from '@alaarab/ogrid-core';
import { useInlineCellEditorState, useRichSelectState } from '@alaarab/ogrid-core';

// Match .cellContent layout so column width doesn't shift during editing
const editorWrapperStyle: React.CSSProperties = {
  width: '100%',
  height: '100%',
  display: 'flex',
  alignItems: 'center',
  padding: '6px 10px',
  boxSizing: 'border-box',
  overflow: 'hidden',
  minWidth: 0,
};

const editorInputStyle: React.CSSProperties = {
  width: '100%',
  padding: 0,
  border: 'none',
  background: 'transparent',
  color: 'inherit',
  font: 'inherit',
  fontSize: '13px',
  outline: 'none',
  minWidth: 0,
};

export interface InlineCellEditorProps<T> {
  value: unknown;
  item: T;
  column: IColumnDef<T>;
  rowIndex: number;
  editorType: 'text' | 'select' | 'checkbox' | 'richSelect' | 'date';
  onCommit: (value: unknown) => void;
  onCancel: () => void;
}

export function InlineCellEditor<T>(props: InlineCellEditorProps<T>): React.ReactElement {
  const { value, column, editorType, onCommit, onCancel } = props;
  const wrapperRef = React.useRef<HTMLDivElement>(null);
  const { localValue, setLocalValue, handleKeyDown, handleBlur, commit, cancel } =
    useInlineCellEditorState({ value, editorType, onCommit, onCancel });

  const richSelectValues = (column.cellEditorParams?.values as unknown[]) ?? [];
  const richSelectFormatValue = column.cellEditorParams?.formatValue as ((v: unknown) => string) | undefined;
  const richSelect = useRichSelectState({
    values: richSelectValues,
    formatValue: richSelectFormatValue,
    initialValue: value,
    onCommit,
    onCancel,
  });

  React.useEffect(() => {
    const input = wrapperRef.current?.querySelector('input');
    input?.focus();
  }, []);

  if (editorType === 'richSelect') {
    return (
      <div ref={wrapperRef} style={{ ...editorWrapperStyle, position: 'relative' }}>
        <input
          type="text"
          value={richSelect.searchText}
          onChange={(e) => richSelect.setSearchText(e.target.value)}
          onKeyDown={richSelect.handleKeyDown}
          placeholder="Search..."
          autoFocus
          style={editorInputStyle}
        />
        <div
          style={{
            position: 'absolute',
            top: '100%',
            left: 0,
            right: 0,
            maxHeight: 200,
            overflowY: 'auto',
            background: 'var(--ogrid-bg, #fff)',
            border: '1px solid var(--ogrid-border, #ccc)',
            zIndex: 10,
            boxShadow: '0 4px 16px rgba(0,0,0,0.2)',
          }}
          role="listbox"
        >
          {richSelect.filteredValues.map((v, i) => (
            <div
              key={String(v)}
              role="option"
              aria-selected={i === richSelect.highlightedIndex}
              onClick={() => richSelect.selectValue(v)}
              style={{
                padding: '6px 8px',
                cursor: 'pointer',
                color: 'var(--ogrid-fg, #242424)',
                background: i === richSelect.highlightedIndex ? 'var(--ogrid-bg-hover, #e8f0fe)' : undefined,
              }}
            >
              {richSelect.getDisplayText(v)}
            </div>
          ))}
          {richSelect.filteredValues.length === 0 && (
            <div style={{ padding: '6px 8px', color: 'var(--ogrid-muted, #999)' }}>No matches</div>
          )}
        </div>
      </div>
    );
  }

  if (editorType === 'checkbox') {
    const checked = value === true;
    return (
      <Checkbox.Root
        checked={checked}
        onCheckedChange={(c: boolean | 'indeterminate') => commit(c === true)}
        onKeyDown={(e: React.KeyboardEvent) => e.key === 'Escape' && (e.preventDefault(), cancel())}
      >
        <Checkbox.Indicator>✓</Checkbox.Indicator>
      </Checkbox.Root>
    );
  }

  if (editorType === 'select') {
    const values = (column.cellEditorParams?.values as unknown[]) ?? [];
    return (
      <div style={editorWrapperStyle}>
        <select
          value={value !== null && value !== undefined ? String(value) : ''}
          onChange={(e) => commit(e.target.value)}
          onKeyDown={(e: React.KeyboardEvent) => e.key === 'Escape' && (e.preventDefault(), cancel())}
          autoFocus
          style={{
            width: '100%',
            padding: 0,
            border: 'none',
            background: 'transparent',
            color: 'inherit',
            font: 'inherit',
            fontSize: '13px',
            cursor: 'pointer',
            outline: 'none',
          }}
        >
          {values.map((v) => (
            <option key={String(v)} value={String(v)}>
              {String(v)}
            </option>
          ))}
        </select>
      </div>
    );
  }

  if (editorType === 'date') {
    return (
      <div ref={wrapperRef} style={editorWrapperStyle}>
        <input
          type="date"
          value={localValue}
          onChange={(e) => setLocalValue(e.target.value)}
          onBlur={handleBlur}
          onKeyDown={handleKeyDown}
          style={editorInputStyle}
          autoFocus
        />
      </div>
    );
  }

  return (
    <div ref={wrapperRef} style={editorWrapperStyle}>
      <input
        type="text"
        value={localValue}
        onChange={(e) => setLocalValue(e.target.value)}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        style={editorInputStyle}
        autoFocus
      />
    </div>
  );
}

// packages/vue-radix/src/DataGridTable/InlineCellEditor.vue
<script setup lang="ts">
import { ref, computed, onMounted } from 'vue';
import type { IColumnDefinition } from '@alaarab/ogrid-vue';
import {
  useInlineCellEditorState,
  useRichSelectState,
} from '@alaarab/ogrid-vue';

export interface InlineCellEditorProps<T = any> {
  value: unknown;
  item: T;
  column: IColumnDefinition;
  rowIndex: number;
  editorType: 'text' | 'select' | 'checkbox' | 'richSelect' | 'date';
  onCommit: (value: unknown) => void;
  onCancel: () => void;
}

const props = defineProps<InlineCellEditorProps>();

const wrapperRef = ref<HTMLDivElement | null>(null);

const {
  localValue,
  setLocalValue,
  handleKeyDown,
  handleBlur,
  commit,
  cancel,
} = useInlineCellEditorState({
  value: props.value,
  editorType: props.editorType,
  onCommit: props.onCommit,
  onCancel: props.onCancel,
});

const richSelect = useRichSelectState({
  values: (props.column.cellEditorParams?.values as unknown[]) ?? [],
  formatValue: props.column.cellEditorParams?.formatValue as ((v: unknown) => string) | undefined,
  initialValue: props.value,
  onCommit: props.onCommit,
  onCancel: props.onCancel,
});

const selectValues = computed(() => (props.column.cellEditorParams?.values as unknown[]) ?? []);

const checkboxChecked = computed(() => props.value === true);

const handleCheckboxChange = (val: boolean) => {
  commit(val);
};

const handleSelectChange = (e: Event) => {
  const target = e.target as HTMLSelectElement;
  commit(target.value);
};

onMounted(() => {
  const input = wrapperRef.value?.querySelector('input');
  if (input) {
    input.focus();
    input.select();
  }
});
</script>

<template>
  <!-- Rich Select -->
  <div v-if="editorType === 'richSelect'" ref="wrapperRef" class="rich-select-wrapper">
    <input
      type="text"
      :value="richSelect.searchText.value"
      @input="(e) => richSelect.setSearchText((e.target as HTMLInputElement).value)"
      @keydown="richSelect.handleKeyDown"
      placeholder="Search..."
      class="rich-select-input"
      autofocus
    />
    <div class="rich-select-dropdown" role="listbox">
      <div
        v-for="(v, i) in richSelect.filteredValues.value"
        :key="String(v)"
        role="option"
        :aria-selected="i === richSelect.highlightedIndex.value"
        :class="['rich-select-option', { highlighted: i === richSelect.highlightedIndex.value }]"
        @click="() => richSelect.selectValue(v)"
      >
        {{ richSelect.getDisplayText(v) }}
      </div>
      <div v-if="richSelect.filteredValues.value.length === 0" class="rich-select-no-matches">
        No matches
      </div>
    </div>
  </div>

  <!-- Checkbox -->
  <div v-else-if="editorType === 'checkbox'" class="checkbox-editor-wrapper">
    <input
      type="checkbox"
      :checked="checkboxChecked"
      @change="(e: Event) => handleCheckboxChange((e.target as HTMLInputElement).checked)"
      @keydown.esc.prevent="cancel"
      class="checkbox-editor"
      autofocus
    />
  </div>

  <!-- Select -->
  <div v-else-if="editorType === 'select'" class="select-wrapper">
    <select
      :value="value !== null && value !== undefined ? String(value) : ''"
      @change="handleSelectChange"
      @keydown.esc.prevent="cancel"
      class="select-editor"
      autofocus
    >
      <option v-for="v in selectValues" :key="String(v)" :value="String(v)">
        {{ String(v) }}
      </option>
    </select>
  </div>

  <!-- Date -->
  <div v-else-if="editorType === 'date'" ref="wrapperRef" class="editor-wrapper">
    <input
      type="date"
      :value="localValue"
      @input="(e) => setLocalValue((e.target as HTMLInputElement).value)"
      @blur="handleBlur"
      @keydown="handleKeyDown"
      class="editor-input"
      autofocus
    />
  </div>

  <!-- Text (default) -->
  <div v-else ref="wrapperRef" class="editor-wrapper">
    <input
      type="text"
      :value="localValue"
      @input="(e) => setLocalValue((e.target as HTMLInputElement).value)"
      @blur="handleBlur"
      @keydown="handleKeyDown"
      class="editor-input"
      autofocus
    />
  </div>
</template>

<style scoped lang="scss">
.editor-wrapper,
.select-wrapper {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  padding: 6px 10px;
  box-sizing: border-box;
  overflow: hidden;
  min-width: 0;
}

.editor-input,
.select-editor {
  width: 100%;
  padding: 0;
  border: none;
  background: transparent;
  color: inherit;
  font: inherit;
  font-size: 13px;
  outline: none;
  min-width: 0;
}

.select-editor {
  cursor: pointer;
}

.rich-select-wrapper {
  width: 100%;
  height: 100%;
  display: flex;
  align-items: center;
  padding: 6px 10px;
  box-sizing: border-box;
  overflow: hidden;
  min-width: 0;
  position: relative;
}

.rich-select-input {
  width: 100%;
  padding: 0;
  border: none;
  background: transparent;
  color: inherit;
  font: inherit;
  font-size: 13px;
  outline: none;
  min-width: 0;
}

.rich-select-dropdown {
  position: absolute;
  top: 100%;
  left: 0;
  right: 0;
  max-height: 200px;
  overflow-y: auto;
  background: var(--ogrid-bg, #fff);
  border: 1px solid var(--ogrid-border, #ccc);
  z-index: 10;
  box-shadow: 0 4px 16px rgba(0, 0, 0, 0.2);
}

.rich-select-option {
  padding: 6px 8px;
  cursor: pointer;
  color: var(--ogrid-fg, #242424);

  &.highlighted {
    background: var(--ogrid-bg-hover, #e8f0fe);
  }
}

.rich-select-no-matches {
  padding: 6px 8px;
  color: var(--ogrid-muted, #999);
}

.checkbox-editor-wrapper {
  display: flex;
  align-items: center;
  justify-content: center;
  width: 100%;
  height: 100%;
}

.checkbox-editor {
  width: 18px;
  height: 18px;
  cursor: pointer;
  accent-color: var(--ogrid-primary, #0078d4);
}
</style>
