// packages/vue-radix/src/DataGridTable/DataGridTable.vue
<script setup lang="ts">
import { computed, defineComponent, h, Teleport } from 'vue';
import {
  useDataGridTableSetup,
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  getCellInteractionProps,
  buildHeaderRows,
  CHECKBOX_COLUMN_WIDTH,
  ROW_NUMBER_COLUMN_WIDTH,
  DEFAULT_MIN_COLUMN_WIDTH,
  type IOGridDataGridProps,
  type IColumnDef,
  type ICellEditorProps,
} from '@alaarab/ogrid-vue';
import ColumnHeaderFilter from '../ColumnHeaderFilter/ColumnHeaderFilter.vue';
import ColumnHeaderMenu from '../ColumnHeaderMenu/ColumnHeaderMenu.vue';
import InlineCellEditor from './InlineCellEditor.vue';
import { StatusBar, MarchingAntsOverlay } from '@alaarab/ogrid-vue';
import GridContextMenu from './GridContextMenu.vue';

const props = defineProps<{
  gridProps: IOGridDataGridProps<any>;
}>();

const propsRef = computed(() => props.gridProps);

const {
  wrapperRef,
  tableContainerRef,
  tableRef,
  lastMouseShift,
  state,
  columnReorder: { isDragging: isReorderDragging, dropIndicatorX, handleHeaderMouseDown: handleReorderMouseDown },
  virtualScroll: { containerRef: vsContainerRef, visibleRange, totalHeight, scrollToRow },
  virtualScrollEnabled,
  columnResize: { handleResizeStart, getColumnWidth },
} = useDataGridTableSetup({ props: propsRef });

// Wrap refs in plain object to prevent Vue template auto-unwrapping
// (MarchingAntsOverlay expects Ref<HTMLElement | null>, not the raw element)
const _refs = { tableContainer: tableContainerRef };

// Computed state refs
const layout = computed(() => state.layout.value);
const rowSel = computed(() => state.rowSelection.value);
const editing = computed(() => state.editing.value);
const interaction = computed(() => state.interaction.value);
const ctxMenu = computed(() => state.contextMenu.value);
const viewModels = computed(() => state.viewModels.value);
const pinning = computed(() => state.pinning.value);
const headerMenu = computed(() => pinning.value.headerMenu);

const headerRows = computed(() => buildHeaderRows(props.gridProps.columns, props.gridProps.visibleColumns));

// Computed items for virtual scrolling support
const visibleItems = computed(() => {
  const items = props.gridProps.items;
  if (!virtualScrollEnabled.value) return items.map((item, i) => ({ item, rowIndex: i }));
  const vr = visibleRange.value;
  const result: { item: any; rowIndex: number }[] = [];
  for (let i = vr.startIndex; i <= Math.min(vr.endIndex, items.length - 1); i++) {
    if (items[i]) result.push({ item: items[i], rowIndex: i });
  }
  return result;
});

// Pagination-aware row number offset
const rowNumberOffset = computed(() => {
  if (!layout.value.hasRowNumbersCol) return 0;
  const currentPage = props.gridProps.currentPage ?? 1;
  const pageSize = props.gridProps.pageSize ?? 25;
  return (currentPage - 1) * pageSize;
});

// Layout overflow handling
const fitToContent = computed(() => (props.gridProps.layoutMode ?? 'fill') === 'content');
const allowOverflowX = computed(() => {
  const l = layout.value;
  return !props.gridProps.suppressHorizontalScroll
    && l.containerWidth > 0
    && (l.minTableWidth > l.containerWidth || l.desiredTableWidth > l.containerWidth);
});

// Read pre-computed pinning offsets
const pinningOffsets = computed(() => ({
  leftOffsets: pinning.value.leftOffsets,
  rightOffsets: pinning.value.rightOffsets,
}));

const handleSingleRowClick = (e: MouseEvent, rowId: string | number) => {
  if (props.gridProps.rowSelection !== 'single') return;
  const sel = rowSel.value.selectedRowIds;
  rowSel.value.updateSelection(sel.has(rowId) ? new Set() : new Set([rowId]));
};

const handleRowCheckboxChange = (rowId: string | number, checked: boolean, rowIndex: number) => {
  rowSel.value.handleRowCheckboxChange(rowId, checked, rowIndex, lastMouseShift.value);
};

const isRowSelected = (rowId: string | number) => {
  return rowSel.value.selectedRowIds.has(rowId);
};

const handleKeyDown = (e: KeyboardEvent) => {
  interaction.value.handleGridKeyDown(e);
};

const NOOP = () => {};

// Cell render helpers
const getCellRenderData = (item: any, col: IColumnDef<any>, rowIndex: number, colIndex: number) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  const editCallbacks = {
    commitCellEdit: editing.value.commitCellEdit,
    setEditingCell: editing.value.setEditingCell,
    setPendingEditorValue: editing.value.setPendingEditorValue,
    cancelPopoverEdit: editing.value.cancelPopoverEdit,
  };

  if (descriptor.mode === 'editing-inline') {
    const editorProps = buildInlineEditorProps(item, col, descriptor, editCallbacks);
    return { type: 'editor' as const, props: editorProps, descriptor };
  }

  if (descriptor.mode === 'editing-popover' && typeof col.cellEditor === 'function') {
    const editorProps = buildPopoverEditorProps(item, col, descriptor, editing.value.pendingEditorValue, editCallbacks);
    return { type: 'popover-editor' as const, props: editorProps, col, descriptor };
  }

  return { type: 'content' as const, props: null, descriptor };
};

const getCellDisplayValue = (item: any, col: IColumnDef<any>, rowIndex: number, colIndex: number) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  return resolveCellDisplayContent(col, item, descriptor.displayValue);
};

const getCellClass = (rowIndex: number, colIndex: number, col: IColumnDef<any>, item: any) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  const classes = ['ogrid-cell'];

  if (descriptor.isActive && !descriptor.isInRange) {
    classes.push('ogrid-active-cell');
  }

  if (descriptor.isInRange) {
    classes.push('ogrid-selected-cell');
  }

  return classes.join(' ');
};

const getCellStyle = (item: any, col: IColumnDef<any>, rowIndex: number, colIndex: number) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  const columnWidth = getColumnWidth(col);
  const style: Record<string, string> = {
    position: 'relative',
    padding: '0',
    minWidth: `${col.minWidth ?? DEFAULT_MIN_COLUMN_WIDTH}px`,
    width: `${columnWidth}px`,
    maxWidth: `${columnWidth}px`,
  };

  // Column pinning
  const freezeCols = props.gridProps.freezeCols;
  const visibleCols = layout.value.visibleCols;
  const visibleColIndex = visibleCols.indexOf(col);
  const isFreezeCol = freezeCols != null && freezeCols >= 1 && visibleColIndex < freezeCols;
  const isPinnedLeft = col.pinned === 'left';
  const isPinnedRight = col.pinned === 'right';

  if (isPinnedLeft || (isFreezeCol && visibleColIndex === 0)) {
    const offsets = pinningOffsets.value;
    style.position = 'sticky';
    style.left = `${offsets.leftOffsets[col.columnId] ?? 0}px`;
    style.zIndex = '6';
    style.backgroundColor = 'var(--ogrid-bg, #fff)';
    style.willChange = 'transform';
  } else if (isPinnedRight) {
    const offsets = pinningOffsets.value;
    style.position = 'sticky';
    style.right = `${offsets.rightOffsets[col.columnId] ?? 0}px`;
    style.zIndex = '6';
    style.backgroundColor = 'var(--ogrid-bg, #fff)';
    style.willChange = 'transform';
  }

  if (descriptor.canEditAny) {
    style.cursor = 'cell';
  }

  if (descriptor.isInCutRange) {
    style.backgroundColor = 'rgba(0,0,0,0.04)';
    style.opacity = '0.7';
  }

  return style;
};

// Header cell style (with pinning support)
const getHeaderCellStyle = (col: IColumnDef<any>, colIndex: number) => {
  const columnWidth = getColumnWidth(col);
  const freezeCols = props.gridProps.freezeCols;
  const isFreezeCol = freezeCols != null && freezeCols >= 1 && colIndex < freezeCols;
  const isPinnedLeft = col.pinned === 'left';
  const isPinnedRight = col.pinned === 'right';

  const style: Record<string, string> = {
    width: `${columnWidth}px`,
    minWidth: `${(col.minWidth ?? DEFAULT_MIN_COLUMN_WIDTH)}px`,
    maxWidth: `${columnWidth}px`,
  };

  if (isPinnedLeft || (isFreezeCol && colIndex === 0)) {
    const offsets = pinningOffsets.value;
    style.position = 'sticky';
    style.top = '0';
    style.left = `${offsets.leftOffsets[col.columnId] ?? 0}px`;
    style.zIndex = '10';
    style.backgroundColor = 'var(--ogrid-header-bg, #f5f5f5)';
    style.willChange = 'transform';
  } else if (isPinnedRight) {
    const offsets = pinningOffsets.value;
    style.position = 'sticky';
    style.top = '0';
    style.right = `${offsets.rightOffsets[col.columnId] ?? 0}px`;
    style.zIndex = '10';
    style.backgroundColor = 'var(--ogrid-header-bg, #f5f5f5)';
    style.willChange = 'transform';
  }

  return style;
};

// Cell content style (with numeric/boolean alignment)
const getCellContentStyle = (col: IColumnDef<any>, item: any, rowIndex: number, colIndex: number) => {
  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  const style: Record<string, string> = {
    padding: '8px 12px',
    overflow: 'hidden',
    textOverflow: 'ellipsis',
    whiteSpace: 'nowrap',
    position: 'relative',
  };

  if (col.type === 'numeric') {
    style.textAlign = 'right';
  } else if (col.type === 'boolean') {
    style.textAlign = 'center';
  }

  // Apply custom cell styles
  const customStyle = resolveCellStyle(col, item);
  if (customStyle) {
    Object.assign(style, customStyle);
  }

  return style;
};

const shouldShowFillHandle = (item: any, col: IColumnDef<any>, rowIndex: number, colIndex: number) => {
  const range = interaction.value.selectionRange;
  if (!range) return false;

  const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIndex, viewModels.value.cellDescriptorInput);
  return descriptor.canEditAny && descriptor.isSelectionEndCell;
};

const getFilterProps = (col: IColumnDef<any>) => {
  return getHeaderFilterConfig(col, viewModels.value.headerFilterInput);
};

// Popover anchor ref
const setPopoverAnchorEl = (el: HTMLElement) => {
  editing.value.setPopoverAnchorEl(el);
};

// Bind wrapperRef to element via ref callback
const setWrapperRef = (el: any) => {
  wrapperRef.value = el as HTMLDivElement;
  vsContainerRef.value = el as HTMLElement;
};
</script>

<template>
  <div class="ogrid-wrapper">
    <!-- Main Grid -->
    <div
      :ref="setWrapperRef"
      class="ogrid-table-container"
      :style="{
        overflowX: gridProps.suppressHorizontalScroll ? 'hidden' : allowOverflowX ? 'auto' : 'hidden',
        overflowY: 'auto',
        opacity: gridProps.isLoading && gridProps.items.length > 0 ? '0.6' : '1',
      }"
      tabindex="0"
      role="region"
      :aria-label="gridProps['aria-label'] ?? (!gridProps['aria-labelledby'] ? 'Data grid' : undefined)"
      :aria-labelledby="gridProps['aria-labelledby']"
      @keydown="handleKeyDown"
      @mousedown="(e) => { lastMouseShift = e.shiftKey; }"
      @contextmenu.prevent
    >
      <!-- Drop Indicator for Column Reorder -->
      <div
        v-if="isReorderDragging && dropIndicatorX !== null"
        class="ogrid-drop-indicator"
        :style="{ left: `${dropIndicatorX}px` }"
      ></div>

      <div :ref="(el) => { tableContainerRef = el as HTMLDivElement; }" style="position: relative">
        <table
          :ref="(el) => { tableRef = el as HTMLElement; }"
          class="ogrid-table"
          :style="{
            width: fitToContent ? 'auto' : '100%',
            minWidth: allowOverflowX ? `${layout.minTableWidth}px` : undefined,
          }"
          :data-freeze-rows="gridProps.freezeRows != null && gridProps.freezeRows >= 1 ? gridProps.freezeRows : undefined"
          :data-freeze-cols="gridProps.freezeCols != null && gridProps.freezeCols >= 1 ? gridProps.freezeCols : undefined"
        >
          <!-- Header -->
          <thead>
            <tr
              v-for="(row, rowIdx) in headerRows"
              :key="rowIdx"
              class="ogrid-header-row"
            >
              <!-- Checkbox Header -->
              <th
                v-if="layout.hasCheckboxCol && rowIdx === 0"
                :rowspan="headerRows.length"
                class="ogrid-header-cell ogrid-selection-header"
                :style="{ width: `${CHECKBOX_COLUMN_WIDTH}px` }"
              >
                <input
                  v-if="gridProps.rowSelection === 'multiple'"
                  type="checkbox"
                  :checked="rowSel.allSelected"
                  @change="rowSel.handleSelectAll"
                  aria-label="Select all rows"
                  class="ogrid-checkbox"
                />
              </th>

              <!-- Row Numbers Header -->
              <th
                v-if="layout.hasRowNumbersCol && rowIdx === headerRows.length - 1"
                class="ogrid-header-cell ogrid-row-number-header"
                :style="{ width: `${ROW_NUMBER_COLUMN_WIDTH}px`, textAlign: 'center' }"
              >
                #
              </th>

              <!-- Header Cells -->
              <th
                v-for="cell in row"
                :key="cell.columnDef?.columnId || `group-${rowIdx}`"
                :colspan="cell.colSpan"
                :rowspan="!cell.isGroup ? headerRows.length - cell.depth : undefined"
                :class="['ogrid-header-cell', { 'ogrid-group-header': cell.isGroup }]"
                :style="cell.columnDef && !cell.isGroup
                  ? getHeaderCellStyle(cell.columnDef, layout.visibleCols.indexOf(cell.columnDef))
                  : undefined"
                :data-column-id="cell.columnDef?.columnId"
                :aria-sort="cell.columnDef && !cell.isGroup && gridProps.sort?.field === cell.columnDef.columnId
                  ? (gridProps.sort.direction === 'asc' ? 'ascending' : 'descending')
                  : undefined"
                @mousedown="cell.columnDef && !cell.isGroup ? (e) => handleReorderMouseDown(cell.columnDef.columnId, e) : undefined"
              >
                <div class="ogrid-header-content">
                  <ColumnHeaderFilter
                    v-if="cell.columnDef && !cell.isGroup"
                    v-bind="getFilterProps(cell.columnDef)"
                  />
                  <span v-else class="ogrid-header-label">
                    {{ cell.label }}
                  </span>
                  <button
                    v-if="cell.columnDef && !cell.isGroup"
                    class="ogrid-header-menu-btn"
                    aria-label="Column options"
                    title="Column options"
                    @click.stop="(e: MouseEvent) => headerMenu.open(cell.columnDef.columnId, e.currentTarget as HTMLElement)"
                  >&#8942;</button>
                </div>

                <!-- Resize Handle -->
                <div
                  v-if="cell.columnDef && cell.columnDef.resizable !== false"
                  class="ogrid-resize-handle"
                  @mousedown.stop="(e) => handleResizeStart(e, cell.columnDef!)"
                ></div>
              </th>
            </tr>
          </thead>

          <!-- Body with virtual scrolling support -->
          <tbody v-if="!viewModels.showEmptyInGrid">
            <!-- Top spacer for virtual scrolling -->
            <tr
              v-if="virtualScrollEnabled && visibleRange.offsetTop > 0"
              :style="{ height: `${visibleRange.offsetTop}px` }"
              aria-hidden="true"
            />

            <tr
              v-for="{ item, rowIndex } in visibleItems"
              :key="gridProps.getRowId(item)"
              :data-row-id="gridProps.getRowId(item)"
              :class="{
                'ogrid-row': true,
                'ogrid-selected-row': isRowSelected(gridProps.getRowId(item)),
              }"
              :style="{ cursor: gridProps.rowSelection === 'single' ? 'pointer' : undefined }"
              @click="(e) => handleSingleRowClick(e, gridProps.getRowId(item))"
            >
              <!-- Checkbox Cell -->
              <td
                v-if="layout.hasCheckboxCol"
                class="ogrid-cell ogrid-selection-cell"
                @click.stop
              >
                <input
                  type="checkbox"
                  :checked="isRowSelected(gridProps.getRowId(item))"
                  @change="(e) => handleRowCheckboxChange(gridProps.getRowId(item), (e.target as HTMLInputElement).checked, rowIndex)"
                  :aria-label="`Select row ${rowIndex + 1}`"
                  class="ogrid-checkbox"
                />
              </td>

              <!-- Row Number Cell -->
              <td
                v-if="layout.hasRowNumbersCol"
                class="ogrid-cell ogrid-row-number-cell"
              >
                {{ rowNumberOffset + rowIndex + 1 }}
              </td>

              <!-- Data Cells -->
              <td
                v-for="(col, colIndex) in layout.visibleCols"
                :key="col.columnId"
                :data-column-id="col.columnId"
                :data-row-index="rowIndex"
                :data-col-index="layout.colOffset + colIndex"
                :class="getCellClass(rowIndex, layout.colOffset + colIndex, col, item)"
                :style="getCellStyle(item, col, rowIndex, layout.colOffset + colIndex)"
                @mousedown="(e) => interaction.handleCellMouseDown(e, rowIndex, layout.colOffset + colIndex)"
                @contextmenu="(e) => ctxMenu.handleCellContextMenu(e)"
              >
                <div :style="getCellContentStyle(col, item, rowIndex, layout.colOffset + colIndex)">
                  <!-- Inline Editor -->
                  <component
                    v-if="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).type === 'editor'"
                    :is="InlineCellEditor"
                    v-bind="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).props"
                  />
                  <!-- Popover Editor -->
                  <template v-else-if="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).type === 'popover-editor'">
                    <div
                      :ref="(el) => { if (el) setPopoverAnchorEl(el as HTMLElement); }"
                      style="min-height: 100%; min-width: 40px"
                      aria-hidden="true"
                    ></div>
                    <component
                      v-if="editing.popoverAnchorEl"
                      :is="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).col.cellEditor"
                      v-bind="getCellRenderData(item, col, rowIndex, layout.colOffset + colIndex).props"
                    />
                  </template>
                  <!-- Display Content -->
                  <template v-else>
                    {{ getCellDisplayValue(item, col, rowIndex, layout.colOffset + colIndex) }}

                    <!-- Fill Handle (on selection end cell) -->
                    <div
                      v-if="shouldShowFillHandle(item, col, rowIndex, layout.colOffset + colIndex)"
                      class="ogrid-fill-handle"
                      @mousedown="interaction.handleFillHandleMouseDown"
                      aria-label="Fill handle"
                    ></div>
                  </template>
                </div>
              </td>
            </tr>

            <!-- Bottom spacer for virtual scrolling -->
            <tr
              v-if="virtualScrollEnabled && visibleRange.offsetBottom > 0"
              :style="{ height: `${visibleRange.offsetBottom}px` }"
              aria-hidden="true"
            />
          </tbody>
        </table>

        <!-- Empty State -->
        <div v-if="viewModels.showEmptyInGrid && gridProps.emptyState" class="ogrid-empty-state">
          <component
            v-if="gridProps.emptyState.render"
            :is="{ render: gridProps.emptyState.render }"
          />
          <div v-else>
            <div class="ogrid-empty-title">No results found</div>
            <div class="ogrid-empty-message">
              <template v-if="gridProps.emptyState.message">
                {{ gridProps.emptyState.message }}
              </template>
              <template v-else-if="gridProps.emptyState.hasActiveFilters">
                No items match your current filters. Try adjusting your search or
                <button
                  class="ogrid-empty-clear-btn"
                  @click="gridProps.emptyState.onClearAll"
                >
                  clear all filters
                </button>
                to see all items.
              </template>
              <template v-else>
                No data available
              </template>
            </div>
          </div>
        </div>

        <!-- Marching Ants Overlay -->
        <MarchingAntsOverlay
          :containerRef="_refs.tableContainer"
          :selectionRange="interaction.selectionRange"
          :copyRange="interaction.copyRange"
          :cutRange="interaction.cutRange"
          :colOffset="layout.colOffset"
          :items="gridProps.items"
          :visibleColumns="gridProps.visibleColumns instanceof Set ? Array.from(gridProps.visibleColumns) : gridProps.visibleColumns"
          :columnSizingOverrides="layout.columnSizingOverrides"
          :columnOrder="gridProps.columnOrder"
        />
      </div>
    </div>

    <!-- Loading Overlay -->
    <div
      v-if="gridProps.isLoading"
      class="ogrid-loading-overlay"
    >
      <div class="ogrid-loading-content">
        <div class="loading-spinner"></div>
        <span>{{ gridProps.loadingMessage || 'Loading...' }}</span>
      </div>
    </div>

    <!-- Context Menu (Teleported to body) -->
    <Teleport to="body" v-if="ctxMenu.menuPosition">
      <GridContextMenu
        :x="ctxMenu.menuPosition.x"
        :y="ctxMenu.menuPosition.y"
        :hasSelection="!!interaction.selectionRange"
        :canUndo="interaction.canUndo"
        :canRedo="interaction.canRedo"
        :onUndo="interaction.onUndo || NOOP"
        :onRedo="interaction.onRedo || NOOP"
        :onCopy="interaction.handleCopy"
        :onCut="interaction.handleCut"
        :onPaste="() => interaction.handlePaste()"
        :onSelectAll="interaction.handleSelectAllCells"
        :onClose="ctxMenu.closeContextMenu"
      />
    </Teleport>

    <!-- Column Header Menu -->
    <ColumnHeaderMenu
      :isOpen="headerMenu.isOpen"
      :anchorElement="headerMenu.anchorElement"
      :onClose="headerMenu.close"
      :onPinLeft="headerMenu.handlePinLeft"
      :onPinRight="headerMenu.handlePinRight"
      :onUnpin="headerMenu.handleUnpin"
      :onSortAsc="headerMenu.handleSortAsc"
      :onSortDesc="headerMenu.handleSortDesc"
      :onClearSort="headerMenu.handleClearSort"
      :onAutosizeThis="headerMenu.handleAutosizeThis"
      :onAutosizeAll="headerMenu.handleAutosizeAll"
      :canPinLeft="headerMenu.canPinLeft"
      :canPinRight="headerMenu.canPinRight"
      :canUnpin="headerMenu.canUnpin"
      :currentSort="headerMenu.currentSort"
      :isSortable="headerMenu.isSortable"
      :isResizable="headerMenu.isResizable"
    />

    <!-- Status Bar -->
    <StatusBar
      v-if="viewModels.statusBarConfig"
      :totalCount="viewModels.statusBarConfig.totalCount"
      :filteredCount="viewModels.statusBarConfig.filteredCount"
      :selectedCount="viewModels.statusBarConfig.selectedCount ?? rowSel.selectedRowIds.size"
      :selectedCellCount="interaction.selectionRange
        ? (Math.abs(interaction.selectionRange.endRow - interaction.selectionRange.startRow) + 1) *
          (Math.abs(interaction.selectionRange.endCol - interaction.selectionRange.startCol) + 1)
        : undefined"
      :aggregation="viewModels.statusBarConfig.aggregation"
      :suppressRowCount="viewModels.statusBarConfig.suppressRowCount"
    />
  </div>
</template>

<style scoped lang="scss">
@import './DataGridTable.module.scss';

.ogrid-wrapper {
  position: relative;
  flex: 1;
  min-height: 0;
  display: flex;
  flex-direction: column;
}

.ogrid-table-container {
  flex: 1;
  position: relative;
  outline: none;
  background-color: var(--ogrid-bg, #fff);
  will-change: scroll-position;
}

/* Drag-range highlight applied via DOM attributes during drag (bypasses Vue for performance) */
:deep([data-drag-range]) {
  background: var(--ogrid-range-bg, rgba(33, 115, 70, 0.12)) !important;
}

.ogrid-drop-indicator {
  position: absolute;
  top: 0;
  bottom: 0;
  width: 3px;
  background: var(--ogrid-primary, #217346);
  pointer-events: none;
  z-index: 100;
}

.ogrid-table {
  border-collapse: collapse;
  font-size: 14px;
  background: var(--ogrid-bg, #fff);
}

.ogrid-header-row {
  z-index: 8;
  background: var(--ogrid-header-bg, #f5f5f5);
}

.ogrid-header-cell {
  position: sticky;
  top: 0;
  background: var(--ogrid-header-bg, #f5f5f5);
  border-bottom: 1px solid var(--ogrid-border, #e0e0e0);
  border-right: 1px solid var(--ogrid-border, #e0e0e0);
  padding: 8px 12px;
  z-index: 8;
  text-align: left;
  font-weight: 600;
  user-select: none;
  cursor: grab;

  &:last-child {
    border-right: none;
  }

  &:active {
    cursor: grabbing;
  }

  &:focus-visible {
    outline: 2px solid var(--ogrid-accent, #0078d4);
    outline-offset: -2px;
    z-index: 11;
  }
}

.ogrid-group-header {
  text-align: center;
  border-bottom: 2px solid var(--ogrid-border, #e0e0e0);
  cursor: default;

  &:active {
    cursor: default;
  }
}

.ogrid-header-content {
  display: flex;
  align-items: center;
  gap: 4px;
  width: 100%;
}

.ogrid-header-label {
  flex: 1;
  min-width: 0;
  overflow: hidden;
  text-overflow: ellipsis;
  white-space: nowrap;
}

.ogrid-header-menu-btn {
  background: none;
  border: none;
  cursor: pointer;
  padding: 4px 6px;
  font-size: 16px;
  color: var(--ogrid-fg-muted, rgba(0, 0, 0, 0.5));
  line-height: 1;
  flex-shrink: 0;
  border-radius: 4px;
  display: inline-flex;
  align-items: center;
  justify-content: center;
  min-width: 24px;
  height: 24px;
  transition: background-color 0.15s;

  &:hover {
    background: var(--ogrid-hover-bg, rgba(0, 0, 0, 0.04));
    color: var(--ogrid-fg, rgba(0, 0, 0, 0.8));
  }

  &:focus-visible {
    outline: 2px solid var(--ogrid-accent, #0078d4);
    outline-offset: 2px;
  }
}

.ogrid-resize-handle {
  position: absolute;
  right: -3px;
  top: 0;
  bottom: 0;
  width: 8px;
  cursor: col-resize;
  z-index: 10;
  user-select: none;
}

.ogrid-row {
  &:hover {
    background: var(--ogrid-hover-bg, #f9f9f9);
  }
}

.ogrid-selected-row {
  background: var(--ogrid-selected-bg, #e3f2fd);
}

.ogrid-cell {
  padding: 0;
  border-bottom: 1px solid var(--ogrid-border, #e0e0e0);
  border-right: 1px solid var(--ogrid-border, #e0e0e0);
  position: relative;
  height: 1px;

  &:last-child {
    border-right: none;
  }

  &:focus-visible {
    outline: 2px solid var(--ogrid-accent, #0078d4);
    outline-offset: -2px;
    z-index: 3;
  }
}

.ogrid-active-cell {
  outline: 2px solid var(--ogrid-active-border, #0078d4);
  outline-offset: -2px;
  z-index: 1;
}

.ogrid-selected-cell {
  background: var(--ogrid-bg-range, rgba(33, 115, 70, 0.12));
}

.ogrid-fill-handle {
  position: absolute;
  right: -3px;
  bottom: -3px;
  width: 7px;
  height: 7px;
  background-color: var(--ogrid-selection, #217346);
  border: 1px solid var(--ogrid-bg, #fff);
  border-radius: 1px;
  cursor: crosshair;
  pointer-events: auto;
  z-index: 3;
}

.ogrid-selection-header,
.ogrid-selection-cell {
  width: 40px;
  text-align: center;
  padding: 8px;
}

.ogrid-row-number-header,
.ogrid-row-number-cell {
  width: 40px;
  text-align: center;
  padding: 6px;
  font-weight: 600;
  font-variant-numeric: tabular-nums;
  color: var(--ogrid-muted, #888);
  background: var(--ogrid-header-bg, #f5f5f5);
}

.ogrid-checkbox {
  cursor: pointer;
  width: 16px;
  height: 16px;
}

.ogrid-empty-state {
  padding: 32px 16px;
  text-align: center;
  border-top: 1px solid var(--ogrid-border, #e0e0e0);
  background: var(--ogrid-statusbar-bg, #f5f5f5);
}

.ogrid-empty-title {
  font-size: 1.25rem;
  font-weight: 600;
  margin-bottom: 8px;
}

.ogrid-empty-message {
  font-size: 0.875rem;
  color: var(--ogrid-muted, #888);
}

.ogrid-empty-clear-btn {
  background: none;
  border: none;
  color: var(--ogrid-primary, #0066cc);
  text-decoration: underline;
  cursor: pointer;
  padding: 0;
  font: inherit;

  &:hover {
    color: var(--ogrid-primary-hover, #005a9e);
  }
}

.ogrid-loading-overlay {
  position: absolute;
  inset: 0;
  z-index: 2;
  display: flex;
  align-items: center;
  justify-content: center;
  background-color: rgba(255, 255, 255, 0.7);
}

.ogrid-loading-content {
  display: flex;
  flex-direction: column;
  align-items: center;
  gap: 8px;
  padding: 16px;
  background-color: var(--ogrid-bg, #fff);
  border: 1px solid var(--ogrid-border, #e0e0e0);
  border-radius: 4px;
  font-size: 0.875rem;
  color: var(--ogrid-muted, #888);
}

.loading-spinner {
  width: 24px;
  height: 24px;
  border: 3px solid var(--ogrid-border, #e0e0e0);
  border-top-color: var(--ogrid-primary, #0066cc);
  border-radius: 50%;
  animation: spin 0.8s linear infinite;
}

@keyframes spin {
  to { transform: rotate(360deg); }
}
</style>

// packages/react-material/src/DataGridTable/DataGridTable.tsx
import * as React from 'react';
import { useCallback, useRef, useMemo } from 'react';
import { createPortal } from 'react-dom';
import {
  Box,
  CircularProgress,
  Typography,
  Button,
  Popover,
  Checkbox,
  Table,
  TableHead,
  TableBody,
  TableRow,
  TableCell,
  TableContainer,
} from '@mui/material';
import { ColumnHeaderFilter } from '../ColumnHeaderFilter';
import { InlineCellEditor } from './InlineCellEditor';
import { StatusBar } from './StatusBar';
import { GridContextMenu } from './GridContextMenu';
import type {
  IColumnDef,
  ICellEditorProps,
  IOGridDataGridProps,
} from '@alaarab/ogrid-react';
import {
  useDataGridState,
  useColumnResize,
  useLatestRef,
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  MarchingAntsOverlay,
  buildHeaderRows,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  getCellInteractionProps,
  areGridRowPropsEqual,
  CellErrorBoundary,
  CHECKBOX_COLUMN_WIDTH,
  DEFAULT_MIN_COLUMN_WIDTH,
} from '@alaarab/ogrid-react';


// ── Module-scope stable styles (avoid per-render Emotion resolutions) ──

const gridRootSx = { position: 'relative', flex: 1, minHeight: 0, display: 'flex', flexDirection: 'column' } as const;

// Row
const ROW_HOVER_SX = { '&:hover': { bgcolor: 'action.hover' } } as const;

// Checkbox column
const CHECKBOX_CELL_SX = { width: CHECKBOX_COLUMN_WIDTH, minWidth: CHECKBOX_COLUMN_WIDTH, maxWidth: CHECKBOX_COLUMN_WIDTH, textAlign: 'center' } as const;
const CHECKBOX_WRAPPER_SX = { display: 'flex', alignItems: 'center', justifyContent: 'center' } as const;
const CHECKBOX_PLACEHOLDER_SX = { width: CHECKBOX_COLUMN_WIDTH, minWidth: CHECKBOX_COLUMN_WIDTH, p: 0 } as const;

// Header
const STICKY_HEADER_SX = { position: 'sticky', top: 0, zIndex: 8, bgcolor: 'action.hover', '& th': { bgcolor: 'action.hover' } } as const;
const HEADER_ROW_SX = { bgcolor: 'action.hover' } as const;
const GROUP_HEADER_CELL_SX = { textAlign: 'center', fontWeight: 600, borderBottom: 2, borderColor: 'divider', py: 0.75 } as const;

// Cell content base variants (selected by column type + editability)
const CELL_CONTENT_BASE_SX = {
  width: '100%', height: '100%', display: 'flex', alignItems: 'center', minWidth: 0,
  px: '10px', py: '6px', boxSizing: 'border-box', overflow: 'hidden',
  textOverflow: 'ellipsis', whiteSpace: 'nowrap', userSelect: 'none', outline: 'none',
} as const;
const CELL_CONTENT_NUMERIC_SX = { ...CELL_CONTENT_BASE_SX, justifyContent: 'flex-end', textAlign: 'right' as const } as const;
const CELL_CONTENT_BOOLEAN_SX = { ...CELL_CONTENT_BASE_SX, justifyContent: 'center', textAlign: 'center' as const } as const;
const CELL_CONTENT_EDITABLE_SX = { ...CELL_CONTENT_BASE_SX, cursor: 'cell' } as const;
const CELL_CONTENT_NUMERIC_EDITABLE_SX = { ...CELL_CONTENT_NUMERIC_SX, cursor: 'cell' } as const;
const CELL_CONTENT_BOOLEAN_EDITABLE_SX = { ...CELL_CONTENT_BOOLEAN_SX, cursor: 'cell' } as const;

// Cell overlay states (only applied to the few active/selected cells)
const CELL_ACTIVE_SX = { outline: '2px solid var(--ogrid-selection, #217346)', outlineOffset: '-1px', zIndex: 2, position: 'relative' as const, overflow: 'visible' } as const;
const CELL_IN_RANGE_SX = { bgcolor: 'var(--ogrid-bg-range, rgba(33, 115, 70, 0.12))' } as const;
const CELL_CUT_RANGE_SX = { bgcolor: 'action.hover', opacity: 0.7 } as const;

// Pre-computed overlay variant arrays (avoid per-cell array allocation + filter)
// Key: `${base}_${overlay}` where overlay is 'active' | 'range' | 'cut'
const OVERLAY_VARIANTS = {
  base_active: [CELL_CONTENT_BASE_SX, CELL_ACTIVE_SX],
  base_range: [CELL_CONTENT_BASE_SX, CELL_IN_RANGE_SX],
  base_cut: [CELL_CONTENT_BASE_SX, CELL_IN_RANGE_SX, CELL_CUT_RANGE_SX],
  editable_active: [CELL_CONTENT_EDITABLE_SX, CELL_ACTIVE_SX],
  editable_range: [CELL_CONTENT_EDITABLE_SX, CELL_IN_RANGE_SX],
  editable_cut: [CELL_CONTENT_EDITABLE_SX, CELL_IN_RANGE_SX, CELL_CUT_RANGE_SX],
  numeric_active: [CELL_CONTENT_NUMERIC_SX, CELL_ACTIVE_SX],
  numeric_range: [CELL_CONTENT_NUMERIC_SX, CELL_IN_RANGE_SX],
  numeric_cut: [CELL_CONTENT_NUMERIC_SX, CELL_IN_RANGE_SX, CELL_CUT_RANGE_SX],
  numeric_editable_active: [CELL_CONTENT_NUMERIC_EDITABLE_SX, CELL_ACTIVE_SX],
  numeric_editable_range: [CELL_CONTENT_NUMERIC_EDITABLE_SX, CELL_IN_RANGE_SX],
  numeric_editable_cut: [CELL_CONTENT_NUMERIC_EDITABLE_SX, CELL_IN_RANGE_SX, CELL_CUT_RANGE_SX],
  boolean_active: [CELL_CONTENT_BOOLEAN_SX, CELL_ACTIVE_SX],
  boolean_range: [CELL_CONTENT_BOOLEAN_SX, CELL_IN_RANGE_SX],
  boolean_cut: [CELL_CONTENT_BOOLEAN_SX, CELL_IN_RANGE_SX, CELL_CUT_RANGE_SX],
  boolean_editable_active: [CELL_CONTENT_BOOLEAN_EDITABLE_SX, CELL_ACTIVE_SX],
  boolean_editable_range: [CELL_CONTENT_BOOLEAN_EDITABLE_SX, CELL_IN_RANGE_SX],
  boolean_editable_cut: [CELL_CONTENT_BOOLEAN_EDITABLE_SX, CELL_IN_RANGE_SX, CELL_CUT_RANGE_SX],
} as const;

/** Select pre-computed sx for a cell based on column type, editability, and overlay state. */
function getCellSx(
  colType: string | undefined,
  canEdit: boolean,
  isActive: boolean,
  isInRange: boolean,
  isInCutRange: boolean,
): object | readonly object[] {
  // Determine base key
  let baseKey: string;
  if (colType === 'numeric') baseKey = canEdit ? 'numeric_editable' : 'numeric';
  else if (colType === 'boolean') baseKey = canEdit ? 'boolean_editable' : 'boolean';
  else baseKey = canEdit ? 'editable' : 'base';

  // Determine overlay
  if (isInCutRange) return OVERLAY_VARIANTS[`${baseKey}_cut` as keyof typeof OVERLAY_VARIANTS];
  if (isInRange) return OVERLAY_VARIANTS[`${baseKey}_range` as keyof typeof OVERLAY_VARIANTS];
  if (isActive) return OVERLAY_VARIANTS[`${baseKey}_active` as keyof typeof OVERLAY_VARIANTS];

  // No overlay — return the base sx directly
  if (colType === 'numeric') return canEdit ? CELL_CONTENT_NUMERIC_EDITABLE_SX : CELL_CONTENT_NUMERIC_SX;
  if (colType === 'boolean') return canEdit ? CELL_CONTENT_BOOLEAN_EDITABLE_SX : CELL_CONTENT_BOOLEAN_SX;
  return canEdit ? CELL_CONTENT_EDITABLE_SX : CELL_CONTENT_BASE_SX;
}

// Fill handle
const FILL_HANDLE_SX = {
  position: 'absolute', right: -3, bottom: -3, width: 7, height: 7,
  bgcolor: 'var(--ogrid-selection, #217346)', border: '1px solid var(--ogrid-bg, #fff)', borderRadius: '1px',
  cursor: 'crosshair', pointerEvents: 'auto', zIndex: 3,
} as const;

// Cell <td> positioning variants
const CELL_TD_BASE_SX = { position: 'relative' as const, p: 0, height: '1px' } as const;
const CELL_TD_PINNED_LEFT_SX = { ...CELL_TD_BASE_SX, position: 'sticky' as const, left: 0, zIndex: 6, bgcolor: 'background.paper', willChange: 'transform' } as const;
const CELL_TD_PINNED_RIGHT_SX = { ...CELL_TD_BASE_SX, position: 'sticky' as const, right: 0, zIndex: 6, bgcolor: 'background.paper', willChange: 'transform' } as const;

// Header cell positioning variants
const HEADER_BASE_SX = { fontWeight: 600, position: 'relative' as const } as const;
const HEADER_PINNED_LEFT_SX = { ...HEADER_BASE_SX, position: 'sticky' as const, left: 0, top: 0, zIndex: 9, bgcolor: 'action.hover', willChange: 'transform' } as const;
const HEADER_PINNED_RIGHT_SX = { ...HEADER_BASE_SX, position: 'sticky' as const, right: 0, top: 0, zIndex: 9, bgcolor: 'action.hover', willChange: 'transform' } as const;

// Resize handle
const RESIZE_HANDLE_SX = {
  position: 'absolute', top: 0, right: '-3px', bottom: 0, width: '8px',
  cursor: 'col-resize', userSelect: 'none',
  '&::after': { content: '""', position: 'absolute', top: 0, right: '3px', bottom: 0, width: '2px' },
  '&:hover::after': { bgcolor: 'primary.main' },
  '&:active::after': { bgcolor: 'primary.dark' },
} as const;

// Popover
const POPOVER_ANCHOR_SX = { minHeight: '100%', minWidth: 40 } as const;
const POPOVER_CONTENT_SX = { p: 1 } as const;

// Wrapper
const WRAPPER_SCROLL_SX = { display: 'flex', flexDirection: 'column', minHeight: '100%' } as const;

// Table wrapper
const TABLE_WRAPPER_SX = { position: 'relative', opacity: 1 } as const;
const TABLE_WRAPPER_LOADING_SX = { position: 'relative', opacity: 0.6 } as const;

// Empty state
const EMPTY_STATE_SX = { py: 4, px: 2, textAlign: 'center', borderTop: 1, borderColor: 'divider', bgcolor: 'action.hover' } as const;

// Loading overlay
const LOADING_OVERLAY_SX = {
  position: 'absolute', inset: 0, zIndex: 2,
  display: 'flex', alignItems: 'center', justifyContent: 'center',
  bgcolor: 'rgba(255,255,255,0.7)',
} as const;
const LOADING_INNER_SX = {
  display: 'flex', flexDirection: 'column', alignItems: 'center', gap: 1,
  p: 2, bgcolor: 'background.paper', border: 1, borderColor: 'divider', borderRadius: 1,
} as const;

// Module-scope event handlers
const STOP_PROPAGATION = (e: React.MouseEvent) => e.stopPropagation();
const PREVENT_DEFAULT = (e: React.MouseEvent) => { e.preventDefault(); };
const NOOP = () => {};

// --- Memoized row component (skips re-render for rows unaffected by selection changes) ---

/** Pre-computed per-column layout (avoids per-cell recalculation inside GridRow). */
interface ColumnLayout<T = unknown> {
  col: IColumnDef<T>;
  tdSx: object;
  minWidth: number;
  width: number;
  maxWidth: number;
}

interface GridRowProps {
  item: unknown;
  rowIndex: number;
  rowId: string | number;
  isSelected: boolean;
  columnLayouts: ColumnLayout<unknown>[];
  renderCellContent: (item: unknown, col: IColumnDef<unknown>, rowIndex: number, colIdx: number) => React.ReactNode;
  handleSingleRowClick: (e: React.MouseEvent<HTMLTableRowElement>) => void;
  handleRowCheckboxChange: (rowId: string | number, checked: boolean, rowIndex: number, shiftKey: boolean) => void;
  lastMouseShiftRef: React.MutableRefObject<boolean>;
  hasCheckboxCol: boolean;
  // Comparator-only props (drive re-render decisions, not used in render body)
  selectionRange: { startRow: number; endRow: number; startCol: number; endCol: number } | null;
  activeCell: { rowIndex: number; columnIndex: number } | null;
  cutRange: { startRow: number; endRow: number; startCol: number; endCol: number } | null;
  copyRange: { startRow: number; endRow: number; startCol: number; endCol: number } | null;
  isDragging: boolean;
  editingRowId: string | number | null;
}

function GridRowInner(props: GridRowProps) {
  const {
    item, rowIndex, rowId, isSelected, columnLayouts,
    renderCellContent, handleSingleRowClick, handleRowCheckboxChange,
    lastMouseShiftRef, hasCheckboxCol,
  } = props;

  return (
    <TableRow
      selected={isSelected}
      data-row-id={rowId}
      onClick={handleSingleRowClick}
      sx={ROW_HOVER_SX}
    >
      {hasCheckboxCol && (
        <TableCell padding="checkbox" sx={CHECKBOX_CELL_SX}>
          <Box
            data-row-index={rowIndex}
            data-col-index={0}
            onClick={STOP_PROPAGATION}
            sx={CHECKBOX_WRAPPER_SX}
          >
            <Checkbox
              checked={isSelected}
              onChange={(_, checked) => handleRowCheckboxChange(rowId, checked, rowIndex, lastMouseShiftRef.current)}
              size="small"
              aria-label={`Select row ${rowIndex + 1}`}
            />
          </Box>
        </TableCell>
      )}
      {columnLayouts.map((cl, colIdx) => (
        <TableCell
          key={cl.col.columnId}
          sx={cl.tdSx}
          style={{ minWidth: cl.minWidth, width: cl.width, maxWidth: cl.maxWidth }}
        >
          {renderCellContent(item, cl.col, rowIndex, colIdx)}
        </TableCell>
      ))}
    </TableRow>
  );
}

const GridRow = React.memo(GridRowInner, areGridRowPropsEqual);

function DataGridTableInner<T>(props: IOGridDataGridProps<T>): React.ReactElement {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const tableContainerRef = useRef<HTMLDivElement>(null);
  const state = useDataGridState({ props, wrapperRef });
  const lastMouseShiftRef = useRef(false);

  const { layout, rowSelection: rowSel, editing, interaction, contextMenu: ctxMenu, viewModels } = state;
  const { visibleCols, hasCheckboxCol, colOffset, containerWidth, minTableWidth, desiredTableWidth, columnSizingOverrides, setColumnSizingOverrides } = layout;
  const { selectedRowIds, updateSelection, handleRowCheckboxChange, handleSelectAll, allSelected, someSelected } = rowSel;
  const { editingCell, setEditingCell, pendingEditorValue, setPendingEditorValue, commitCellEdit, cancelPopoverEdit, popoverAnchorEl, setPopoverAnchorEl } = editing;
  const { setActiveCell, handleCellMouseDown, handleSelectAllCells, selectionRange, hasCellSelection, handleGridKeyDown, handleFillHandleMouseDown, handleCopy, handleCut, handlePaste, cutRange, copyRange, canUndo, canRedo, onUndo, onRedo, isDragging } = interaction;
  const handlePasteVoid = useCallback(() => { void handlePaste(); }, [handlePaste]);
  const { menuPosition, handleCellContextMenu, closeContextMenu } = ctxMenu;
  const { headerFilterInput, cellDescriptorInput, statusBarConfig, showEmptyInGrid, onCellError } = viewModels;

  const {
    items,
    getRowId,
    emptyState,
    layoutMode = 'fill',
    rowSelection = 'none',
    freezeRows,
    freezeCols,
    suppressHorizontalScroll,
    isLoading = false,
    loadingMessage = 'Loading\u2026',
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledBy,
  } = props;

  const fitToContent = layoutMode === 'content';
  const allowOverflowX = !suppressHorizontalScroll && containerWidth > 0 && (minTableWidth > containerWidth || desiredTableWidth > containerWidth);

  // Memoize header rows (recursive tree traversal)
  const headerRows = useMemo(() => buildHeaderRows(props.columns, props.visibleColumns), [props.columns, props.visibleColumns]);

  const { handleResizeStart, getColumnWidth } = useColumnResize<T>({
    columnSizingOverrides,
    setColumnSizingOverrides,
  });

  // Pre-compute per-column layout (tdSx, widths) so GridRow doesn't recalculate per-cell
  const columnLayouts = useMemo<ColumnLayout<T>[]>(() =>
    visibleCols.map((col, colIdx) => {
      const isFreezeCol = freezeCols != null && freezeCols >= 1 && colIdx < freezeCols;
      const isPinnedLeft = col.pinned === 'left';
      const isPinnedRight = col.pinned === 'right';
      const columnWidth = getColumnWidth(col);
      const tdSx = isPinnedLeft || (isFreezeCol && colIdx === 0) ? CELL_TD_PINNED_LEFT_SX : isPinnedRight ? CELL_TD_PINNED_RIGHT_SX : CELL_TD_BASE_SX;
      return { col, tdSx, minWidth: col.minWidth ?? DEFAULT_MIN_COLUMN_WIDTH, width: columnWidth, maxWidth: columnWidth };
    }),
  [visibleCols, freezeCols, getColumnWidth]);

  const editCallbacks = useMemo(() => ({ commitCellEdit, setEditingCell, setPendingEditorValue, cancelPopoverEdit }), [commitCellEdit, setEditingCell, setPendingEditorValue, cancelPopoverEdit]);
  const interactionHandlers = useMemo(() => ({ handleCellMouseDown, setActiveCell, setEditingCell, handleCellContextMenu }), [handleCellMouseDown, setActiveCell, setEditingCell, handleCellContextMenu]);

  // Refs for volatile state — lets renderCellContent be stable (same function ref across
  // selection changes) so that GridRow's React.memo comparator can skip unaffected rows.
  const cellDescriptorInputRef = useLatestRef(cellDescriptorInput);
  const pendingEditorValueRef = useLatestRef(pendingEditorValue);
  const popoverAnchorElRef = useLatestRef(popoverAnchorEl);

  // Stable row-click handler
  const selectedRowIdsRef = useLatestRef(selectedRowIds);

  const handleSingleRowClick = useCallback((e: React.MouseEvent<HTMLTableRowElement>) => {
    if (rowSelection !== 'single') return;
    const rowId = e.currentTarget.dataset.rowId;
    if (!rowId) return;
    const ids = selectedRowIdsRef.current;
    updateSelection(ids.has(rowId) ? new Set() : new Set([rowId]));
  // eslint-disable-next-line react-hooks/exhaustive-deps -- selectedRowIdsRef is a stable ref
  }, [rowSelection, updateSelection]);

  // Wrapper sx (depends on dynamic values — memoize to avoid recreation)
  const wrapperSx = useMemo(() => ({
    position: 'relative' as const,
    flex: 1,
    minHeight: 0,
    width: fitToContent ? 'fit-content' : '100%',
    maxWidth: '100%',
    overflowX: suppressHorizontalScroll ? 'hidden' as const : allowOverflowX ? 'auto' as const : 'hidden' as const,
    overflowY: 'auto' as const,
    bgcolor: 'background.paper',
    willChange: 'scroll-position',
    '& [data-drag-range]': { bgcolor: 'rgba(33, 115, 70, 0.12) !important' },
  }), [fitToContent, suppressHorizontalScroll, allowOverflowX]);

  const renderCellContent = useCallback(
    (item: T, col: IColumnDef<T>, rowIndex: number, colIdx: number): React.ReactNode => {
      const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIdx, cellDescriptorInputRef.current);
      const rowId = getRowId(item);

      let cellContent: React.ReactNode;

      if (descriptor.mode === 'editing-inline') {
        cellContent = <InlineCellEditor<T> {...buildInlineEditorProps(item, col, descriptor, editCallbacks)} />;
      } else if (descriptor.mode === 'editing-popover' && typeof col.cellEditor === 'function') {
        const editorProps = buildPopoverEditorProps(item, col, descriptor, pendingEditorValueRef.current, editCallbacks);
        const CustomEditor = col.cellEditor as React.ComponentType<ICellEditorProps<T>>;
        cellContent = (
          <>
            <Box ref={(el: HTMLDivElement | null) => { if (el) setPopoverAnchorEl(el); }} sx={POPOVER_ANCHOR_SX} aria-hidden />
            <Popover
              open={!!popoverAnchorElRef.current}
              anchorEl={popoverAnchorElRef.current}
              onClose={cancelPopoverEdit}
              anchorOrigin={{ vertical: 'bottom', horizontal: 'left' }}
              transformOrigin={{ vertical: 'top', horizontal: 'left' }}
            >
              <Box sx={POPOVER_CONTENT_SX}>
                <CustomEditor {...editorProps} />
              </Box>
            </Popover>
          </>
        );
      } else {
        const content = resolveCellDisplayContent(col, item, descriptor.displayValue);
        const cellStyle = resolveCellStyle(col, item);
        const styledContent = cellStyle ? <Box component="span" sx={cellStyle}>{content}</Box> : content;

        // Select pre-computed sx variant (module-scope = no per-cell allocation)
        const cellSx = getCellSx(
          col.type,
          descriptor.canEditAny,
          descriptor.isActive && !descriptor.isInRange,
          descriptor.isInRange,
          descriptor.isInCutRange,
        );

        const interactionProps = getCellInteractionProps(descriptor, col.columnId, interactionHandlers);

        cellContent = (
          <Box
            component="div"
            {...interactionProps}
            sx={cellSx}
          >
            {styledContent}
            {descriptor.canEditAny && descriptor.isSelectionEndCell && (
              <Box component="div" onMouseDown={handleFillHandleMouseDown} aria-label="Fill handle" sx={FILL_HANDLE_SX} />
            )}
          </Box>
        );
      }

      return (
        <CellErrorBoundary key={`${rowId}-${col.columnId}`} onError={onCellError}>
          {cellContent}
        </CellErrorBoundary>
      );
    },
    // eslint-disable-next-line react-hooks/exhaustive-deps -- *Ref vars are stable refs from useLatestRef
    [editCallbacks, interactionHandlers, handleFillHandleMouseDown, setPopoverAnchorEl, cancelPopoverEdit, getRowId, onCellError]
  );

  return (
    <Box sx={gridRootSx}>
      <Box
        ref={wrapperRef}
        tabIndex={0}
        role="region"
        aria-label={ariaLabel ?? (ariaLabelledBy ? undefined : 'Data grid')}
        aria-labelledby={ariaLabelledBy}
        onMouseDown={(e) => { lastMouseShiftRef.current = e.shiftKey; }}
        onKeyDown={handleGridKeyDown}
        onContextMenu={PREVENT_DEFAULT}
        data-overflow-x={allowOverflowX ? 'true' : 'false'}
        sx={wrapperSx}
      >
      <Box sx={WRAPPER_SCROLL_SX}>
      <TableContainer sx={{ minWidth: allowOverflowX ? minTableWidth : undefined }}>
        <Box ref={tableContainerRef} sx={isLoading && items.length > 0 ? TABLE_WRAPPER_LOADING_SX : TABLE_WRAPPER_SX}>
          <Table size="small" sx={{ overflow: 'hidden', minWidth: minTableWidth }}
            data-freeze-rows={freezeRows != null && freezeRows >= 1 ? freezeRows : undefined}
            data-freeze-cols={freezeCols != null && freezeCols >= 1 ? freezeCols : undefined}
          >
            <TableHead sx={STICKY_HEADER_SX}>
              {headerRows.map((row, rowIdx) => (
                <TableRow key={rowIdx} sx={HEADER_ROW_SX}>
                  {/* Checkbox column in the last (leaf) row only */}
                  {rowIdx === headerRows.length - 1 && hasCheckboxCol && (
                    <TableCell
                      padding="checkbox"
                      rowSpan={headerRows.length > 1 ? 1 : undefined}
                      sx={CHECKBOX_CELL_SX}
                    >
                      <Checkbox
                        checked={allSelected}
                        indeterminate={someSelected}
                        onChange={(_, c) => handleSelectAll(!!c)}
                        size="small"
                        aria-label="Select all rows"
                      />
                    </TableCell>
                  )}
                  {/* Empty placeholder for checkbox in the first group row */}
                  {rowIdx === 0 && rowIdx < headerRows.length - 1 && hasCheckboxCol && (
                    <TableCell rowSpan={headerRows.length - 1} sx={CHECKBOX_PLACEHOLDER_SX} />
                  )}
                  {row.map((cell, cellIdx) => {
                    if (cell.isGroup) {
                      return (
                        <TableCell
                          key={cellIdx}
                          colSpan={cell.colSpan}
                          component="th"
                          scope="colgroup"
                          sx={GROUP_HEADER_CELL_SX}
                        >
                          {cell.label}
                        </TableCell>
                      );
                    }
                    // Leaf cell
                    const col = cell.columnDef! as IColumnDef<T>;
                    const colIdx = visibleCols.indexOf(col);
                    const isFreezeCol = freezeCols != null && freezeCols >= 1 && colIdx < freezeCols;
                    const isPinnedLeft = col.pinned === 'left';
                    const isPinnedRight = col.pinned === 'right';
                    const columnWidth = getColumnWidth(col);
                    const headerSx = isPinnedLeft || (isFreezeCol && colIdx === 0) ? HEADER_PINNED_LEFT_SX : isPinnedRight ? HEADER_PINNED_RIGHT_SX : HEADER_BASE_SX;
                    return (
                      <TableCell
                        key={col.columnId}
                        component="th"
                        scope="col"
                        rowSpan={headerRows.length > 1 ? headerRows.length - rowIdx : undefined}
                        sx={headerSx}
                        style={{ minWidth: col.minWidth ?? DEFAULT_MIN_COLUMN_WIDTH, width: columnWidth, maxWidth: columnWidth }}
                      >
                        <ColumnHeaderFilter {...getHeaderFilterConfig(col, headerFilterInput)} />
                        <Box onMouseDown={(e) => handleResizeStart(e, col)} sx={RESIZE_HANDLE_SX} />
                      </TableCell>
                    );
                  })}
                </TableRow>
              ))}
            </TableHead>
            {!showEmptyInGrid && (
              <TableBody>
                {items.map((item, rowIndex) => {
                  const rowIdStr = getRowId(item);
                  return (
                    <GridRow
                      key={rowIdStr}
                      item={item}
                      rowIndex={rowIndex}
                      rowId={rowIdStr}
                      isSelected={selectedRowIds.has(rowIdStr)}
                      columnLayouts={columnLayouts as ColumnLayout<unknown>[]}
                      renderCellContent={renderCellContent as GridRowProps['renderCellContent']}
                      handleSingleRowClick={handleSingleRowClick}
                      handleRowCheckboxChange={handleRowCheckboxChange}
                      lastMouseShiftRef={lastMouseShiftRef}
                      hasCheckboxCol={hasCheckboxCol}
                      selectionRange={selectionRange}
                      activeCell={interaction.activeCell}
                      cutRange={cutRange}
                      copyRange={copyRange}
                      isDragging={isDragging}
                      editingRowId={editingCell?.rowId ?? null}
                    />
                  );
                })}
              </TableBody>
            )}
          </Table>
          <MarchingAntsOverlay
            containerRef={tableContainerRef}
            selectionRange={selectionRange}
            copyRange={copyRange}
            cutRange={cutRange}
            colOffset={colOffset}
          />
          {showEmptyInGrid && emptyState && (
            <Box sx={EMPTY_STATE_SX}>
              {emptyState.render ? (
                emptyState.render()
              ) : (
                <>
                  <Typography variant="h6" gutterBottom>No results found</Typography>
                  <Typography variant="body2" color="text.secondary">
                    {emptyState.message != null ? (
                      emptyState.message
                    ) : emptyState.hasActiveFilters ? (
                      <>
                        No items match your current filters. Try adjusting your search or{' '}
                        <Button variant="text" size="small" onClick={emptyState.onClearAll}>clear all filters</Button>{' '}
                        to see all items.
                      </>
                    ) : (
                      'There are no items available at this time.'
                    )}
                  </Typography>
                </>
              )}
            </Box>
          )}
        </Box>
      </TableContainer>
      </Box>

        {menuPosition &&
          createPortal(
            <GridContextMenu
              x={menuPosition.x}
              y={menuPosition.y}
              hasSelection={hasCellSelection}
              canUndo={canUndo}
              canRedo={canRedo}
              onUndo={onUndo ?? NOOP}
              onRedo={onRedo ?? NOOP}
              onCopy={handleCopy}
              onCut={handleCut}
              onPaste={handlePasteVoid}
              onSelectAll={handleSelectAllCells}
              onClose={closeContextMenu}
            />,
            document.body
          )}
      </Box>
      {statusBarConfig && (
        <StatusBar
          totalCount={statusBarConfig.totalCount}
          filteredCount={statusBarConfig.filteredCount}
          selectedCount={statusBarConfig.selectedCount ?? selectedRowIds.size}
          selectedCellCount={selectionRange ? (Math.abs(selectionRange.endRow - selectionRange.startRow) + 1) * (Math.abs(selectionRange.endCol - selectionRange.startCol) + 1) : undefined}
          aggregation={statusBarConfig.aggregation}
          suppressRowCount={statusBarConfig.suppressRowCount}
        />
      )}
      {isLoading && items.length > 0 && (
        <Box sx={LOADING_OVERLAY_SX}>
          <Box sx={LOADING_INNER_SX}>
            <CircularProgress size={24} />
            <Typography variant="body2" color="text.secondary">{loadingMessage}</Typography>
          </Box>
        </Box>
      )}
    </Box>
  );
}

export const DataGridTable = React.memo(DataGridTableInner) as typeof DataGridTableInner;
