// packages/angular/src/components/base-inline-cell-editor.component.ts
import { Input, Output, EventEmitter, signal, computed, ElementRef, ViewChild } from '@angular/core';
import type { IColumnDef } from '@alaarab/ogrid-core';

/**
 * Abstract base class for Angular inline cell editors.
 * Contains all shared signals, lifecycle hooks, keyboard handlers,
 * dropdown positioning, and display logic.
 *
 * Subclasses only need a @Component decorator with selector + template.
 */
export abstract class BaseInlineCellEditorComponent<T = unknown> {
  @Input({ required: true }) value!: unknown;
  @Input({ required: true }) item!: T;
  @Input({ required: true }) column!: IColumnDef<T>;
  @Input({ required: true }) rowIndex!: number;
  @Input({ required: true }) editorType!: 'text' | 'select' | 'checkbox' | 'date' | 'richSelect';
  @Output() commit = new EventEmitter<unknown>();
  @Output() cancel = new EventEmitter<void>();

  @ViewChild('inputEl') inputEl?: ElementRef<HTMLInputElement | HTMLSelectElement>;
  @ViewChild('selectWrapper') selectWrapper?: ElementRef<HTMLDivElement>;
  @ViewChild('selectDropdown') selectDropdown?: ElementRef<HTMLDivElement>;
  @ViewChild('richSelectWrapper') richSelectWrapper?: ElementRef<HTMLDivElement>;
  @ViewChild('richSelectInput') richSelectInput?: ElementRef<HTMLInputElement>;
  @ViewChild('richSelectDropdown') richSelectDropdown?: ElementRef<HTMLDivElement>;

  readonly localValue = signal<unknown>('');
  readonly highlightedIndex = signal(0);
  readonly selectOptions = signal<unknown[]>([]);
  readonly searchText = signal('');
  private scrollCleanup: (() => void) | null = null;
  readonly filteredOptions = computed(() => {
    const options = this.selectOptions();
    const search = this.searchText().trim().toLowerCase();
    if (!search) return options;
    return options.filter((v) => this.getDisplayText(v).toLowerCase().includes(search));
  });

  private _initialized = false;

  ngOnInit(): void {
    this._initialized = true;
    this.syncFromInputs();
  }

  ngOnChanges(): void {
    if (this._initialized) {
      this.syncFromInputs();
    }
  }

  private syncFromInputs(): void {
    const v = this.value;
    let strVal = v != null ? String(v) : '';
    if (this.editorType === 'date' && strVal.match(/^\d{4}-\d{2}-\d{2}/)) {
      strVal = strVal.substring(0, 10);
    }
    this.localValue.set(strVal);

    const col = this.column;
    if (col?.cellEditorParams?.values) {
      const vals = col.cellEditorParams.values as unknown[];
      this.selectOptions.set(vals);
      const initialIdx = vals.findIndex((opt) => String(opt) === String(v));
      this.highlightedIndex.set(Math.max(initialIdx, 0));
    }
  }

  ngAfterViewInit(): void {
    setTimeout(() => {
      const richSelectInput = this.richSelectInput?.nativeElement;
      if (richSelectInput) {
        richSelectInput.focus();
        richSelectInput.select();
        this.positionFixedDropdown(this.richSelectWrapper, this.richSelectDropdown);
        this.attachScrollClose(this.richSelectWrapper?.nativeElement);
        return;
      }
      const selectWrap = this.selectWrapper?.nativeElement;
      if (selectWrap) {
        selectWrap.focus();
        this.positionFixedDropdown(this.selectWrapper, this.selectDropdown);
        this.attachScrollClose(selectWrap);
        return;
      }
      const el = this.inputEl?.nativeElement;
      if (el) {
        el.focus();
        if (el instanceof HTMLInputElement && el.type === 'text') {
          el.select();
        }
      }
    });
  }

  ngOnDestroy(): void {
    this.scrollCleanup?.();
  }

  /** Attach scroll listeners to close the editor when the grid scrolls.
   *  Delayed via RAF to skip spurious scroll events fired during mount
   *  (e.g. focus-triggered scroll, layout-shift scroll from DOM changes). */
  private attachScrollClose(wrapper: HTMLElement | undefined): void {
    if (!wrapper) return;
    const scrollParent = wrapper.closest('[data-ogrid-scroll-container]') ?? wrapper.closest('[style*="overflow"]');
    const handleScroll = () => this.cancel.emit();
    const raf = requestAnimationFrame(() => {
      if (scrollParent) scrollParent.addEventListener('scroll', handleScroll, { passive: true });
      window.addEventListener('scroll', handleScroll, { passive: true });
    });
    this.scrollCleanup = () => {
      cancelAnimationFrame(raf);
      if (scrollParent) scrollParent.removeEventListener('scroll', handleScroll);
      window.removeEventListener('scroll', handleScroll);
    };
  }

  commitValue(value: unknown): void {
    this.commit.emit(value);
  }

  onTextKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Enter') {
      e.preventDefault();
      this.commitValue(this.localValue());
    } else if (e.key === 'Escape') {
      e.preventDefault();
      this.cancel.emit();
    } else if (e.key === 'Tab') {
      e.preventDefault();
      this.commitValue(this.localValue());
    }
  }

  getDisplayText(value: unknown): string {
    const formatValue = this.column?.cellEditorParams?.formatValue as ((v: unknown) => string) | undefined;
    if (formatValue) return formatValue(value);
    return value != null ? String(value) : '';
  }

  onCustomSelectKeyDown(e: KeyboardEvent): void {
    const options = this.selectOptions();
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        this.highlightedIndex.set(Math.min(this.highlightedIndex() + 1, options.length - 1));
        this.scrollOptionIntoView(this.selectDropdown);
        break;
      case 'ArrowUp':
        e.preventDefault();
        this.highlightedIndex.set(Math.max(this.highlightedIndex() - 1, 0));
        this.scrollOptionIntoView(this.selectDropdown);
        break;
      case 'Enter':
        e.preventDefault();
        e.stopPropagation();
        if (options.length > 0 && this.highlightedIndex() < options.length) {
          this.commitValue(options[this.highlightedIndex()]);
        }
        break;
      case 'Tab':
        e.preventDefault();
        if (options.length > 0 && this.highlightedIndex() < options.length) {
          this.commitValue(options[this.highlightedIndex()]);
        }
        break;
      case 'Escape':
        e.preventDefault();
        e.stopPropagation();
        this.cancel.emit();
        break;
    }
  }

  onRichSelectSearch(text: string): void {
    this.searchText.set(text);
    this.highlightedIndex.set(0);
  }

  onRichSelectKeyDown(e: KeyboardEvent): void {
    const options = this.filteredOptions();
    switch (e.key) {
      case 'ArrowDown':
        e.preventDefault();
        this.highlightedIndex.set(Math.min(this.highlightedIndex() + 1, options.length - 1));
        this.scrollOptionIntoView(this.richSelectDropdown);
        break;
      case 'ArrowUp':
        e.preventDefault();
        this.highlightedIndex.set(Math.max(this.highlightedIndex() - 1, 0));
        this.scrollOptionIntoView(this.richSelectDropdown);
        break;
      case 'Enter':
        e.preventDefault();
        e.stopPropagation();
        if (options.length > 0 && this.highlightedIndex() < options.length) {
          this.commitValue(options[this.highlightedIndex()]);
        }
        break;
      case 'Escape':
        e.preventDefault();
        e.stopPropagation();
        this.cancel.emit();
        break;
    }
  }

  onCheckboxKeyDown(e: KeyboardEvent): void {
    if (e.key === 'Escape') {
      e.preventDefault();
      this.cancel.emit();
    }
  }

  onTextBlur(): void {
    this.commitValue(this.localValue());
  }

  getInputStyle(): string {
    const baseStyle = 'width:100%;box-sizing:border-box;padding:6px 10px;border:none;outline:none;font:inherit;background:transparent;color:inherit;';
    const col = this.column;
    if (col.type === 'numeric') {
      return baseStyle + 'text-align:right;';
    }
    return baseStyle;
  }

  /** Position a dropdown using fixed positioning to escape overflow clipping. */
  protected positionFixedDropdown(
    wrapperRef: ElementRef<HTMLDivElement> | undefined,
    dropdownRef: ElementRef<HTMLDivElement> | undefined
  ): void {
    const wrapper = wrapperRef?.nativeElement;
    const dropdown = dropdownRef?.nativeElement;
    if (!wrapper || !dropdown) return;
    const rect = wrapper.getBoundingClientRect();
    const maxH = 200;
    const spaceBelow = window.innerHeight - rect.bottom;
    const flipUp = spaceBelow < maxH && rect.top > spaceBelow;
    dropdown.style.position = 'fixed';
    dropdown.style.left = `${rect.left}px`;
    dropdown.style.width = `${rect.width}px`;
    dropdown.style.maxHeight = `${maxH}px`;
    dropdown.style.zIndex = '9999';
    dropdown.style.right = 'auto';
    dropdown.style.textAlign = 'left';
    if (flipUp) {
      dropdown.style.top = 'auto';
      dropdown.style.bottom = `${window.innerHeight - rect.top}px`;
    } else {
      dropdown.style.top = `${rect.bottom}px`;
    }
  }

  /** Scroll the highlighted option into view within a dropdown element. */
  protected scrollOptionIntoView(dropdownRef: ElementRef<HTMLDivElement> | undefined): void {
    setTimeout(() => {
      const dropdown = dropdownRef?.nativeElement;
      if (!dropdown) return;
      const highlighted = dropdown.children[this.highlightedIndex()] as HTMLElement | undefined;
      highlighted?.scrollIntoView({ block: 'nearest' });
    });
  }
}

// packages/react/src/components/BaseInlineCellEditor.tsx
import * as React from 'react';
import { createPortal } from 'react-dom';
import type { IColumnDef } from '../types';
import { useInlineCellEditorState, useRichSelectState, useSelectState } from '../hooks';

// ── Shared editor style constants (used across all 3 UI packages) ──

export const editorWrapperStyle: React.CSSProperties = {
  width: '100%',
  height: '100%',
  display: 'flex',
  alignItems: 'center',
  padding: '6px 10px',
  boxSizing: 'border-box',
  overflow: 'hidden',
  minWidth: 0,
};

export const editorInputStyle: React.CSSProperties = {
  width: '100%',
  padding: 0,
  border: 'none',
  background: 'transparent',
  color: 'inherit',
  font: 'inherit',
  fontSize: '13px',
  outline: 'none',
  minWidth: 0,
};

export const richSelectWrapperStyle: React.CSSProperties = {
  ...editorWrapperStyle,
  position: 'relative',
};

export const richSelectDropdownStyle: React.CSSProperties = {
  position: 'absolute',
  top: '100%',
  left: 0,
  right: 0,
  maxHeight: 200,
  overflowY: 'auto',
  background: 'var(--ogrid-bg, #fff)',
  border: '1px solid var(--ogrid-border, rgba(0, 0, 0, 0.12))',
  zIndex: 10,
  boxShadow: 'var(--ogrid-shadow, 0 4px 16px rgba(0,0,0,0.2))',
  textAlign: 'left',
};

export const richSelectOptionStyle: React.CSSProperties = {
  padding: '6px 8px',
  cursor: 'pointer',
  color: 'var(--ogrid-fg, #242424)',
};

export const richSelectOptionHighlightedStyle: React.CSSProperties = {
  ...richSelectOptionStyle,
  background: 'var(--ogrid-bg-hover, #e8f0fe)',
};

export const richSelectNoMatchesStyle: React.CSSProperties = {
  padding: '6px 8px',
  color: 'var(--ogrid-muted, #999)',
};

export const selectEditorStyle: React.CSSProperties = {
  width: '100%',
  padding: 0,
  border: 'none',
  background: 'transparent',
  color: 'inherit',
  font: 'inherit',
  fontSize: '13px',
  cursor: 'pointer',
  outline: 'none',
};

export const selectDisplayStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  justifyContent: 'space-between',
  width: '100%',
  cursor: 'pointer',
  fontSize: '13px',
  color: 'inherit',
};

export const selectChevronStyle: React.CSSProperties = {
  marginLeft: 4,
  fontSize: '10px',
  opacity: 0.5,
};

// ── BaseInlineCellEditor component ──

export interface BaseInlineCellEditorProps<T> {
  value: unknown;
  item: T;
  column: IColumnDef<T>;
  rowIndex: number;
  editorType: 'text' | 'select' | 'checkbox' | 'richSelect' | 'date';
  onCommit: (value: unknown) => void;
  onCancel: () => void;
  /** Framework-specific checkbox renderer */
  renderCheckbox: (checked: boolean, onCommit: (value: boolean) => void, onCancel: () => void) => React.ReactNode;
  /** @deprecated Built-in custom dropdown is now used. Kept for backward compatibility. */
  renderSelect?: (
    value: unknown,
    values: unknown[],
    onCommit: (value: unknown) => void,
    onCancel: () => void,
  ) => React.ReactNode;
}

/**
 * Base inline cell editor with shared logic for all editor types except checkbox
 * (which is framework-specific). Used by all 3 UI packages to avoid duplication.
 *
 * Text, date, select, and richSelect editors are fully shared.
 * Checkbox is delegated via renderCheckbox render prop.
 */
export function BaseInlineCellEditor<T>(props: BaseInlineCellEditorProps<T>): React.ReactElement {
  const { value, column, editorType, onCommit, onCancel, renderCheckbox } = props;
  const wrapperRef = React.useRef<HTMLDivElement>(null);
  const onCancelRef = React.useRef(onCancel);
  onCancelRef.current = onCancel;
  const { localValue, setLocalValue, handleKeyDown, handleBlur, commit, cancel } =
    useInlineCellEditorState({ value, editorType, onCommit, onCancel });

  const editorValues = (column.cellEditorParams?.values as unknown[]) ?? [];
  const editorFormatValue = column.cellEditorParams?.formatValue as ((v: unknown) => string) | undefined;
  const richSelect = useRichSelectState({
    values: editorValues,
    formatValue: editorFormatValue,
    initialValue: value,
    onCommit,
    onCancel,
  });
  const selectState = useSelectState({
    values: editorValues,
    formatValue: editorFormatValue,
    initialValue: value,
    onCommit,
    onCancel,
  });

  // Fixed dropdown positioning to escape ancestor overflow clipping (.tableWrapper)
  const [fixedDropdownStyle, setFixedDropdownStyle] = React.useState<React.CSSProperties | null>(null);

  React.useLayoutEffect(() => {
    if (editorType !== 'select' && editorType !== 'richSelect') return;
    const wrapper = wrapperRef.current;
    if (!wrapper) return;
    const rect = wrapper.getBoundingClientRect();
    const maxH = 200;
    const spaceBelow = window.innerHeight - rect.bottom;
    const flipUp = spaceBelow < maxH && rect.top > spaceBelow;
    setFixedDropdownStyle({
      position: 'fixed',
      ...(flipUp ? { bottom: window.innerHeight - rect.top } : { top: rect.bottom }),
      left: rect.left,
      width: rect.width,
      maxHeight: maxH,
      overflowY: 'auto',
      background: 'var(--ogrid-bg, #fff)',
      border: '1px solid var(--ogrid-border, rgba(0, 0, 0, 0.12))',
      zIndex: 9999,
      boxShadow: 'var(--ogrid-shadow, 0 4px 16px rgba(0,0,0,0.2))',
      textAlign: 'left',
    });

    // Close editor on scroll so the fixed dropdown doesn't drift away from the cell.
    // Delay attachment via RAF to skip spurious scroll events fired during mount
    // (e.g. focus-triggered scroll, layout-shift scroll from DOM changes).
    const scrollParent = wrapper.closest('[data-ogrid-scroll-container]') ?? wrapper.closest('[style*="overflow"]');
    const handleScroll = () => onCancelRef.current();
    const raf = requestAnimationFrame(() => {
      if (scrollParent) {
        scrollParent.addEventListener('scroll', handleScroll, { passive: true });
      }
      window.addEventListener('scroll', handleScroll, { passive: true });
    });
    return () => {
      cancelAnimationFrame(raf);
      if (scrollParent) scrollParent.removeEventListener('scroll', handleScroll);
      window.removeEventListener('scroll', handleScroll);
    };
  }, [editorType]);

  const computedDropdownStyle = fixedDropdownStyle ?? richSelectDropdownStyle;

  React.useEffect(() => {
    const wrapper = wrapperRef.current;
    if (!wrapper) return;
    const input = wrapper.querySelector('input');
    if (input) {
      input.focus({ preventScroll: true });
      // Select all text for easy replacement (like Excel)
      input.select();
    } else {
      // Focus the wrapper for keyboard events (select editor has no input)
      wrapper.focus({ preventScroll: true });
    }
  }, []); // Mount-only: intentionally runs once to focus/open picker on editor open

  // Helper: portal dropdown to document.body when using fixed positioning
  // to escape ancestor `contain: content` which clips even fixed elements
  const usePortal = fixedDropdownStyle != null;

  // Rich select (shared across all frameworks)
  if (editorType === 'richSelect') {
    const dropdownContent = (
      <div style={computedDropdownStyle} role="listbox">
        {richSelect.filteredValues.map((v, i) => (
          <div
            key={String(v)}
            role="option"
            aria-selected={i === richSelect.highlightedIndex}
            onClick={() => richSelect.selectValue(v)}
            style={i === richSelect.highlightedIndex ? richSelectOptionHighlightedStyle : richSelectOptionStyle}
          >
            {richSelect.getDisplayText(v)}
          </div>
        ))}
        {richSelect.filteredValues.length === 0 && (
          <div style={richSelectNoMatchesStyle}>No matches</div>
        )}
      </div>
    );
    return (
      <div ref={wrapperRef} style={richSelectWrapperStyle}>
        <input
          type="text"
          value={richSelect.searchText}
          onChange={(e) => richSelect.setSearchText(e.target.value)}
          onKeyDown={richSelect.handleKeyDown}
          placeholder="Search..."
          autoFocus
          style={editorInputStyle}
        />
        {usePortal ? createPortal(dropdownContent, document.body) : dropdownContent}
      </div>
    );
  }

  // Checkbox (framework-specific)
  if (editorType === 'checkbox') {
    const checked = value === true;
    return <>{renderCheckbox(checked, (val) => commit(val), cancel)}</>;
  }

  // Select (custom dropdown, shared across all frameworks)
  if (editorType === 'select') {
    const dropdownContent = (
      <div style={computedDropdownStyle} ref={selectState.dropdownRef} role="listbox">
        {editorValues.map((v, i) => (
          <div
            key={String(v)}
            role="option"
            aria-selected={i === selectState.highlightedIndex}
            onClick={() => selectState.selectValue(v)}
            style={i === selectState.highlightedIndex ? richSelectOptionHighlightedStyle : richSelectOptionStyle}
          >
            {selectState.getDisplayText(v)}
          </div>
        ))}
      </div>
    );
    return (
      <div ref={wrapperRef} style={richSelectWrapperStyle} onKeyDown={selectState.handleKeyDown} tabIndex={0}>
        <div style={selectDisplayStyle}>
          <span>{selectState.getDisplayText(value)}</span>
          <span style={selectChevronStyle}>&#9662;</span>
        </div>
        {usePortal ? createPortal(dropdownContent, document.body) : dropdownContent}
      </div>
    );
  }

  // Date editor — plain text input (Excel-style: type the date, no native calendar)
  if (editorType === 'date') {
    return (
      <div ref={wrapperRef} style={editorWrapperStyle}>
        <input
          type="text"
          value={localValue}
          onChange={(e) => setLocalValue(e.target.value)}
          onBlur={handleBlur}
          onKeyDown={handleKeyDown}
          placeholder="YYYY-MM-DD"
          style={editorInputStyle}
          autoFocus
        />
      </div>
    );
  }

  // Text editor (default, shared across all frameworks)
  return (
    <div ref={wrapperRef} style={editorWrapperStyle}>
      <input
        type="text"
        value={localValue}
        onChange={(e) => setLocalValue(e.target.value)}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        style={editorInputStyle}
        autoFocus
      />
    </div>
  );
}
