// packages/angular/src/components/formula-ref-overlay.component.ts
/**
 * FormulaRefOverlayComponent -- Renders colored border overlays on cells
 * referenced by the active formula, like Excel's reference highlighting.
 *
 * Port of React's FormulaRefOverlay component.
 */

import {
  Component,
  ChangeDetectionStrategy,
  ViewEncapsulation,
  input,
  signal,
  effect,
} from '@angular/core';
import { FORMULA_REF_COLORS, type FormulaReference } from '@alaarab/ogrid-core';

interface RefRect {
  top: number;
  left: number;
  width: number;
  height: number;
  color: string;
}

function measureRef(
  container: HTMLElement,
  ref: FormulaReference,
  colOffset: number,
): RefRect | null {
  const startCol = ref.col + colOffset;
  const endCol = (ref.endCol ?? ref.col) + colOffset;
  const endRow = ref.endRow ?? ref.row;

  const tl = container.querySelector(
    `[data-row-index="${ref.row}"][data-col-index="${startCol}"]`
  ) as HTMLElement | null;
  const br = container.querySelector(
    `[data-row-index="${endRow}"][data-col-index="${endCol}"]`
  ) as HTMLElement | null;

  if (!tl || !br) return null;

  const cRect = container.getBoundingClientRect();
  const tlRect = tl.getBoundingClientRect();
  const brRect = br.getBoundingClientRect();

  return {
    top: Math.round(tlRect.top - cRect.top),
    left: Math.round(tlRect.left - cRect.left),
    width: Math.round(brRect.right - tlRect.left),
    height: Math.round(brRect.bottom - tlRect.top),
    color: FORMULA_REF_COLORS[ref.colorIndex % FORMULA_REF_COLORS.length],
  };
}

@Component({
  selector: 'ogrid-formula-ref-overlay',
  standalone: true,
  encapsulation: ViewEncapsulation.None,
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @for (r of rects(); track $index) {
      <svg
        [style.position]="'absolute'"
        [style.top.px]="r.top"
        [style.left.px]="r.left"
        [style.width.px]="r.width"
        [style.height.px]="r.height"
        [style.pointerEvents]="'none'"
        [style.zIndex]="3"
        [style.overflow]="'visible'"
        aria-hidden="true"
      >
        <rect
          x="1" y="1"
          [attr.width]="max0(r.width - 2)"
          [attr.height]="max0(r.height - 2)"
          fill="none"
          [attr.stroke]="r.color"
          stroke-width="2"
          style="shape-rendering: crispEdges"
        />
      </svg>
    }
  `,
})
export class FormulaRefOverlayComponent {
  /** The positioned container that wraps the table. */
  readonly containerEl = input<HTMLElement | null>(null);
  /** References to highlight. */
  readonly references = input<FormulaReference[]>([]);
  /** Column offset (1 when checkbox/row-number columns are present). */
  readonly colOffset = input<number>(0);

  readonly rects = signal<RefRect[]>([]);

  private rafId = 0;

  constructor() {
    effect(() => {
      const refs = this.references();
      const container = this.containerEl();
      const colOff = this.colOffset();

      cancelAnimationFrame(this.rafId);

      if (!container || refs.length === 0) {
        this.rects.set([]);
        return;
      }

      this.rafId = requestAnimationFrame(() => {
        const measured: RefRect[] = [];
        for (const ref of refs) {
          const r = measureRef(container, ref, colOff);
          if (r) measured.push(r);
        }
        this.rects.set(measured);
      });
    });
  }

  max0(v: number): number {
    return Math.max(0, v);
  }
}

// packages/react/src/components/FormulaRefOverlay.tsx
/**
 * FormulaRefOverlay  -  Renders colored border overlays on cells referenced by
 * the active formula, like Excel's reference highlighting.
 *
 * Uses the same container measurement pattern as MarchingAntsOverlay.
 */

import * as React from 'react';
import { useEffect, useState, useCallback, useRef, memo } from 'react';
import { FORMULA_REF_COLORS, type FormulaReference } from '@alaarab/ogrid-core/formula';

interface RefRect {
  top: number;
  left: number;
  width: number;
  height: number;
  color: string;
}

export interface FormulaRefOverlayProps {
  /** Ref to the positioned container that wraps the table. */
  containerRef: React.RefObject<HTMLElement | null>;
  /** References to highlight. */
  references: FormulaReference[];
  /** Column offset (1 when checkbox/row-number columns are present). */
  colOffset: number;
}

/** Shared SVG rect style  -  avoids recreating on every render. */
const CRISP_EDGES: React.CSSProperties = { shapeRendering: 'crispEdges' };

function measureRef(
  container: HTMLElement,
  ref: FormulaReference,
  colOffset: number,
): RefRect | null {
  const startCol = ref.col + colOffset;
  const endCol = (ref.endCol ?? ref.col) + colOffset;
  const endRow = ref.endRow ?? ref.row;

  const tl = container.querySelector(
    `[data-row-index="${ref.row}"][data-col-index="${startCol}"]`
  ) as HTMLElement | null;
  const br = container.querySelector(
    `[data-row-index="${endRow}"][data-col-index="${endCol}"]`
  ) as HTMLElement | null;

  if (!tl || !br) return null;

  const cRect = container.getBoundingClientRect();
  const tlRect = tl.getBoundingClientRect();
  const brRect = br.getBoundingClientRect();

  return {
    top: Math.round(tlRect.top - cRect.top),
    left: Math.round(tlRect.left - cRect.left),
    width: Math.round(brRect.right - tlRect.left),
    height: Math.round(brRect.bottom - tlRect.top),
    color: FORMULA_REF_COLORS[ref.colorIndex % FORMULA_REF_COLORS.length] ?? FORMULA_REF_COLORS[0] ?? '#217346',
  };
}

function FormulaRefOverlayInner({
  containerRef,
  references,
  colOffset,
}: FormulaRefOverlayProps): React.ReactElement | null {
  const [rects, setRects] = useState<RefRect[]>([]);
  const rafRef = useRef(0);

  const measureAll = useCallback(() => {
    const container = containerRef.current;
    if (!container || references.length === 0) {
      setRects([]);
      return;
    }
    const measured: RefRect[] = [];
    for (const ref of references) {
      const r = measureRef(container, ref, colOffset);
      if (r) measured.push(r);
    }
    setRects(measured);
  }, [references, containerRef, colOffset]);

  useEffect(() => {
    if (references.length === 0) {
      setRects([]);
      return;
    }
    rafRef.current = requestAnimationFrame(measureAll);
    return () => cancelAnimationFrame(rafRef.current);
  }, [references, measureAll]);

  if (rects.length === 0) return null;

  return (
    <>
      {rects.map((r, i) => (
        <svg
          key={i}
          style={{
            position: 'absolute',
            top: r.top,
            left: r.left,
            width: r.width,
            height: r.height,
            pointerEvents: 'none',
            zIndex: 3,
            overflow: 'visible',
          }}
          aria-hidden="true"
        >
          <rect
            x="1"
            y="1"
            width={Math.max(0, r.width - 2)}
            height={Math.max(0, r.height - 2)}
            fill="none"
            stroke={r.color}
            strokeWidth="2"
            style={CRISP_EDGES}
          />
        </svg>
      ))}
    </>
  );
}

export const FormulaRefOverlay = memo(FormulaRefOverlayInner);
