// packages/react-radix/src/ColumnChooser/ColumnChooser.tsx
import * as React from 'react';
import * as Popover from '@radix-ui/react-popover';
import * as Checkbox from '@radix-ui/react-checkbox';
import type { IColumnDefinition } from '@alaarab/ogrid-react';
import { useColumnChooserState } from '@alaarab/ogrid-react';
import styles from './ColumnChooser.module.scss';

export type { IColumnDefinition };

export interface IColumnChooserProps {
  columns: IColumnDefinition[];
  visibleColumns: Set<string>;
  onVisibilityChange: (columnKey: string, visible: boolean) => void;
  className?: string;
}

function TableSettingsIcon(): React.ReactElement {
  return (
    <span className={styles.buttonIcon} aria-hidden>
      ⚙
    </span>
  );
}
function ChevronDown(): React.ReactElement {
  return <span className={styles.chevron} aria-hidden>▼</span>;
}
function ChevronUp(): React.ReactElement {
  return <span className={styles.chevron} aria-hidden>▲</span>;
}

export const ColumnChooser: React.FC<IColumnChooserProps> = (props) => {
  const { columns, visibleColumns, onVisibilityChange, className } = props;

  const {
    open,
    setOpen,
    handleCheckboxChange: setColumnVisible,
    handleSelectAll,
    handleClearAll,
    visibleCount,
    totalCount,
  } = useColumnChooserState({ columns, visibleColumns, onVisibilityChange });

  const handleCheckboxChange = (columnKey: string) => (checked: boolean | 'indeterminate') => {
    setColumnVisible(columnKey)(checked === true);
  };

  return (
    <div className={`${styles.container} ${className || ''}`}>
      <Popover.Root open={open} onOpenChange={setOpen}>
        <Popover.Trigger asChild>
          <button
            type="button"
            className={styles.triggerButton}
            aria-expanded={open}
            aria-haspopup="listbox"
          >
            <TableSettingsIcon />
            <span>
              Column Visibility ({visibleCount} of {totalCount})
            </span>
            {open ? <ChevronUp /> : <ChevronDown />}
          </button>
        </Popover.Trigger>
        <Popover.Portal>
          <Popover.Content
            className={styles.dropdown}
            sideOffset={4}
            align="end"
            onOpenAutoFocus={(e: Event) => e.preventDefault()}
          >
            <div className={styles.header}>Select Columns ({visibleCount} of {totalCount})</div>
            <div className={styles.optionsList}>
              {columns.map((column) => (
                <div key={column.columnId} className={styles.optionItem}>
                  <Checkbox.Root
                    id={`col-${column.columnId}`}
                    checked={visibleColumns.has(column.columnId)}
                    onCheckedChange={handleCheckboxChange(column.columnId)}
                    disabled={column.required === true}
                    className={styles.checkbox}
                  >
                    <Checkbox.Indicator className={styles.checkboxIndicator}>✓</Checkbox.Indicator>
                  </Checkbox.Root>
                  <label htmlFor={`col-${column.columnId}`} style={{ marginLeft: 8, cursor: 'pointer' }}>
                    {column.name}
                  </label>
                </div>
              ))}
            </div>
            <div className={styles.actions}>
              <button type="button" className={styles.clearButton} onClick={handleClearAll}>
                Clear All
              </button>
              <button type="button" className={styles.selectAllButton} onClick={handleSelectAll}>
                Select All
              </button>
            </div>
          </Popover.Content>
        </Popover.Portal>
      </Popover.Root>
    </div>
  );
};

// packages/vue-radix/src/ColumnChooser/ColumnChooser.vue
<script setup lang="ts">
import { Menu, MenuButton, MenuItems, MenuItem } from '@headlessui/vue';
import { useColumnChooserState, type IColumnDefinition } from '@alaarab/ogrid-vue';

export interface IColumnChooserProps {
  columns: IColumnDefinition[];
  visibleColumns: Set<string>;
  onVisibilityChange: (columnKey: string, visible: boolean) => void;
  className?: string;
}

const props = withDefaults(defineProps<IColumnChooserProps>(), {
  className: '',
});

const {
  open,
  setOpen,
  handleCheckboxChange: setColumnVisible,
  handleSelectAll,
  handleClearAll,
  visibleCount,
  totalCount,
} = useColumnChooserState({
  columns: () => props.columns,
  visibleColumns: () => props.visibleColumns,
  onVisibilityChange: props.onVisibilityChange,
});

const handleCheckboxChange = (columnKey: string) => (e: Event) => {
  const target = e.target as HTMLInputElement;
  setColumnVisible(columnKey)(target.checked);
};
</script>

<template>
  <div :class="['container', className]">
    <Menu v-slot="{ open: isOpen }">
      <MenuButton
        class="trigger-button"
        :aria-expanded="isOpen"
        aria-haspopup="listbox"
        @click="setOpen(!open)"
      >
        <span class="button-icon" aria-hidden>⚙</span>
        <span>Column Visibility ({{ visibleCount }} of {{ totalCount }})</span>
        <span class="chevron" aria-hidden>{{ isOpen ? '▲' : '▼' }}</span>
      </MenuButton>

      <transition
        enter-active-class="transition duration-100 ease-out"
        enter-from-class="opacity-0 scale-95"
        enter-to-class="opacity-100 scale-100"
        leave-active-class="transition duration-75 ease-in"
        leave-from-class="opacity-100 scale-100"
        leave-to-class="opacity-0 scale-95"
      >
        <MenuItems class="dropdown">
          <div class="header">Select Columns ({{ visibleCount }} of {{ totalCount }})</div>

          <div class="options-list">
            <MenuItem
              v-for="column in columns"
              :key="column.columnId"
              as="div"
              class="option-item"
            >
              <input
                :id="`col-${column.columnId}`"
                type="checkbox"
                :checked="visibleColumns.has(column.columnId)"
                :disabled="column.required === true"
                class="checkbox-input"
                @change="handleCheckboxChange(column.columnId)"
              />
              <label
                :for="`col-${column.columnId}`"
                class="checkbox-label"
              >
                {{ column.name }}
              </label>
            </MenuItem>
          </div>

          <div class="actions">
            <button type="button" class="clear-button" @click="handleClearAll">
              Clear All
            </button>
            <button type="button" class="select-all-button" @click="handleSelectAll">
              Select All
            </button>
          </div>
        </MenuItems>
      </transition>
    </Menu>
  </div>
</template>

<style scoped lang="scss">
@import './ColumnChooser.module.scss';
</style>
