// packages/react-fluent/src/ColumnChooser/ColumnChooser.tsx
import * as React from 'react';
import { useRef, useEffect } from 'react';
import {
  Button,
  Checkbox,
} from '@fluentui/react-components';
import type { CheckboxOnChangeData } from '@fluentui/react-components';
import { TableSettingsRegular, ChevronDownRegular, ChevronUpRegular } from '@fluentui/react-icons';
import type { IColumnDefinition } from '@alaarab/ogrid-react';
import { useColumnChooserState } from '@alaarab/ogrid-react';
import styles from './ColumnChooser.module.scss';

export type { IColumnDefinition };

export interface IColumnChooserProps {
  columns: IColumnDefinition[];
  visibleColumns: Set<string>;
  onVisibilityChange: (columnKey: string, visible: boolean) => void;
  className?: string;
}

export const ColumnChooser: React.FC<IColumnChooserProps> = (props) => {
  const { columns, visibleColumns, onVisibilityChange, className } = props;
  const buttonRef = useRef<HTMLButtonElement>(null);
  const dropdownRef = useRef<HTMLDivElement>(null);

  const {
    open,
    handleToggle,
    handleClose,
    handleCheckboxChange: setColumnVisible,
    handleSelectAll,
    handleClearAll,
    visibleCount,
    totalCount,
  } = useColumnChooserState({ columns, visibleColumns, onVisibilityChange });

  useEffect(() => {
    if (!open) return;
    const handleClickOutside = (event: MouseEvent): void => {
      const target = event.target as Node;
      if (
        dropdownRef.current && !dropdownRef.current.contains(target) &&
        buttonRef.current && !buttonRef.current.contains(target)
      ) {
        handleClose();
      }
    };
    const timeoutId = setTimeout(() => {
      document.addEventListener('mousedown', handleClickOutside);
    }, 0);
    return () => {
      clearTimeout(timeoutId);
      document.removeEventListener('mousedown', handleClickOutside);
    };
  }, [open, handleClose]);

  const handleCheckboxChange = (columnKey: string) =>
    (_ev: React.ChangeEvent<HTMLInputElement>, data: CheckboxOnChangeData) => {
      setColumnVisible(columnKey)(data.checked === true);
    };

  return (
    <div className={`${styles.container} ${className || ''}`}>
      <Button
        ref={buttonRef}
        appearance="outline"
        icon={<TableSettingsRegular />}
        onClick={handleToggle}
        aria-expanded={open}
        aria-haspopup="listbox"
      >
        Column Visibility ({visibleCount} of {totalCount})
        {open ? <ChevronUpRegular /> : <ChevronDownRegular />}
      </Button>

      {open && (
        <div ref={dropdownRef} className={styles.dropdown}>
          <div className={styles.header}>
            Select Columns ({visibleCount} of {totalCount})
          </div>
          <div className={styles.optionsList}>
            {columns.map((column) => (
              <div key={column.columnId} className={styles.optionItem}>
                <Checkbox
                  label={column.name}
                  checked={visibleColumns.has(column.columnId)}
                  onChange={handleCheckboxChange(column.columnId)}
                />
              </div>
            ))}
          </div>
          <div className={styles.actions}>
            <Button appearance="subtle" size="small" onClick={handleClearAll}>
              Clear All
            </Button>
            <Button appearance="primary" size="small" onClick={handleSelectAll}>
              Select All
            </Button>
          </div>
        </div>
      )}
    </div>
  );
};

// packages/vue-radix/src/ColumnChooser/ColumnChooser.vue
<script setup lang="ts">
import { Menu, MenuButton, MenuItems, MenuItem } from '@headlessui/vue';
import { useColumnChooserState, type IColumnDefinition } from '@alaarab/ogrid-vue';

export interface IColumnChooserProps {
  columns: IColumnDefinition[];
  visibleColumns: Set<string>;
  onVisibilityChange: (columnKey: string, visible: boolean) => void;
  className?: string;
}

const props = withDefaults(defineProps<IColumnChooserProps>(), {
  className: '',
});

const {
  open,
  setOpen,
  handleCheckboxChange: setColumnVisible,
  handleSelectAll,
  handleClearAll,
  visibleCount,
  totalCount,
} = useColumnChooserState({
  columns: () => props.columns,
  visibleColumns: () => props.visibleColumns,
  onVisibilityChange: props.onVisibilityChange,
});

const handleCheckboxChange = (columnKey: string) => (e: Event) => {
  const target = e.target as HTMLInputElement;
  setColumnVisible(columnKey)(target.checked);
};
</script>

<template>
  <div :class="['container', className]">
    <Menu v-slot="{ open: isOpen }">
      <MenuButton
        class="trigger-button"
        :aria-expanded="isOpen"
        aria-haspopup="listbox"
        @click="setOpen(!open)"
      >
        <span class="button-icon" aria-hidden>⚙</span>
        <span>Column Visibility ({{ visibleCount }} of {{ totalCount }})</span>
        <span class="chevron" aria-hidden>{{ isOpen ? '▲' : '▼' }}</span>
      </MenuButton>

      <transition
        enter-active-class="transition duration-100 ease-out"
        enter-from-class="opacity-0 scale-95"
        enter-to-class="opacity-100 scale-100"
        leave-active-class="transition duration-75 ease-in"
        leave-from-class="opacity-100 scale-100"
        leave-to-class="opacity-0 scale-95"
      >
        <MenuItems class="dropdown">
          <div class="header">Select Columns ({{ visibleCount }} of {{ totalCount }})</div>

          <div class="options-list">
            <MenuItem
              v-for="column in columns"
              :key="column.columnId"
              as="div"
              class="option-item"
            >
              <input
                :id="`col-${column.columnId}`"
                type="checkbox"
                :checked="visibleColumns.has(column.columnId)"
                :disabled="column.required === true"
                class="checkbox-input"
                @change="handleCheckboxChange(column.columnId)"
              />
              <label
                :for="`col-${column.columnId}`"
                class="checkbox-label"
              >
                {{ column.name }}
              </label>
            </MenuItem>
          </div>

          <div class="actions">
            <button type="button" class="clear-button" @click="handleClearAll">
              Clear All
            </button>
            <button type="button" class="select-all-button" @click="handleSelectAll">
              Select All
            </button>
          </div>
        </MenuItems>
      </transition>
    </Menu>
  </div>
</template>

<style scoped lang="scss">
@import './ColumnChooser.module.scss';
</style>
