// packages/react-radix/src/DataGridTable/EmptyState.tsx
import * as React from 'react';
import styles from './DataGridTable.module.scss';

interface EmptyStateProps {
  emptyState: {
    render?: () => React.ReactNode;
    message?: React.ReactNode;
    hasActiveFilters?: boolean;
    onClearAll?: () => void;
  };
}

export function EmptyState({ emptyState }: EmptyStateProps): React.ReactElement {
  return (
    <div className={styles.emptyStateInGrid}>
      <div>
        {emptyState.render ? (
          emptyState.render()
        ) : (
          <>
            <div className={styles.emptyStateInGridTitle}>No results found</div>
            <div className={styles.emptyStateInGridMessage}>
              {emptyState.message != null ? (
                emptyState.message
              ) : emptyState.hasActiveFilters ? (
                <>
                  No items match your current filters. Try adjusting your search or{' '}
                  <button type="button" className={styles.emptyStateInGridLink} onClick={emptyState.onClearAll}>
                    clear all filters
                  </button>{' '}
                  to see all items.
                </>
              ) : (
                'There are no items available at this time.'
              )}
            </div>
          </>
        )}
      </div>
    </div>
  );
}

// packages/angular/src/components/empty-state.component.ts
import { Component, input, output } from '@angular/core';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'ogrid-empty-state',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    .ogrid-empty-state-clear-btn {
      background: none; border: none; color: inherit;
      text-decoration: underline; cursor: pointer; padding: 0; font: inherit;
    }
  `],
  template: `
    @if (render()) {
      <ng-container [ngTemplateOutlet]="render()!"></ng-container>
    } @else if (message()) {
      {{ message() }}
    } @else if (hasActiveFilters()) {
      No items match your current filters. Try adjusting your search or
      <button type="button" (click)="clearAll.emit()" class="ogrid-empty-state-clear-btn">
        clear all filters
      </button>
      to see all items.
    } @else {
      There are no items available at this time.
    }
  `,
})
export class EmptyStateComponent {
  readonly message = input<string | undefined>(undefined);
  readonly hasActiveFilters = input<boolean>(false);
  readonly render = input<unknown>(undefined);
  readonly clearAll = output<void>();
}
