// packages/vue-radix/src/DataGridTable/MarchingAntsOverlay.vue
<script setup lang="ts">
/**
 * MarchingAntsOverlay — Renders range overlays on top of the grid:
 *
 * 1. **Selection range**: solid green border around the current selection
 * 2. **Copy/Cut range**: animated dashed border (marching ants) like Excel
 *
 * Uses SVG rects positioned via cell data-attribute measurements.
 */
import { ref, computed, watch, onMounted, onUnmounted, type Ref } from 'vue';
import type { ISelectionRange } from '@alaarab/ogrid-vue';

export interface MarchingAntsOverlayProps {
  /** Ref to the positioned container that wraps the table (must have position: relative) */
  containerRef: Ref<HTMLElement | null>;
  /** Current selection range — solid green border */
  selectionRange: ISelectionRange | null;
  /** Copy range — animated dashed border */
  copyRange?: ISelectionRange | null;
  /** Cut range — animated dashed border */
  cutRange?: ISelectionRange | null;
  /** Column offset — 1 when checkbox column is present, else 0 */
  colOffset: number;
}

const props = withDefaults(defineProps<MarchingAntsOverlayProps>(), {
  copyRange: null,
  cutRange: null,
});

// Inject the @keyframes rule once into <head> (deduplicates across multiple OGrid instances)
function ensureKeyframes() {
  if (typeof document === 'undefined') return;
  if (document.getElementById('ogrid-marching-ants-keyframes')) return;
  const style = document.createElement('style');
  style.id = 'ogrid-marching-ants-keyframes';
  style.textContent =
    '@keyframes ogrid-marching-ants{to{stroke-dashoffset:-8}}';
  document.head.appendChild(style);
}

interface OverlayRect {
  top: number;
  left: number;
  width: number;
  height: number;
}

/** Measure the bounding rect of a range within a container. */
function measureRange(
  container: HTMLElement,
  range: ISelectionRange,
  colOffset: number
): OverlayRect | null {
  const startGlobalCol = range.startCol + colOffset;
  const endGlobalCol = range.endCol + colOffset;

  const topLeft = container.querySelector(
    `[data-row-index="${range.startRow}"][data-col-index="${startGlobalCol}"]`
  ) as HTMLElement | null;
  const bottomRight = container.querySelector(
    `[data-row-index="${range.endRow}"][data-col-index="${endGlobalCol}"]`
  ) as HTMLElement | null;

  if (!topLeft || !bottomRight) return null;

  const cRect = container.getBoundingClientRect();
  const tlRect = topLeft.getBoundingClientRect();
  const brRect = bottomRight.getBoundingClientRect();

  return {
    top: tlRect.top - cRect.top,
    left: tlRect.left - cRect.left,
    width: brRect.right - tlRect.left,
    height: brRect.bottom - tlRect.top,
  };
}

const selRect = ref<OverlayRect | null>(null);
const clipRect = ref<OverlayRect | null>(null);
let rafId = 0;
let ro: ResizeObserver | undefined;

const clipRange = computed(() => props.copyRange ?? props.cutRange);

const measureAll = () => {
  const container = props.containerRef.value;
  if (!container) {
    selRect.value = null;
    clipRect.value = null;
    return;
  }

  selRect.value = props.selectionRange ? measureRange(container, props.selectionRange, props.colOffset) : null;
  clipRect.value = clipRange.value ? measureRange(container, clipRange.value, props.colOffset) : null;
};

// Inject keyframes on mount
onMounted(() => {
  ensureKeyframes();
});

// Measure when any range changes; re-measure on resize
watch([() => props.selectionRange, clipRange, () => props.containerRef.value], () => {
  if (!props.selectionRange && !clipRange.value) {
    selRect.value = null;
    clipRect.value = null;
    return;
  }

  // Delay one frame so cells are rendered
  rafId = requestAnimationFrame(measureAll);

  const container = props.containerRef.value;
  if (container) {
    ro?.disconnect();
    ro = new ResizeObserver(measureAll);
    ro.observe(container);
  }
}, { immediate: true });

onUnmounted(() => {
  cancelAnimationFrame(rafId);
  ro?.disconnect();
});

const clipRangeMatchesSel = computed(() => {
  const sel = props.selectionRange;
  const clip = clipRange.value;
  return (
    sel != null &&
    clip != null &&
    sel.startRow === clip.startRow &&
    sel.startCol === clip.startCol &&
    sel.endRow === clip.endRow &&
    sel.endCol === clip.endCol
  );
});
</script>

<template>
  <div v-if="selRect || clipRect" style="position: relative">
    <!-- Selection range: solid green border (hidden when clipboard range overlaps) -->
    <svg
      v-if="selRect && !clipRangeMatchesSel"
      :style="{
        position: 'absolute',
        top: `${selRect.top}px`,
        left: `${selRect.left}px`,
        width: `${selRect.width}px`,
        height: `${selRect.height}px`,
        pointerEvents: 'none',
        zIndex: 4,
        overflow: 'visible',
      }"
      aria-hidden="true"
    >
      <rect
        :x="1"
        :y="1"
        :width="Math.max(0, selRect.width - 2)"
        :height="Math.max(0, selRect.height - 2)"
        fill="none"
        stroke="var(--ogrid-selection, #217346)"
        stroke-width="2"
      />
    </svg>

    <!-- Copy/Cut range: animated marching ants -->
    <svg
      v-if="clipRect"
      :style="{
        position: 'absolute',
        top: `${clipRect.top}px`,
        left: `${clipRect.left}px`,
        width: `${clipRect.width}px`,
        height: `${clipRect.height}px`,
        pointerEvents: 'none',
        zIndex: 5,
        overflow: 'visible',
      }"
      aria-hidden="true"
    >
      <rect
        :x="1"
        :y="1"
        :width="Math.max(0, clipRect.width - 2)"
        :height="Math.max(0, clipRect.height - 2)"
        fill="none"
        stroke="var(--ogrid-selection, #217346)"
        stroke-width="2"
        stroke-dasharray="4 4"
        style="animation: ogrid-marching-ants 0.5s linear infinite"
      />
    </svg>
  </div>
</template>

// packages/angular/src/components/marching-ants-overlay.component.ts
import { Component, input, effect, signal, DestroyRef, inject } from '@angular/core';
import { CommonModule } from '@angular/common';
import type { ISelectionRange } from '../types';

interface OverlayRect {
  top: number;
  left: number;
  width: number;
  height: number;
}

function measureRange(
  container: HTMLElement,
  range: ISelectionRange,
  colOffset: number,
): OverlayRect | null {
  const startGlobalCol = range.startCol + colOffset;
  const endGlobalCol = range.endCol + colOffset;

  const topLeft = container.querySelector(
    `[data-row-index="${range.startRow}"][data-col-index="${startGlobalCol}"]`,
  ) as HTMLElement | null;
  const bottomRight = container.querySelector(
    `[data-row-index="${range.endRow}"][data-col-index="${endGlobalCol}"]`,
  ) as HTMLElement | null;

  if (!topLeft || !bottomRight) return null;

  const cRect = container.getBoundingClientRect();
  const tlRect = topLeft.getBoundingClientRect();
  const brRect = bottomRight.getBoundingClientRect();

  return {
    top: tlRect.top - cRect.top,
    left: tlRect.left - cRect.left,
    width: brRect.right - tlRect.left,
    height: brRect.bottom - tlRect.top,
  };
}

function ensureKeyframes(): void {
  if (typeof document === 'undefined') return;
  if (document.getElementById('ogrid-marching-ants-keyframes')) return;
  const style = document.createElement('style');
  style.id = 'ogrid-marching-ants-keyframes';
  style.textContent = '@keyframes ogrid-marching-ants{to{stroke-dashoffset:-8}}';
  document.head.appendChild(style);
}

@Component({
  selector: 'ogrid-marching-ants-overlay',
  standalone: true,
  imports: [CommonModule],
  styles: [`
    .ogrid-marching-ants-svg { position: absolute; pointer-events: none; overflow: visible; }
    .ogrid-marching-ants-svg--selection { z-index: 4; }
    .ogrid-marching-ants-svg--clip { z-index: 5; }
  `],
  template: `
    @if (selRect() && !clipRangeMatchesSel()) {
      <svg
        class="ogrid-marching-ants-svg ogrid-marching-ants-svg--selection"
        [style.top.px]="selRect()!.top"
        [style.left.px]="selRect()!.left"
        [style.width.px]="selRect()!.width"
        [style.height.px]="selRect()!.height"
        aria-hidden="true"
      >
        <rect
          x="1" y="1"
          [attr.width]="max0(selRect()!.width - 2)"
          [attr.height]="max0(selRect()!.height - 2)"
          fill="none"
          stroke="var(--ogrid-selection, #217346)"
          stroke-width="2"
        />
      </svg>
    }
    @if (clipRect()) {
      <svg
        class="ogrid-marching-ants-svg ogrid-marching-ants-svg--clip"
        [style.top.px]="clipRect()!.top"
        [style.left.px]="clipRect()!.left"
        [style.width.px]="clipRect()!.width"
        [style.height.px]="clipRect()!.height"
        aria-hidden="true"
      >
        <rect
          x="1" y="1"
          [attr.width]="max0(clipRect()!.width - 2)"
          [attr.height]="max0(clipRect()!.height - 2)"
          fill="none"
          stroke="var(--ogrid-selection, #217346)"
          stroke-width="2"
          stroke-dasharray="4 4"
          style="animation: ogrid-marching-ants 0.5s linear infinite"
        />
      </svg>
    }
  `,
})
export class MarchingAntsOverlayComponent {
  private destroyRef = inject(DestroyRef);

  readonly containerEl = input.required<HTMLElement | null>();
  readonly selectionRange = input<ISelectionRange | null>(null);
  readonly copyRange = input<ISelectionRange | null>(null);
  readonly cutRange = input<ISelectionRange | null>(null);
  readonly colOffset = input<number>(0);
  readonly columnSizingVersion = input<number>(0);

  readonly selRect = signal<OverlayRect | null>(null);
  readonly clipRect = signal<OverlayRect | null>(null);

  private rafId = 0;
  private resizeObserver: ResizeObserver | null = null;

  constructor() {
    ensureKeyframes();

    effect(() => {
      const container = this.containerEl();
      const selRange = this.selectionRange();
      const clipRange = this.copyRange() ?? this.cutRange();
      const colOff = this.colOffset();
      void this.columnSizingVersion(); // Track column resize changes

      if (this.resizeObserver) {
        this.resizeObserver.disconnect();
        this.resizeObserver = null;
      }

      if (!selRange && !clipRange) {
        this.selRect.set(null);
        this.clipRect.set(null);
        return;
      }

      const measureAll = () => {
        if (!container) {
          this.selRect.set(null);
          this.clipRect.set(null);
          return;
        }
        this.selRect.set(selRange ? measureRange(container, selRange, colOff) : null);
        this.clipRect.set(clipRange ? measureRange(container, clipRange, colOff) : null);
      };

      if (this.rafId) cancelAnimationFrame(this.rafId);
      this.rafId = requestAnimationFrame(measureAll);

      if (container) {
        this.resizeObserver = new ResizeObserver(measureAll);
        this.resizeObserver.observe(container);
      }
    });

    this.destroyRef.onDestroy(() => {
      if (this.rafId) cancelAnimationFrame(this.rafId);
      if (this.resizeObserver) this.resizeObserver.disconnect();
    });
  }

  clipRangeMatchesSel(): boolean {
    const selRange = this.selectionRange();
    const clipRange = this.copyRange() ?? this.cutRange();
    return selRange != null && clipRange != null &&
      selRange.startRow === clipRange.startRow &&
      selRange.startCol === clipRange.startCol &&
      selRange.endRow === clipRange.endRow &&
      selRange.endCol === clipRange.endCol;
  }

  max0(n: number): number {
    return Math.max(0, n);
  }
}
