// packages/fluent/src/DataGridTable/StatusBar.tsx
import * as React from 'react';
import { getStatusBarParts } from '@alaarab/ogrid-core';
import styles from './DataGridTable.module.scss';

export interface StatusBarProps {
  totalCount: number;
  filteredCount?: number;
  selectedCount?: number;
  selectedCellCount?: number;
  aggregation?: {
    sum: number;
    avg: number;
    min: number;
    max: number;
    count: number;
  } | null;
  suppressRowCount?: boolean;
}

export function StatusBar(props: StatusBarProps): React.ReactElement {
  const parts = getStatusBarParts(props);
  return (
    <div className={styles.statusBar} role="status" aria-live="polite">
      {parts.map((p) => (
        <span key={p.key} className={styles.statusBarItem}>
          <span className={styles.statusBarLabel}>{p.label}</span>
          <span className={styles.statusBarValue}>{p.value.toLocaleString()}</span>
        </span>
      ))}
    </div>
  );
}

// packages/angular/src/components/status-bar.component.ts
import { Component, input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { getStatusBarParts } from '@alaarab/ogrid-core';

@Component({
  selector: 'ogrid-status-bar',
  standalone: true,
  imports: [CommonModule],
  template: `
    <div [class]="classNames()?.statusBar ?? ''" role="status" aria-live="polite">
      @for (part of parts(); track part.key) {
        <span [class]="classNames()?.statusBarItem ?? ''">
          <span [class]="classNames()?.statusBarLabel ?? ''">{{ part.label }}</span>
          <span [class]="classNames()?.statusBarValue ?? ''">{{ part.value.toLocaleString() }}</span>
        </span>
      }
    </div>
  `,
})
export class StatusBarComponent {
  readonly totalCount = input.required<number>();
  readonly filteredCount = input<number | undefined>(undefined);
  readonly selectedCount = input<number | undefined>(undefined);
  readonly selectedCellCount = input<number | undefined>(undefined);
  readonly aggregation = input<{
    sum: number;
    avg: number;
    min: number;
    max: number;
    count: number;
  } | null | undefined>(undefined);
  readonly suppressRowCount = input<boolean | undefined>(undefined);
  readonly classNames = input<{
    statusBar?: string;
    statusBarItem?: string;
    statusBarLabel?: string;
    statusBarValue?: string;
  } | undefined>(undefined);

  protected readonly parts = () => {
    return getStatusBarParts({
      totalCount: this.totalCount(),
      filteredCount: this.filteredCount(),
      selectedCount: this.selectedCount(),
      selectedCellCount: this.selectedCellCount(),
      aggregation: this.aggregation() ?? undefined,
      suppressRowCount: this.suppressRowCount(),
    });
  };
}
