// packages/angular/src/testing/dataGridTableTestFactory.ts
/**
 * Shared DataGridTable tests for Angular UI packages.
 * Each UI package calls createDataGridTableTests(DataGridTableComponent) to run these.
 *
 * Tests instantiate the component class directly and verify behavior through
 * the BaseDataGridTableComponent signals and DataGridStateService.
 */
import { fixtureRows, fixtureColumns, getRowId } from './fixtures';
import type { FixtureRow } from './fixtures';
import type { IOGridDataGridProps, IColumnDef, IColumnGroupDef, FilterValue, IStatusBarProps, ICellValueChangedEvent } from '../types';
import type { DataGridStateService } from '../services/datagrid-state.service';
import type { Signal, SimpleChanges } from '@angular/core';

function makeProps(overrides: Partial<IOGridDataGridProps<FixtureRow>> = {}): IOGridDataGridProps<FixtureRow> {
  return {
    items: fixtureRows.slice(0, 2),
    columns: fixtureColumns as IColumnDef<FixtureRow>[],
    getRowId,
    sortBy: undefined,
    sortDirection: 'asc',
    onColumnSort: jest.fn(),
    visibleColumns: new Set(['name', 'status']),
    filters: {},
    onFilterChange: jest.fn(),
    filterOptions: { status: ['Active', 'Closed'] },
    loadingFilterOptions: {},
    ...overrides,
  } as IOGridDataGridProps<FixtureRow>;
}

interface DataGridTableInstance {
  propsInput?: IOGridDataGridProps<FixtureRow>;
  itemsInput?: FixtureRow[];
  columns?: (IColumnDef<FixtureRow> | IColumnGroupDef<FixtureRow>)[];
  getRowIdInput?: (item: FixtureRow) => string | number;
  sortBy?: string;
  sortDirection?: 'asc' | 'desc';
  onColumnSort?: (columnKey: string) => void;
  visibleColumns?: Set<string>;
  filters?: Record<string, unknown>;
  onFilterChange?: (key: string, value: FilterValue | undefined) => void;
  filterOptions?: Record<string, string[]>;
  loadingFilterOptions?: Record<string, boolean>;
  isLoadingInput?: boolean;
  suppressHorizontalScroll?: boolean;
  stickyHeaderInput?: boolean;
  statusBar?: IStatusBarProps;
  emptyStateInput?: {
    onClearAll: () => void;
    hasActiveFilters: boolean;
    message?: string;
    render?: unknown;
  };
  editable?: boolean;
  onCellValueChanged?: (event: ICellValueChangedEvent<FixtureRow>) => void;
  cellSelection?: boolean;
  ngOnChanges?: (changes: SimpleChanges) => void;
  stateService: DataGridStateService<FixtureRow>;
  allowOverflowX: Signal<boolean>;
  stickyHeader: Signal<boolean>;
  items: Signal<FixtureRow[]>;
  getRowId: Signal<(item: FixtureRow) => string | number>;
  isLoading: Signal<boolean>;
  commitEdit: () => void;
  cancelEdit: () => void;
  onEditorKeydown: (event: KeyboardEvent) => void;
}

// Use unknown for the constructor since DataGridTableComponent is a generic class
// The instance will be cast to DataGridTableInstance after instantiation
export function createDataGridTableTests(DataGridTableComponent: new () => unknown): void {
  function createComponent(overrides: Partial<IOGridDataGridProps<FixtureRow>> = {}): DataGridTableInstance {
    const instance = new DataGridTableComponent() as DataGridTableInstance;
    const props = makeProps(overrides);

    // Set propsInput for Material/Radix (single-prop API via @Input setter)
    instance.propsInput = props;
    // Also set individual inputs for PrimeNG (individual-input API)
    instance.itemsInput = props.items;
    instance.columns = props.columns;
    instance.getRowIdInput = props.getRowId;
    instance.sortBy = props.sortBy;
    instance.sortDirection = props.sortDirection ?? 'asc';
    instance.onColumnSort = props.onColumnSort;
    instance.visibleColumns = props.visibleColumns;
    instance.filters = props.filters;
    instance.onFilterChange = props.onFilterChange;
    instance.filterOptions = props.filterOptions ?? {};
    instance.loadingFilterOptions = props.loadingFilterOptions ?? {};
    if (props.isLoading !== undefined) instance.isLoadingInput = props.isLoading;
    if (props.suppressHorizontalScroll !== undefined) instance.suppressHorizontalScroll = props.suppressHorizontalScroll;
    if (props.stickyHeader !== undefined) instance.stickyHeaderInput = props.stickyHeader;
    if (props.statusBar !== undefined) instance.statusBar = props.statusBar;
    if (props.emptyState !== undefined) instance.emptyStateInput = props.emptyState;
    if (props.editable !== undefined) instance.editable = props.editable;
    if (props.onCellValueChanged !== undefined) instance.onCellValueChanged = props.onCellValueChanged;
    if (props.cellSelection !== undefined) instance.cellSelection = props.cellSelection;
    // Trigger ngOnChanges for PrimeNG (rebuilds propsSignal from individual inputs)
    if (typeof instance.ngOnChanges === 'function') {
      instance.ngOnChanges({});
    }
    // Feed props into the state service
    instance.stateService.props.set(props);
    return instance;
  }

  it('instantiates correctly', () => {
    const comp = createComponent();
    expect(comp).toBeTruthy();
    expect(comp.stateService).toBeDefined();
  });

  it('has base class methods (commitEdit, cancelEdit, onEditorKeydown)', () => {
    const comp = createComponent();
    expect(typeof comp.commitEdit).toBe('function');
    expect(typeof comp.cancelEdit).toBe('function');
    expect(typeof comp.onEditorKeydown).toBe('function');
  });

  it('items computed returns correct items from props', () => {
    const comp = createComponent();
    expect(comp.items()).toEqual(fixtureRows.slice(0, 2));
  });

  it('getRowId computed returns the getRowId function', () => {
    const comp = createComponent();
    const fn = comp.getRowId();
    expect(fn(fixtureRows[0])).toBe('1');
  });

  it('isLoading defaults to false', () => {
    const comp = createComponent();
    expect(comp.isLoading()).toBe(false);
  });

  it('isLoading reflects props.isLoading', () => {
    const comp = createComponent({ isLoading: true });
    expect(comp.isLoading()).toBe(true);
  });

  it('state service computes visibleCols from props', () => {
    const comp = createComponent();
    const state = comp.stateService.getState();
    const visColIds = state.layout.visibleCols.map((c: IColumnDef<FixtureRow>) => c.columnId);
    expect(visColIds).toEqual(['name', 'status']);
  });

  it('visibleCols filters out hidden columns', () => {
    const comp = createComponent({ visibleColumns: new Set(['name']) });
    const state = comp.stateService.getState();
    const visColIds = state.layout.visibleCols.map((c: IColumnDef<FixtureRow>) => c.columnId);
    expect(visColIds).toEqual(['name']);
  });

  it('suppressHorizontalScroll is reflected', () => {
    const comp = createComponent({ suppressHorizontalScroll: true });
    expect(comp.allowOverflowX()).toBe(false);
  });

  it('statusBar computed returns config when statusBar is provided', () => {
    const comp = createComponent({ statusBar: { totalCount: 2, suppressRowCount: false } });
    const state = comp.stateService.getState();
    expect(state.viewModels.statusBarConfig).toBeTruthy();
  });

  it('statusBar is null when statusBar prop is not set', () => {
    const comp = createComponent();
    const state = comp.stateService.getState();
    expect(state.viewModels.statusBarConfig).toBeNull();
  });

  it('emptyState shows when items empty and emptyState provided', () => {
    const comp = createComponent({ items: [], emptyState: { hasActiveFilters: true, onClearAll: jest.fn() } });
    const state = comp.stateService.getState();
    expect(state.viewModels.showEmptyInGrid).toBe(true);
  });

  it('editable mode: state has onCellValueChanged when provided', () => {
    const onCellValueChanged = jest.fn();
    const comp = createComponent({ editable: true, onCellValueChanged });
    const state = comp.stateService.getState();
    expect(state.viewModels.cellDescriptorInput.editable).toBe(true);
    expect(state.viewModels.cellDescriptorInput.onCellValueChanged).toBeDefined();
  });

  it('headerFilterInput has correct structure', () => {
    const comp = createComponent();
    const state = comp.stateService.getState();
    const hfi = state.viewModels.headerFilterInput;
    expect(hfi.sortDirection).toBe('asc');
    expect(typeof hfi.onColumnSort).toBe('function');
    expect(hfi.filters).toEqual({});
    expect(typeof hfi.onFilterChange).toBe('function');
  });

  it('stickyHeader defaults to true', () => {
    const comp = createComponent();
    expect(comp.stickyHeader()).toBe(true);
  });

  it('stickyHeader=false is reflected in computed signal', () => {
    const comp = createComponent({ stickyHeader: false });
    expect(comp.stickyHeader()).toBe(false);
  });

  describe('onKeyDown intercept', () => {
    it('onKeyDown callback receives keyboard events from handleGridKeyDown', () => {
      const onKeyDown = jest.fn();
      const comp = createComponent({ onKeyDown, cellSelection: true });
      // Set active cell so key handling proceeds
      comp.stateService.setActiveCell({ rowIndex: 0, columnIndex: 0 });
      comp.stateService.setSelectionRange({ startRow: 0, startCol: 0, endRow: 0, endCol: 0 });
      const e = new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true });
      comp.stateService.handleGridKeyDown(e);
      expect(onKeyDown).toHaveBeenCalledWith(e);
    });

    it('preventDefault in onKeyDown suppresses grid default handling', () => {
      const onKeyDown = jest.fn((e: KeyboardEvent) => e.preventDefault());
      const comp = createComponent({ onKeyDown, cellSelection: true });
      comp.stateService.setActiveCell({ rowIndex: 0, columnIndex: 0 });
      comp.stateService.setSelectionRange({ startRow: 0, startCol: 0, endRow: 0, endCol: 0 });
      const initialActive = comp.stateService.getState().interaction.activeCell;
      const e = new KeyboardEvent('keydown', { key: 'ArrowDown', bubbles: true, cancelable: true });
      comp.stateService.handleGridKeyDown(e);
      // Active cell should not have changed since preventDefault was called
      expect(comp.stateService.getState().interaction.activeCell).toEqual(initialActive);
      expect(onKeyDown).toHaveBeenCalledWith(e);
    });
  });

  describe('aria-sort on sorted columns', () => {
    it('headerFilterInput reflects ascending sort direction', () => {
      const comp = createComponent({ sortBy: 'name', sortDirection: 'asc' });
      const state = comp.stateService.getState();
      expect(state.viewModels.headerFilterInput.sortBy).toBe('name');
      expect(state.viewModels.headerFilterInput.sortDirection).toBe('asc');
    });

    it('headerFilterInput reflects descending sort direction', () => {
      const comp = createComponent({ sortBy: 'status', sortDirection: 'desc' });
      const state = comp.stateService.getState();
      expect(state.viewModels.headerFilterInput.sortBy).toBe('status');
      expect(state.viewModels.headerFilterInput.sortDirection).toBe('desc');
    });

    it('headerFilterInput has undefined sortBy when no sort is active', () => {
      const comp = createComponent({ sortBy: undefined });
      const state = comp.stateService.getState();
      expect(state.viewModels.headerFilterInput.sortBy).toBeUndefined();
    });
  });

  describe('cell references: column letters', () => {
    it('showColumnLetters=true is threaded through props to state service', () => {
      const comp = createComponent({ showColumnLetters: true, showRowNumbers: true });
      const props = comp.stateService.props();
      expect(props?.showColumnLetters).toBe(true);
    });

    it('default (no showColumnLetters) does not set showColumnLetters in props', () => {
      const comp = createComponent();
      const props = comp.stateService.props();
      expect(props?.showColumnLetters).toBeFalsy();
    });

    it('showRowNumbers=true sets hasRowNumbersCol in layout state', () => {
      const comp = createComponent({ showRowNumbers: true });
      const state = comp.stateService.getState();
      expect(state.layout.hasRowNumbersCol).toBe(true);
    });

    it('default (no showRowNumbers) does not set hasRowNumbersCol', () => {
      const comp = createComponent();
      const state = comp.stateService.getState();
      expect(state.layout.hasRowNumbersCol).toBe(false);
    });

    it('showColumnLetters with showRowNumbers increases colOffset', () => {
      const comp = createComponent({ showColumnLetters: true, showRowNumbers: true });
      const state = comp.stateService.getState();
      // colOffset should account for the row numbers column
      expect(state.layout.colOffset).toBeGreaterThanOrEqual(1);
    });

    it('onActiveCellChange callback is threaded through props', () => {
      const onActiveCellChange = jest.fn();
      const comp = createComponent({ showColumnLetters: true, showRowNumbers: true, onActiveCellChange });
      const props = comp.stateService.props();
      expect(props?.onActiveCellChange).toBe(onActiveCellChange);
    });
  });

  describe('error handling in cell rendering', () => {
    it('onCellError callback is threaded through viewModels', () => {
      const onCellError = jest.fn();
      const comp = createComponent({ onCellError });
      const state = comp.stateService.getState();
      expect(state.viewModels.onCellError).toBe(onCellError);
    });

    it('onCellError is undefined when not provided', () => {
      const comp = createComponent();
      const state = comp.stateService.getState();
      expect(state.viewModels.onCellError).toBeUndefined();
    });
  });
}

// packages/react/src/testing/dataGridTableTestFactory.tsx
/**
 * Shared DataGridTable tests.
 * Each UI package calls createDataGridTableTests(DataGridTable) to run these.
 */
import * as React from 'react';
import { render, screen, fireEvent, waitFor, act } from '@testing-library/react';
import type { IColumnDef, UserLike, IOGridDataGridProps } from '../types';
import { fixtureRows, getRowId, type FixtureRow } from './fixtures';

export function createDataGridTableTests(DataGridTable: React.ComponentType<IOGridDataGridProps<FixtureRow>>): void {
  const twoColumnColumns: IColumnDef<FixtureRow>[] = [
    {
      columnId: 'name',
      name: 'Name',
      sortable: true,
      filterable: { type: 'text' },
      renderCell: (item) => <span data-testid="cell-name">{item.name}</span>,
    },
    {
      columnId: 'status',
      name: 'Status',
      sortable: true,
      filterable: { type: 'multiSelect', filterField: 'status' },
      renderCell: (item) => <span data-testid="cell-status">{item.status}</span>,
    },
  ];

  function renderTable(overrides: Record<string, unknown> = {}) {
    const defaultProps = {
      items: fixtureRows.slice(0, 2),
      columns: twoColumnColumns,
      getRowId,
      sortBy: undefined,
      sortDirection: 'asc',
      onColumnSort: jest.fn(),
      visibleColumns: new Set(['name', 'status']),
      filters: {},
      onFilterChange: jest.fn(),
      filterOptions: { status: ['Active', 'Closed'] },
      loadingFilterOptions: {},
    };
    return render(<DataGridTable {...defaultProps} {...overrides} />);
  }

  it('renders rows and cells for visible columns', () => {
    renderTable();
    expect(screen.getAllByTestId('cell-name').map((el) => el.textContent)).toEqual(['Alpha', 'Beta']);
    expect(screen.getAllByTestId('cell-status').map((el) => el.textContent)).toEqual(['Active', 'Closed']);
  });

  it('hides columns not in visibleColumns', () => {
    renderTable({ visibleColumns: new Set(['name']) });
    expect(screen.getAllByTestId('cell-name')).toHaveLength(2);
    expect(screen.queryByTestId('cell-status')).not.toBeInTheDocument();
  });

  it('sets aria-label when provided', () => {
    const { container } = renderTable({ 'aria-label': 'Projects grid' });
    const region = container.querySelector('[role="region"][aria-label="Projects grid"]');
    expect(region).toBeInTheDocument();
  });

  it('sets aria-labelledby when provided', () => {
    render(
      <>
        <h2 id="grid-heading">Projects</h2>
        <DataGridTable
          items={fixtureRows.slice(0, 2)}
          columns={twoColumnColumns}
          getRowId={getRowId}
          sortBy={undefined}
          sortDirection="asc"
          onColumnSort={jest.fn()}
          visibleColumns={new Set(['name', 'status'])}
          filters={{}}
          onFilterChange={jest.fn()}
          filterOptions={{}}
          loadingFilterOptions={{}}
          aria-labelledby="grid-heading"
        />
      </>
    );
    const region = screen.getByRole('region', { name: 'Projects' });
    expect(region).toHaveAttribute('aria-labelledby', 'grid-heading');
  });

  it('shows empty state when no items and emptyState provided', () => {
    const onClearAll = jest.fn();
    renderTable({
      items: [],
      emptyState: { hasActiveFilters: true, onClearAll },
    });
    expect(screen.getByText(/No results found/i)).toBeInTheDocument();
    const clearButton = screen.getByRole('button', { name: /clear all filters/i });
    fireEvent.click(clearButton);
    expect(onClearAll).toHaveBeenCalled();
  });

  it('wires text filter through onFilterChange with filterField override', () => {
    const onFilterChange = jest.fn();
    const textFilterColumns: IColumnDef<FixtureRow>[] = [
      {
        columnId: 'name',
        name: 'Name',
        sortable: false,
        filterable: { type: 'text', filterField: 'nameFilter' },
        renderCell: (item) => <span data-testid="cell-name">{item.name}</span>,
      },
    ];
    renderTable({ columns: textFilterColumns, onFilterChange });
    const filterButton = screen.getByRole('button', { name: /filter name/i });
    fireEvent.click(filterButton);
    const input = screen.getByPlaceholderText(/enter search term/i);
    fireEvent.change(input, { target: { value: 'Alpha' } });
    const applyButton = screen.getByRole('button', { name: /apply/i });
    fireEvent.click(applyButton);
    expect(onFilterChange).toHaveBeenCalledWith('nameFilter', { type: 'text', value: 'Alpha' });
  });

  it('wires multi-select filter through onFilterChange with filterField', () => {
    const onFilterChange = jest.fn();
    const statusColumns: IColumnDef<FixtureRow>[] = [
      {
        columnId: 'name',
        name: 'Name',
        sortable: false,
        filterable: { type: 'multiSelect', filterField: 'status' },
        renderCell: (item) => <span data-testid="cell-name">{item.name}</span>,
      },
    ];
    renderTable({
      columns: statusColumns,
      visibleColumns: new Set(['name']),
      onFilterChange,
      filterOptions: { status: ['Active', 'Closed'] },
    });
    const filterButton = screen.getByRole('button', { name: /filter name/i });
    fireEvent.click(filterButton);
    const selectAllButton = screen.getByRole('button', { name: /select all/i });
    fireEvent.click(selectAllButton);
    const applyButton = screen.getByRole('button', { name: /apply/i });
    fireEvent.click(applyButton);
    expect(onFilterChange).toHaveBeenCalledWith('status', { type: 'multiSelect', value: ['Active', 'Closed'] });
  });

  it('renders with editable columns and onCellValueChanged (editable smoke)', () => {
    const onCellValueChanged = jest.fn();
    const editableColumns: IColumnDef<FixtureRow>[] = [
      {
        columnId: 'name',
        name: 'Name',
        editable: true,
        cellEditor: 'text',
        renderCell: (item) => <span data-testid="cell-name">{item.name}</span>,
      },
      {
        columnId: 'status',
        name: 'Status',
        renderCell: (item) => <span data-testid="cell-status">{item.status}</span>,
      },
    ];
    renderTable({
      columns: editableColumns,
      visibleColumns: new Set(['name', 'status']),
      editable: true,
      onCellValueChanged,
    });
    expect(screen.getAllByTestId('cell-name').map((el) => el.textContent)).toEqual(['Alpha', 'Beta']);
    expect(onCellValueChanged).not.toHaveBeenCalled();
  });

  it('does not make cells editable when onCellValueChanged is not provided', () => {
    const editableColumns: IColumnDef<FixtureRow>[] = [
      {
        columnId: 'name',
        name: 'Name',
        editable: true,
        cellEditor: 'text',
        renderCell: (item) => <span data-testid="cell-name">{item.name}</span>,
      },
    ];
    renderTable({
      columns: editableColumns,
      visibleColumns: new Set(['name']),
      editable: true,
    });
    const nameCells = screen.getAllByTestId('cell-name');
    expect(nameCells[0]).toHaveTextContent('Alpha');
  });

  it('wires people filter: open, search, select user, calls onFilterChange', async () => {
    const alice: UserLike = { id: '1', displayName: 'Alice Johnson', email: 'alice@example.com' };
    const peopleSearch = jest.fn<Promise<UserLike[]>, [string]>().mockResolvedValue([alice]);
    const onFilterChange = jest.fn();
    const peopleColumns: IColumnDef<FixtureRow>[] = [
      { columnId: 'name', name: 'Name', sortable: false, renderCell: (item) => <span data-testid="cell-name">{item.name}</span> },
      { columnId: 'owner', name: 'Owner', sortable: false, filterable: { type: 'people', filterField: 'ownerEmail' }, renderCell: (item) => <span data-testid="cell-owner">{item.name}</span> },
    ];
    renderTable({
      columns: peopleColumns,
      visibleColumns: new Set(['name', 'owner']),
      filters: {},
      onFilterChange,
      filterOptions: {},
      loadingFilterOptions: {},
      peopleSearch,
    });
    const filterButton = screen.getByRole('button', { name: /filter owner/i });
    fireEvent.click(filterButton);
    const input = screen.getByPlaceholderText(/search for a person/i);
    fireEvent.change(input, { target: { value: 'ali' } });
    // Wait for the 300ms debounce to fire with real timers
    await act(async () => { await new Promise((r) => setTimeout(r, 350)); });
    await waitFor(() => { expect(peopleSearch).toHaveBeenCalledWith('ali'); });
    const suggestion = await screen.findByText('Alice Johnson');
    fireEvent.click(suggestion);
    expect(onFilterChange).toHaveBeenCalledWith('ownerEmail', { type: 'people', value: expect.objectContaining({ displayName: 'Alice Johnson', email: 'alice@example.com' }) });
  });

  it('type: numeric column renders cells correctly', () => {
    const numericColumns: IColumnDef<FixtureRow>[] = [
      {
        columnId: 'name',
        name: 'Name',
        renderCell: (item) => <span data-testid="cell-name">{item.name}</span>,
      },
      {
        columnId: 'status',
        name: 'Amount',
        type: 'numeric',
        renderCell: (item) => <span data-testid="cell-amount">{item.status}</span>,
      },
    ];
    const { container } = renderTable({
      columns: numericColumns,
      visibleColumns: new Set(['name', 'status']),
    });
    // Verify numeric column cells render
    const amountCells = container.querySelectorAll('[data-testid="cell-amount"]');
    expect(amountCells.length).toBe(2);
    expect(amountCells[0].textContent).toBe('Active');
    // Verify it's within a cell wrapper that has row/col index attributes
    const cellWrapper = amountCells[0].closest('[data-col-index]');
    expect(cellWrapper).toBeTruthy();
  });

  it('suppressHorizontalScroll prevents overflow-x auto', () => {
    const { container } = renderTable({ suppressHorizontalScroll: true });
    const region = container.querySelector('[role="region"]');
    expect(region).toBeTruthy();
    // suppressHorizontalScroll sets data-overflow-x="false" (CSS handles hiding)
    expect(region?.getAttribute('data-overflow-x')).toBe('false');
  });

  it('renders status bar when statusBar is true', () => {
    renderTable({ statusBar: true });
    const statusBar = screen.getByRole('status');
    expect(statusBar).toBeInTheDocument();
    expect(statusBar.textContent).toContain('Rows:');
  });

  it('left-pinned column renders with pinnedColumns prop', () => {
    const { container } = renderTable({ pinnedColumns: { name: 'left' } });
    // Pinned column still renders its cells
    const nameCells = container.querySelectorAll('td[data-column-id="name"]');
    expect(nameCells.length).toBeGreaterThan(0);
    // Header for pinned column is present
    const headerCells = container.querySelectorAll('th');
    const nameHeader = Array.from(headerCells).find((th) => th.textContent?.includes('Name'));
    expect(nameHeader).toBeTruthy();
  });

  it('right-pinned column renders with pinnedColumns prop', () => {
    const { container } = renderTable({ pinnedColumns: { status: 'right' } });
    const statusCells = container.querySelectorAll('td[data-column-id="status"]');
    expect(statusCells.length).toBeGreaterThan(0);
    const headerCells = container.querySelectorAll('th');
    const statusHeader = Array.from(headerCells).find((th) => th.textContent?.includes('Status'));
    expect(statusHeader).toBeTruthy();
  });

  it('multiple pinned columns render together', () => {
    const { container } = renderTable({ pinnedColumns: { name: 'left', status: 'right' } });
    expect(container.querySelectorAll('td[data-column-id="name"]').length).toBeGreaterThan(0);
    expect(container.querySelectorAll('td[data-column-id="status"]').length).toBeGreaterThan(0);
  });

  it('stickyHeader defaults to true', () => {
    const { container } = renderTable();
    const thead = container.querySelector('thead');
    expect(thead).toBeTruthy();
  });

  it('stickyHeader=false renders without error', () => {
    const { container } = renderTable({ stickyHeader: false });
    const thead = container.querySelector('thead');
    expect(thead).toBeTruthy();
  });

  it('sorted column header has aria-sort="ascending" when sortDirection is asc', () => {
    const { container } = renderTable({ sortBy: 'name', sortDirection: 'asc' });
    const sortedTh = container.querySelector('th[aria-sort="ascending"]');
    expect(sortedTh).toBeInTheDocument();
  });

  it('sorted column header has aria-sort="descending" when sortDirection is desc', () => {
    const { container } = renderTable({ sortBy: 'name', sortDirection: 'desc' });
    const sortedTh = container.querySelector('th[aria-sort="descending"]');
    expect(sortedTh).toBeInTheDocument();
  });

  it('unsorted columns do not have aria-sort attribute', () => {
    const { container } = renderTable({ sortBy: 'name', sortDirection: 'asc' });
    // status column is not sorted, should have no aria-sort
    const statusTh = container.querySelector('th[data-column-id="status"]');
    expect(statusTh).toBeInTheDocument();
    expect(statusTh?.getAttribute('aria-sort')).toBeNull();
  });

  it('changing sort column updates aria-sort attributes', () => {
    const { container, rerender } = renderTable({ sortBy: 'name', sortDirection: 'asc' });
    expect(container.querySelector('th[aria-sort="ascending"]')).toBeInTheDocument();
    rerender(
      <DataGridTable
        items={fixtureRows.slice(0, 2)}
        columns={twoColumnColumns}
        getRowId={getRowId}
        sortBy="status"
        sortDirection="desc"
        onColumnSort={jest.fn()}
        visibleColumns={new Set(['name', 'status'])}
        filters={{}}
        onFilterChange={jest.fn()}
        filterOptions={{ status: ['Active', 'Closed'] }}
        loadingFilterOptions={{}}
      />
    );
    expect(container.querySelector('th[aria-sort="descending"]')).toBeInTheDocument();
    const nameTh = container.querySelector('th[data-column-id="name"]');
    expect(nameTh?.getAttribute('aria-sort')).toBeNull();
  });

  it('onKeyDown callback receives keyboard events from the grid', () => {
    const onKeyDown = jest.fn();
    const { container } = renderTable({ onKeyDown });
    const grid = container.querySelector('[role="region"]') as HTMLElement;
    expect(grid).toBeTruthy();
    grid.focus();
    fireEvent.keyDown(grid, { key: 'ArrowDown' });
    expect(onKeyDown).toHaveBeenCalled();
    const event = onKeyDown.mock.calls[0][0] as React.KeyboardEvent;
    expect(event.key).toBe('ArrowDown');
  });

  it('onKeyDown calling event.preventDefault() suppresses grid default handling', async () => {
    const onKeyDown = jest.fn((e: React.KeyboardEvent) => { e.preventDefault(); });
    const { container } = renderTable({ onKeyDown, cellSelection: true });
    const grid = container.querySelector('[role="region"]') as HTMLElement;
    grid.focus();

    // Click a cell to establish selection
    const cells = container.querySelectorAll('[data-row-index][data-col-index]') as NodeListOf<HTMLElement>;
    const firstCell = Array.from(cells).find(
      (el) => !(el.closest('[role="columnheader"]') ?? el.closest('thead'))
    );
    if (firstCell) fireEvent.mouseDown(firstCell);

    const inRangeBefore = container.querySelectorAll('[data-in-range="true"]').length;
    // ArrowDown with preventDefault should not move selection
    fireEvent.keyDown(grid, { key: 'ArrowDown' });
    const inRangeAfter = container.querySelectorAll('[data-in-range="true"]').length;

    expect(onKeyDown).toHaveBeenCalled();
    expect(inRangeAfter).toBe(inRangeBefore);
  });

  it('onKeyDown not calling preventDefault allows grid to handle Escape normally', async () => {
    const onKeyDown = jest.fn(); // does NOT call preventDefault
    const { container } = renderTable({ onKeyDown, cellSelection: true });
    const grid = container.querySelector('[role="region"]') as HTMLElement;
    grid.focus();

    // Select a cell
    const cells = container.querySelectorAll('[data-row-index][data-col-index]') as NodeListOf<HTMLElement>;
    const firstCell = Array.from(cells).find(
      (el) => !(el.closest('[role="columnheader"]') ?? el.closest('thead'))
    );
    if (firstCell) fireEvent.mouseDown(firstCell);

    await waitFor(() => {
      expect(container.querySelector('[data-in-range="true"]')).toBeInTheDocument();
    });

    fireEvent.keyDown(grid, { key: 'Escape' });
    expect(onKeyDown).toHaveBeenCalled();
    // Grid default runs: Escape clears selection
    await waitFor(() => {
      expect(container.querySelectorAll('[data-in-range="true"]').length).toBe(0);
    });
  });

  describe('virtualScroll threshold', () => {
    const manyRows = Array.from({ length: 60 }, (_, i) => ({
      id: String(i + 1),
      name: `Row ${i + 1}`,
      status: i % 2 === 0 ? 'Active' : 'Closed',
    }));

    it('activates virtualization when item count exceeds threshold', () => {
      // 60 items, threshold=50 → should virtualize (render fewer rows than total)
      const { container } = renderTable({
        items: manyRows,
        virtualScroll: { enabled: true, rowHeight: 40, threshold: 50 },
        visibleColumns: new Set(['name', 'status']),
      });
      const cells = container.querySelectorAll('[data-testid="cell-name"]');
      expect(cells.length).toBeLessThan(manyRows.length);
    });

    it('does not virtualize when item count is below threshold', () => {
      // 60 items, threshold=100 → should NOT virtualize (all rows rendered)
      const { container } = renderTable({
        items: manyRows,
        virtualScroll: { enabled: true, rowHeight: 40, threshold: 100 },
        visibleColumns: new Set(['name', 'status']),
      });
      const cells = container.querySelectorAll('[data-testid="cell-name"]');
      expect(cells.length).toBe(manyRows.length);
    });

    it('accepts virtualScroll config with threshold without error', () => {
      expect(() => {
        renderTable({
          items: manyRows.slice(0, 5),
          virtualScroll: { enabled: true, rowHeight: 40, threshold: 50 },
          visibleColumns: new Set(['name', 'status']),
        });
      }).not.toThrow();
    });
  });

  // Cell references: column letter row
  it('does not render column letter row when showColumnLetters is false (default)', () => {
    const { container } = renderTable();
    const allTh = container.querySelectorAll('thead th');
    const letterCells = Array.from(allTh).filter(th => {
      const text = th.textContent?.trim();
      return text === 'A' || text === 'B';
    });
    expect(letterCells.length).toBe(0);
  });

  it('renders column letter row when showColumnLetters is true', () => {
    const { container } = renderTable({ showColumnLetters: true, showRowNumbers: true });
    const allTh = container.querySelectorAll('thead th');
    const letterCells = Array.from(allTh).filter(th => {
      const text = th.textContent?.trim();
      return text === 'A' || text === 'B';
    });
    expect(letterCells.length).toBeGreaterThanOrEqual(2);
  });

  it('column letter cells show correct letters for visible columns', () => {
    const { container } = renderTable({ showColumnLetters: true, showRowNumbers: true });
    const allTh = container.querySelectorAll('thead th');
    const letterTexts = Array.from(allTh)
      .map(th => th.textContent?.trim())
      .filter(text => text === 'A' || text === 'B');
    expect(letterTexts).toEqual(['A', 'B']);
  });
}
