// packages/angular-inputs/src/Rating/RatingEditor.ts
/**
 * RatingEditorComponent — Premium star rating cell editor for OGrid (Angular).
 *
 * Usage:
 *   import { RatingEditorComponent } from '@alaarab/ogrid-angular-inputs';
 *
 *   // In your column definitions:
 *   const columns = [{
 *     columnId: 'rating',
 *     cellEditor: RatingEditorComponent,
 *     cellEditorPopup: true,
 *     cellEditorParams: { maxStars: 5, allowHalf: false },
 *   }];
 *
 * Implements ICellEditorProps<T> via @Input() decorators — works with cellEditorPopup: true.
 */
import { Component, Input, signal, computed, ElementRef, ViewChild, afterNextRender } from '@angular/core';
import type { IColumnDef, CellEditorParams } from '@alaarab/ogrid-core';
import { clampRating, getStarFill, getRatingFromPosition, DEFAULT_MAX_STARS } from '@alaarab/ogrid-inputs';

// ── Styles (inline objects to avoid CSS file dependency — keeps package sideEffects: false) ──

const rootStyleObj: Record<string, string> = {
  'font-family': '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  'font-size': '13px',
  'background': 'var(--ogrid-bg, #fff)',
  'color': 'var(--ogrid-fg, #242424)',
  'border': '1px solid var(--ogrid-border, rgba(0,0,0,0.12))',
  'border-radius': '8px',
  'box-shadow': 'var(--ogrid-shadow, 0 4px 16px rgba(0,0,0,0.15))',
  'padding': '12px',
  'user-select': 'none',
  'min-width': '180px',
};

const starsRowStyleObj: Record<string, string> = {
  'display': 'flex',
  'align-items': 'center',
  'gap': '4px',
  'margin-bottom': '8px',
};

const starBtnStyleObj: Record<string, string> = {
  'background': 'none',
  'border': 'none',
  'cursor': 'pointer',
  'padding': '2px',
  'font-size': '24px',
  'line-height': '1',
  'color': 'inherit',
  'display': 'flex',
  'align-items': 'center',
};

const footerStyleObj: Record<string, string> = {
  'display': 'flex',
  'justify-content': 'space-between',
  'align-items': 'center',
  'margin-top': '4px',
  'padding-top': '8px',
  'border-top': '1px solid var(--ogrid-border, rgba(0,0,0,0.08))',
};

const labelStyleObj: Record<string, string> = {
  'font-size': '12px',
  'color': 'var(--ogrid-muted, #888)',
};

const clearBtnStyleObj: Record<string, string> = {
  'background': 'none',
  'border': 'none',
  'cursor': 'pointer',
  'padding': '4px 8px',
  'border-radius': '4px',
  'font-size': '12px',
  'color': 'var(--ogrid-accent, #0078d4)',
  'font-weight': '500',
};

// Helper to convert a Record<string,string> into an inline style string
function toStyleString(obj: Record<string, string>): string {
  return Object.entries(obj).map(([k, v]) => `${k}: ${v}`).join('; ');
}

@Component({
  selector: 'ogrid-rating-editor',
  standalone: true,
  template: `
    <div [style]="rootStyle" (mousedown)="$event.stopPropagation()">
      <!-- Stars row -->
      <div [style]="starsRowStyle">
        @for (star of starIndices(); track star) {
          <button
            #starBtn
            type="button"
            [style]="getStarBtnStyle(star)"
            (click)="handleStarClick($event, star)"
            (mouseenter)="hoverRating.set(star + 1)"
            (mouseleave)="hoverRating.set(null)"
            [attr.aria-label]="'Rate ' + (star + 1) + ' of ' + maxStars()"
            tabindex="-1"
          >{{ getStarChar(star) }}</button>
        }
      </div>

      <!-- Footer: label + clear -->
      <div [style]="footerStyle">
        <span [style]="labelStyle">{{ ratingLabel() }}</span>
        <button type="button" [style]="clearBtnStyle" (click)="handleClear()">Clear</button>
      </div>
    </div>
  `,
})
export class RatingEditorComponent {
  @Input() value: unknown;
  @Input() onValueChange!: (value: unknown) => void;
  @Input() onCommit!: () => void;
  @Input() onCancel!: () => void;
  @Input() item: unknown;
  @Input() column!: IColumnDef;
  @Input() cellEditorParams?: CellEditorParams;

  @ViewChild('starBtn') starBtnRef?: ElementRef<HTMLButtonElement>;

  // ── Signals ──

  currentRating = signal(0);
  hoverRating = signal<number | null>(null);

  // ── Computed ──

  maxStars = computed<number>(() => {
    const params = this.cellEditorParams as Record<string, unknown> | undefined;
    const m = params?.['maxStars'];
    return typeof m === 'number' && m > 0 ? m : DEFAULT_MAX_STARS;
  });

  allowHalf = computed<boolean>(() => {
    const params = this.cellEditorParams as Record<string, unknown> | undefined;
    return params?.['allowHalf'] === true;
  });

  starIndices = computed<number[]>(() =>
    Array.from({ length: this.maxStars() }, (_, i) => i)
  );

  displayRating = computed<number>(() =>
    this.hoverRating() ?? this.currentRating()
  );

  ratingLabel = computed<string>(() => {
    const r = this.currentRating();
    if (r === 0) return 'No rating';
    return `${r} / ${this.maxStars()}`;
  });

  // ── Style strings (pre-computed once for template binding) ──

  readonly rootStyle = toStyleString(rootStyleObj);
  readonly starsRowStyle = toStyleString(starsRowStyleObj);
  readonly footerStyle = toStyleString(footerStyleObj);
  readonly labelStyle = toStyleString(labelStyleObj);
  readonly clearBtnStyle = toStyleString(clearBtnStyleObj);

  constructor() {
    afterNextRender(() => {
      // Parse initial value
      if (this.value != null) {
        const num = Number(this.value);
        if (!isNaN(num)) {
          this.currentRating.set(clampRating(num, this.maxStars()));
        }
      }
    });
  }

  // ── Helpers ──

  getStarChar(starIndex: number): string {
    const fill = getStarFill(starIndex, this.displayRating(), this.allowHalf());
    if (fill === 'full') return '★';
    if (fill === 'half') return '⯨';
    return '☆';
  }

  getStarBtnStyle(starIndex: number): string {
    const fill = getStarFill(starIndex, this.displayRating(), this.allowHalf());
    const style: Record<string, string> = { ...starBtnStyleObj };
    if (fill !== 'empty') {
      style['color'] = 'var(--ogrid-star-color, #f5a623)';
    } else {
      style['color'] = 'var(--ogrid-muted, #ccc)';
    }
    return toStyleString(style);
  }

  // ── Interaction ──

  handleStarClick(event: MouseEvent, starIndex: number): void {
    const target = event.currentTarget as HTMLElement;
    const rect = target.getBoundingClientRect();
    const offsetX = event.clientX - rect.left;
    const rating = getRatingFromPosition(starIndex, offsetX, rect.width, this.allowHalf());
    const clamped = clampRating(rating, this.maxStars());
    this.currentRating.set(clamped);
    this.onValueChange(clamped);
    // Auto-commit on star selection
    setTimeout(() => this.onCommit(), 0);
  }

  handleClear(): void {
    this.currentRating.set(0);
    this.hoverRating.set(null);
    this.onValueChange(null);
    this.onCommit();
  }
}

// packages/react-inputs/src/Rating/RatingEditor.tsx
/**
 * RatingEditor  -  Premium star-rating cell editor for OGrid.
 *
 * Usage:
 *   import { RatingEditor } from '@alaarab/ogrid-react-inputs';
 *
 *   const columns = [{
 *     columnId: 'priority',
 *     cellEditor: RatingEditor,
 *     cellEditorPopup: true,
 *     cellEditorParams: { maxStars: 5, allowHalf: false },
 *   }];
 *
 * Implements ICellEditorProps<T>  -  works with cellEditorPopup: true.
 */
import * as React from 'react';
import type { ICellEditorProps } from '@alaarab/ogrid-core';
import {
  clampRating,
  getStarFill,
  getRatingFromPosition,
  DEFAULT_MAX_STARS,
} from '@alaarab/ogrid-inputs';

// ── Styles (inline to avoid CSS file dependency  -  keeps package sideEffects: false) ──

const rootStyle: React.CSSProperties = {
  fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
  fontSize: '13px',
  background: 'var(--ogrid-bg, #fff)',
  color: 'var(--ogrid-fg, #242424)',
  border: '1px solid var(--ogrid-border, rgba(0,0,0,0.12))',
  borderRadius: '8px',
  boxShadow: 'var(--ogrid-shadow, 0 4px 16px rgba(0,0,0,0.15))',
  padding: '12px',
  userSelect: 'none',
};

const starsRowStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: '2px',
  padding: '8px 0',
};

const starBtnStyle: React.CSSProperties = {
  background: 'none',
  border: 'none',
  cursor: 'pointer',
  padding: '2px',
  fontSize: '28px',
  lineHeight: 1,
  transition: 'transform 0.1s ease',
  color: 'inherit',
};

const labelStyle: React.CSSProperties = {
  fontSize: '12px',
  color: 'var(--ogrid-muted, #888)',
  padding: '4px 0 0',
};

const footerStyle: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'flex-start',
  marginTop: '8px',
  paddingTop: '8px',
  borderTop: '1px solid var(--ogrid-border, rgba(0,0,0,0.08))',
};

const footerBtnStyle: React.CSSProperties = {
  background: 'none',
  border: 'none',
  cursor: 'pointer',
  padding: '4px 8px',
  borderRadius: '4px',
  fontSize: '12px',
  color: 'var(--ogrid-accent, #0078d4)',
  fontWeight: 500,
};

// ── Component ──

export function RatingEditor<T>(props: ICellEditorProps<T>): React.ReactElement {
  const { value, onValueChange, onCommit, onCancel, cellEditorParams } = props;

  const maxStars = (cellEditorParams as Record<string, unknown> | undefined)?.maxStars as number | undefined ?? DEFAULT_MAX_STARS;
  const allowHalf = (cellEditorParams as Record<string, unknown> | undefined)?.allowHalf as boolean | undefined ?? false;

  const initialRating = React.useMemo(() => {
    if (value == null || value === '') return 0;
    const num = Number(value);
    return Number.isNaN(num) ? 0 : clampRating(num, maxStars);
  }, [value, maxStars]);

  const [rating, setRating] = React.useState(initialRating);
  const [hoverRating, setHoverRating] = React.useState<number | null>(null);
  const rootRef = React.useRef<HTMLDivElement>(null);

  const displayRating = hoverRating ?? rating;

  const handleStarClick = (starIndex: number, e: React.MouseEvent<HTMLButtonElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const offsetX = e.clientX - rect.left;
    const starWidth = rect.width;
    const newRating = getRatingFromPosition(starIndex, offsetX, starWidth, allowHalf);
    const clamped = clampRating(newRating, maxStars);
    setRating(clamped);
    onValueChange(clamped);
    // Auto-commit on click
    setTimeout(() => onCommit(), 0);
  };

  const handleStarHover = (starIndex: number, e: React.MouseEvent<HTMLButtonElement>) => {
    const rect = e.currentTarget.getBoundingClientRect();
    const offsetX = e.clientX - rect.left;
    const starWidth = rect.width;
    const hoverVal = getRatingFromPosition(starIndex, offsetX, starWidth, allowHalf);
    setHoverRating(clampRating(hoverVal, maxStars));
  };

  const handleMouseLeave = () => {
    setHoverRating(null);
  };

  const handleClear = () => {
    setRating(0);
    onValueChange('');
    onCommit();
  };

  // Focus root on mount
  React.useEffect(() => {
    rootRef.current?.focus();
  }, []);

  // Keyboard handling
  React.useEffect(() => {
    const handleKeyDown = (e: KeyboardEvent) => {
      if (e.key === 'Escape') {
        e.preventDefault();
        onCancel();
      } else if (e.key === 'Enter') {
        e.preventDefault();
        onCommit();
      } else if (e.key === 'ArrowRight' || e.key === 'ArrowUp') {
        e.preventDefault();
        const step = allowHalf ? 0.5 : 1;
        setRating((prev) => {
          const next = clampRating(prev + step, maxStars);
          onValueChange(next);
          return next;
        });
      } else if (e.key === 'ArrowLeft' || e.key === 'ArrowDown') {
        e.preventDefault();
        const step = allowHalf ? 0.5 : 1;
        setRating((prev) => {
          const next = clampRating(Math.max(0, prev - step), maxStars);
          onValueChange(next || '');
          return next;
        });
      }
    };
    const el = rootRef.current;
    if (el) {
      el.addEventListener('keydown', handleKeyDown);
      return () => el.removeEventListener('keydown', handleKeyDown);
    }
  }, [onCancel, onCommit, onValueChange, maxStars, allowHalf]);

  const renderStar = (starIndex: number) => {
    const fill = getStarFill(starIndex, displayRating, allowHalf);

    let starChar: string;
    let starColor: string;
    if (fill === 'full') {
      starChar = '\u2605'; // ★
      starColor = '#F59E0B';
    } else if (fill === 'half') {
      starChar = '\u2605'; // ★ with clip
      starColor = '#F59E0B';
    } else {
      starChar = '\u2606'; // ☆
      starColor = 'var(--ogrid-muted, #ccc)';
    }

    const style: React.CSSProperties = {
      ...starBtnStyle,
      color: starColor,
    };

    if (fill === 'half') {
      // Use a gradient mask to show half-filled star
      return (
        <button
          key={starIndex}
          type="button"
          style={style}
          onClick={(e) => handleStarClick(starIndex, e)}
          onMouseMove={(e) => handleStarHover(starIndex, e)}
          tabIndex={-1}
        >
          <span
            style={{
              background: `linear-gradient(90deg, #F59E0B 50%, var(--ogrid-muted, #ccc) 50%)`,
              WebkitBackgroundClip: 'text',
              WebkitTextFillColor: 'transparent',
              backgroundClip: 'text',
            }}
          >
            {'\u2605'}
          </span>
        </button>
      );
    }

    return (
      <button
        key={starIndex}
        type="button"
        style={style}
        onClick={(e) => handleStarClick(starIndex, e)}
        onMouseMove={(e) => handleStarHover(starIndex, e)}
        tabIndex={-1}
      >
        {starChar}
      </button>
    );
  };

  return (
    <div
      ref={rootRef}
      style={rootStyle}
      onMouseDown={(e) => e.stopPropagation()}
      tabIndex={0}
    >
      {/* Stars row */}
      <div style={starsRowStyle} onMouseLeave={handleMouseLeave}>
        {Array.from({ length: maxStars }, (_, i) => renderStar(i))}
      </div>

      {/* Rating label */}
      <div style={labelStyle}>
        {rating > 0 ? `${rating} / ${maxStars}` : 'No rating'}
      </div>

      {/* Footer */}
      <div style={footerStyle}>
        <button type="button" style={footerBtnStyle} onClick={handleClear}>
          Clear
        </button>
      </div>
    </div>
  );
}
