// packages/vue-radix/src/ColumnHeaderFilter/ColumnHeaderFilter.vue
<script setup lang="ts">
import { Popover, PopoverButton, PopoverPanel } from '@headlessui/vue';
import { useColumnHeaderFilterState, type UserLike, type ColumnFilterType, type IDateFilterValue } from '@alaarab/ogrid-vue';
import TextFilterPopover from './TextFilterPopover.vue';
import MultiSelectFilterPopover from './MultiSelectFilterPopover.vue';
import PeopleFilterPopover from './PeopleFilterPopover.vue';

export interface IColumnHeaderFilterProps {
  columnKey: string;
  columnName: string;
  filterType: ColumnFilterType;
  isSorted?: boolean;
  isSortedDescending?: boolean;
  onSort?: () => void;
  selectedValues?: string[];
  onFilterChange?: (values: string[]) => void;
  options?: string[];
  isLoadingOptions?: boolean;
  textValue?: string;
  onTextChange?: (value: string) => void;
  selectedUser?: UserLike;
  onUserChange?: (user: UserLike | undefined) => void;
  peopleSearch?: (query: string) => Promise<UserLike[]>;
  dateValue?: IDateFilterValue;
  onDateChange?: (value: IDateFilterValue | undefined) => void;
}

const props = withDefaults(defineProps<IColumnHeaderFilterProps>(), {
  isSorted: false,
  isSortedDescending: false,
  options: () => [],
  isLoadingOptions: false,
  textValue: '',
});

const state = useColumnHeaderFilterState({
  filterType: () => props.filterType,
  isSorted: () => props.isSorted,
  isSortedDescending: () => props.isSortedDescending,
  onSort: props.onSort,
  selectedValues: () => props.selectedValues,
  onFilterChange: props.onFilterChange,
  options: () => props.options,
  isLoadingOptions: () => props.isLoadingOptions,
  textValue: () => props.textValue,
  onTextChange: props.onTextChange,
  selectedUser: () => props.selectedUser,
  onUserChange: props.onUserChange,
  peopleSearch: props.peopleSearch,
  dateValue: () => props.dateValue,
  onDateChange: props.onDateChange,
});

const getSortIcon = () => {
  if (props.isSorted) {
    return props.isSortedDescending ? '\u2193' : '\u2191';
  }
  return '\u21C5';
};
</script>

<template>
  <div class="column-header" ref="state.headerRef">
    <div class="header-content">
      <span class="column-name" :title="columnName" data-header-label>
        {{ columnName }}
      </span>
    </div>
    <div class="header-actions">
      <button
        v-if="onSort"
        type="button"
        :class="['sort-icon', { 'sort-active': isSorted }]"
        @click="state.handlers.handleSortClick"
        :aria-label="`Sort by ${columnName}`"
        :title="isSorted ? (isSortedDescending ? 'Sorted descending' : 'Sorted ascending') : 'Sort'"
      >
        <span aria-hidden>{{ getSortIcon() }}</span>
      </button>

      <Popover v-if="filterType !== 'none'" v-slot="{ open }">
        <PopoverButton
          :class="[
            'filter-icon',
            { 'filter-active': state.hasActiveFilter },
            { 'filter-open': open },
          ]"
          @click="state.handlers.handleFilterIconClick"
          :aria-label="`Filter ${columnName}`"
          :title="`Filter ${columnName}`"
        >
          <span aria-hidden>▼</span>
          <span v-if="state.hasActiveFilter" class="filter-badge" />
        </PopoverButton>

        <transition
          enter-active-class="transition duration-200 ease-out"
          enter-from-class="opacity-0 translate-y-1"
          enter-to-class="opacity-100 translate-y-0"
          leave-active-class="transition duration-150 ease-in"
          leave-from-class="opacity-100 translate-y-0"
          leave-to-class="opacity-0 translate-y-1"
        >
          <PopoverPanel :ref="state.popoverRef" class="popover-content">
            <div class="popover-header">Filter: {{ columnName }}</div>

            <!-- Text Filter -->
            <TextFilterPopover
              v-if="filterType === 'text'"
              :value="state.tempTextValue"
              :onValueChange="state.setTempTextValue"
              :onApply="state.handlers.handleTextApply"
              :onClear="state.handlers.handleTextClear"
            />

            <!-- MultiSelect Filter -->
            <MultiSelectFilterPopover
              v-else-if="filterType === 'multiSelect'"
              :searchText="state.searchText"
              :onSearchChange="state.setSearchText"
              :options="options"
              :filteredOptions="state.filteredOptions"
              :selected="state.tempSelected"
              :onOptionToggle="state.handlers.handleCheckboxChange"
              :onSelectAll="state.handlers.handleSelectAll"
              :onClearSelection="state.handlers.handleClearSelection"
              :onApply="state.handlers.handleApplyMultiSelect"
              :isLoading="isLoadingOptions"
            />

            <!-- People Filter -->
            <PeopleFilterPopover
              v-else-if="filterType === 'people'"
              :selectedUser="selectedUser"
              :searchText="state.peopleSearchText"
              :onSearchChange="state.setPeopleSearchText"
              :suggestions="state.peopleSuggestions"
              :isLoading="state.isPeopleLoading"
              :onUserSelect="state.handlers.handleUserSelect"
              :onClearUser="state.handlers.handleClearUser"
              :inputRef="state.peopleInputRef"
            />

            <!-- Date Filter -->
            <div v-else-if="filterType === 'date'">
              <div style="padding: 8px 12px; display: flex; flex-direction: column; gap: 6px">
                <label style="display: flex; align-items: center; gap: 6px; font-size: 12px">
                  From:
                  <input
                    type="date"
                    :value="state.tempDateFrom"
                    @input="state.setTempDateFrom(($event.target as HTMLInputElement).value)"
                    style="flex: 1"
                  />
                </label>
                <label style="display: flex; align-items: center; gap: 6px; font-size: 12px">
                  To:
                  <input
                    type="date"
                    :value="state.tempDateTo"
                    @input="state.setTempDateTo(($event.target as HTMLInputElement).value)"
                    style="flex: 1"
                  />
                </label>
              </div>
              <div class="popover-actions">
                <button
                  class="clear-button"
                  @click="state.handlers.handleDateClear"
                  :disabled="!state.tempDateFrom && !state.tempDateTo"
                >
                  Clear
                </button>
                <button class="apply-button" @click="state.handlers.handleDateApply">
                  Apply
                </button>
              </div>
            </div>
          </PopoverPanel>
        </transition>
      </Popover>
    </div>
  </div>
</template>

<style scoped lang="scss">
@import './ColumnHeaderFilter.module.scss';
</style>

// packages/react-radix/src/ColumnHeaderFilter/ColumnHeaderFilter.tsx
import * as React from 'react';
import * as Popover from '@radix-ui/react-popover';
import type { UserLike, ColumnFilterType, IDateFilterValue } from '@alaarab/ogrid-react';
import { useColumnHeaderFilterState } from '@alaarab/ogrid-react';
import { TextFilterPopover } from './TextFilterPopover';
import { MultiSelectFilterPopover } from './MultiSelectFilterPopover';
import { PeopleFilterPopover } from './PeopleFilterPopover';
import styles from './ColumnHeaderFilter.module.scss';

export interface IColumnHeaderFilterProps {
  columnKey: string;
  columnName: string;
  filterType: ColumnFilterType;
  isSorted?: boolean;
  isSortedDescending?: boolean;
  onSort?: () => void;
  selectedValues?: string[];
  onFilterChange?: (values: string[]) => void;
  options?: string[];
  isLoadingOptions?: boolean;
  textValue?: string;
  onTextChange?: (value: string) => void;
  selectedUser?: UserLike;
  onUserChange?: (user: UserLike | undefined) => void;
  peopleSearch?: (query: string) => Promise<UserLike[]>;
  dateValue?: IDateFilterValue;
  onDateChange?: (value: IDateFilterValue | undefined) => void;
}

function SortIcon({ isSorted, isDesc }: { isSorted: boolean; isDesc: boolean }): React.ReactElement {
  if (isSorted) return <span aria-hidden>{isDesc ? '\u2193' : '\u2191'}</span>;
  return <span aria-hidden>{'\u21C5'}</span>;
}
function FilterIcon(): React.ReactElement {
  return <span aria-hidden>{'\u25BE'}</span>;
}

export const ColumnHeaderFilter: React.FC<IColumnHeaderFilterProps> = React.memo((props) => {
  const {
    columnName,
    filterType,
    isSorted = false,
    isSortedDescending = false,
    onSort,
    selectedValues,
    onFilterChange,
    options = [],
    isLoadingOptions = false,
    textValue = '',
    onTextChange,
    selectedUser,
    onUserChange,
    peopleSearch,
    dateValue,
    onDateChange,
  } = props;

  const state = useColumnHeaderFilterState({
    filterType,
    isSorted,
    isSortedDescending,
    onSort,
    selectedValues,
    onFilterChange,
    options,
    isLoadingOptions,
    textValue,
    onTextChange,
    selectedUser,
    onUserChange,
    peopleSearch,
    dateValue,
    onDateChange,
  });

  const {
    headerRef,
    popoverRef,
    peopleInputRef,
    isFilterOpen,
    setFilterOpen,
    tempSelected,
    tempTextValue,
    setTempTextValue,
    searchText,
    setSearchText,
    filteredOptions,
    peopleSuggestions,
    isPeopleLoading,
    peopleSearchText,
    setPeopleSearchText,
    hasActiveFilter,
    handlers,
  } = state;

  const safeOptions = options ?? [];

  const renderPopoverContent = (): React.ReactNode => {
    if (filterType === 'multiSelect') {
      return (
        <MultiSelectFilterPopover
          searchText={searchText}
          onSearchChange={setSearchText}
          options={safeOptions}
          filteredOptions={filteredOptions}
          selected={tempSelected}
          onOptionToggle={handlers.handleCheckboxChange}
          onSelectAll={handlers.handleSelectAll}
          onClearSelection={handlers.handleClearSelection}
          onApply={handlers.handleApplyMultiSelect}
          isLoading={isLoadingOptions}
        />
      );
    }
    if (filterType === 'text') {
      return (
        <TextFilterPopover
          value={tempTextValue}
          onValueChange={setTempTextValue}
          onApply={handlers.handleTextApply}
          onClear={handlers.handleTextClear}
        />
      );
    }
    if (filterType === 'people') {
      return (
        <PeopleFilterPopover
          selectedUser={selectedUser}
          searchText={peopleSearchText}
          onSearchChange={setPeopleSearchText}
          suggestions={peopleSuggestions}
          isLoading={isPeopleLoading}
          onUserSelect={handlers.handleUserSelect}
          onClearUser={handlers.handleClearUser}
          inputRef={peopleInputRef}
        />
      );
    }
    if (filterType === 'date') {
      return (
        <>
          <div style={{ padding: '8px 12px', display: 'flex', flexDirection: 'column', gap: 6 }}>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12 }}>
              From:
              <input type="date" value={state.tempDateFrom} onChange={(e) => state.setTempDateFrom(e.target.value)} style={{ flex: 1 }} />
            </label>
            <label style={{ display: 'flex', alignItems: 'center', gap: 6, fontSize: 12 }}>
              To:
              <input type="date" value={state.tempDateTo} onChange={(e) => state.setTempDateTo(e.target.value)} style={{ flex: 1 }} />
            </label>
          </div>
          <div className={styles.popoverActions}>
            <button className={styles.clearButton} onClick={handlers.handleDateClear} disabled={!state.tempDateFrom && !state.tempDateTo}>Clear</button>
            <button className={styles.applyButton} onClick={handlers.handleDateApply}>Apply</button>
          </div>
        </>
      );
    }
    return null;
  };

  return (
    <div className={styles.columnHeader} ref={headerRef as React.RefObject<HTMLDivElement>}>
      <div className={styles.headerContent}>
        <span className={styles.columnName} title={columnName} data-header-label>
          {columnName}
        </span>
      </div>
      <div className={styles.headerActions}>
        {onSort && (
          <button
            type="button"
            className={`${styles.sortIcon} ${isSorted ? styles.sortActive : ''}`}
            onClick={handlers.handleSortClick}
            aria-label={`Sort by ${columnName}`}
            title={isSorted ? (isSortedDescending ? 'Sorted descending' : 'Sorted ascending') : 'Sort'}
          >
            <SortIcon isSorted={isSorted} isDesc={isSortedDescending} />
          </button>
        )}
        {filterType !== 'none' && (
          <Popover.Root open={isFilterOpen} onOpenChange={setFilterOpen}>
            <Popover.Trigger asChild>
              <button
                type="button"
                className={`${styles.filterIcon} ${hasActiveFilter ? styles.filterActive : ''} ${isFilterOpen ? styles.filterOpen : ''}`}
                onClick={handlers.handleFilterIconClick}
                aria-label={`Filter ${columnName}`}
                title={`Filter ${columnName}`}
              >
                <FilterIcon />
                {hasActiveFilter && <span className={styles.filterBadge} />}
              </button>
            </Popover.Trigger>
            <Popover.Portal>
              <Popover.Content
                ref={popoverRef as React.RefObject<HTMLDivElement>}
                className={styles.popoverContent}
                sideOffset={4}
                align="start"
                onOpenAutoFocus={(e: Event) => e.preventDefault()}
              >
                <div className={styles.popoverHeader}>Filter: {columnName}</div>
                {renderPopoverContent()}
              </Popover.Content>
            </Popover.Portal>
          </Popover.Root>
        )}
      </div>
    </div>
  );
});

ColumnHeaderFilter.displayName = 'ColumnHeaderFilter';
