// packages/angular-material/src/ogrid/ogrid.component.ts
import { Component, ChangeDetectionStrategy, Input, signal, effect } from '@angular/core';
import {
  OGridService,
  OGridLayoutComponent,
} from '@alaarab/ogrid-angular';
import type { IOGridProps } from '@alaarab/ogrid-angular';
import { DataGridTableComponent } from '../datagrid-table/datagrid-table.component';
import { ColumnChooserComponent } from '../column-chooser/column-chooser.component';
import { PaginationControlsComponent } from '../pagination-controls/pagination-controls.component';

/**
 * Top-level OGrid component for Angular Material.
 * Standalone component — provides OGridService and renders OGridLayout with all sub-components.
 *
 * Uses @Input with signal setter for JIT compatibility (project builds with tsc, not ngc).
 * The effect() reactively configures the service when the input signal changes.
 */
@Component({
  selector: 'ogrid',
  standalone: true,
  changeDetection: ChangeDetectionStrategy.OnPush,
  imports: [
    OGridLayoutComponent,
    DataGridTableComponent,
    ColumnChooserComponent,
    PaginationControlsComponent,
  ],
  providers: [OGridService],
  template: `
    <ogrid-layout
      [className]="ogridService.className()"
      [sideBar]="ogridService.sideBarProps()"
      [hasToolbar]="showToolbar"
      [hasToolbarBelow]="false"
      [hasPagination]="true"
    >
      <ng-container toolbarEnd>
        @if (ogridService.columnChooserPlacement() === 'toolbar') {
          <ogrid-column-chooser
            [columns]="ogridService.columnChooser().columns"
            [visibleColumns]="ogridService.columnChooser().visibleColumns"
            (visibilityChange)="ogridService.columnChooser().onVisibilityChange($event.columnKey, $event.visible)"
          />
        }
      </ng-container>

      <ogrid-datagrid-table [props]="ogridService.dataGridProps()" />

      <ng-container pagination>
        <ogrid-pagination-controls
          [currentPage]="ogridService.pagination().page"
          [pageSize]="ogridService.pagination().pageSize"
          [totalCount]="ogridService.pagination().displayTotalCount"
          [pageSizeOptions]="ogridService.pagination().pageSizeOptions"
          [entityLabelPlural]="ogridService.pagination().entityLabelPlural"
          (pageChange)="ogridService.pagination().setPage($event)"
          (pageSizeChange)="onPageSizeChange($event)"
        />
      </ng-container>
    </ogrid-layout>
  `,
})
export class OGridComponent<T> {
  private readonly propsSignal = signal<IOGridProps<T> | undefined>(undefined);
  readonly ogridService: OGridService<T>;

  @Input({ required: true })
  set props(value: IOGridProps<T>) {
    this.propsSignal.set(value);
  }

  constructor() {
    this.ogridService = new OGridService<T>();
    effect(() => {
      const p = this.propsSignal();
      if (p) this.ogridService.configure(p);
    });
  }

  get showToolbar(): boolean {
    return this.ogridService.columnChooserPlacement() === 'toolbar' || this.ogridService.toolbar() != null;
  }

  onPageSizeChange(size: number): void {
    this.ogridService.pagination().setPageSize(size);
    this.ogridService.pagination().setPage(1);
  }
}

// packages/radix/src/OGrid/OGrid.tsx
import * as React from 'react';
import { forwardRef } from 'react';
import { DataGridTable } from '../DataGridTable/DataGridTable';
import type { IOGridDataGridProps } from '@alaarab/ogrid-core';
import { ColumnChooser } from '../ColumnChooser/ColumnChooser';
import { PaginationControls } from '../PaginationControls/PaginationControls';
import {
  useOGrid,
  OGridLayout,
  type IOGridProps,
  type IOGridApi,
} from '@alaarab/ogrid-core';

export type { IOGridProps } from '@alaarab/ogrid-core';

const OGridInner = forwardRef(function OGridInner<T>(
  props: IOGridProps<T>,
  ref: React.Ref<IOGridApi<T>>
): React.ReactElement {
  const { dataGridProps, pagination, columnChooser, layout } = useOGrid(props, ref);

  return (
    <OGridLayout
      className={layout.className}
      sideBar={layout.sideBarProps}
      toolbar={layout.toolbar}
      toolbarBelow={layout.toolbarBelow}
      toolbarEnd={
        columnChooser.placement === 'toolbar' ? (
          <ColumnChooser
            columns={columnChooser.columns}
            visibleColumns={columnChooser.visibleColumns}
            onVisibilityChange={columnChooser.onVisibilityChange}
          />
        ) : undefined
      }
      pagination={
        <PaginationControls
          currentPage={pagination.page}
          pageSize={pagination.pageSize}
          totalCount={pagination.displayTotalCount}
          onPageChange={pagination.setPage}
          onPageSizeChange={(size) => {
            pagination.setPageSize(size);
            pagination.setPage(1);
          }}
          pageSizeOptions={pagination.pageSizeOptions}
          entityLabelPlural={pagination.entityLabelPlural}
        />
      }
    >
      <DataGridTable<T> {...(dataGridProps as IOGridDataGridProps<T>)} />
    </OGridLayout>
  );
});

OGridInner.displayName = 'OGrid';

export const OGrid = React.memo(OGridInner) as typeof OGridInner;
