// packages/radix/src/DataGridTable/DataGridTable.tsx
import * as React from 'react';
import { useCallback, useRef } from 'react';
import { createPortal } from 'react-dom';
import * as Popover from '@radix-ui/react-popover';
import * as Checkbox from '@radix-ui/react-checkbox';
import { ColumnHeaderFilter } from '../ColumnHeaderFilter';
import { InlineCellEditor } from './InlineCellEditor';
import { StatusBar } from './StatusBar';
import { GridContextMenu } from './GridContextMenu';
import type {
  IColumnDef,
  ICellEditorProps,
  IOGridDataGridProps,
} from '@alaarab/ogrid-core';
import {
  useDataGridState,
  useColumnResize,
  getHeaderFilterConfig,
  getCellRenderDescriptor,
  buildHeaderRows,
  MarchingAntsOverlay,
  resolveCellDisplayContent,
  resolveCellStyle,
  buildInlineEditorProps,
  buildPopoverEditorProps,
  getCellInteractionProps,
} from '@alaarab/ogrid-core';
import styles from './DataGridTable.module.scss';

/** @deprecated Use IOGridDataGridProps from @alaarab/ogrid-core for new code. */
export type IDataGridTableProps<T> = IOGridDataGridProps<T>;

function DataGridTableInner<T>(props: IOGridDataGridProps<T>): React.ReactElement {
  const wrapperRef = useRef<HTMLDivElement>(null);
  const tableContainerRef = useRef<HTMLDivElement>(null);
  const state = useDataGridState({ props, wrapperRef });
  const lastMouseShiftRef = useRef(false);

  const { layout, rowSelection: rowSel, editing, interaction, contextMenu: ctxMenu, viewModels } = state;
  const { visibleCols, totalColCount, hasCheckboxCol, colOffset, containerWidth, minTableWidth, desiredTableWidth, columnSizingOverrides, setColumnSizingOverrides } = layout;
  const { selectedRowIds, updateSelection, handleRowCheckboxChange, handleSelectAll, allSelected, someSelected } = rowSel;
  const { setEditingCell, pendingEditorValue, setPendingEditorValue, commitCellEdit, cancelPopoverEdit, popoverAnchorEl, setPopoverAnchorEl } = editing;
  const { setActiveCell, handleCellMouseDown, handleSelectAllCells, selectionRange, hasCellSelection, handleGridKeyDown, handleFillHandleMouseDown, handleCopy, handleCut, handlePaste, cutRange, copyRange, canUndo, canRedo, onUndo, onRedo } = interaction;
  const { menuPosition, handleCellContextMenu, closeContextMenu } = ctxMenu;
  const { headerFilterInput, cellDescriptorInput, statusBarConfig, showEmptyInGrid } = viewModels;

  const {
    items,
    columns,
    getRowId,
    emptyState,
    layoutMode = 'fill',
    rowSelection = 'none',
    freezeRows,
    freezeCols,
    suppressHorizontalScroll,
    isLoading = false,
    loadingMessage = 'Loading\u2026',
    'aria-label': ariaLabel,
    'aria-labelledby': ariaLabelledBy,
    visibleColumns,
  } = props;

  const headerRows = buildHeaderRows(columns, visibleColumns);

  const allowOverflowX = !suppressHorizontalScroll && containerWidth > 0 && (minTableWidth > containerWidth || desiredTableWidth > containerWidth);
  const fitToContent = layoutMode === 'content';

  const { handleResizeStart, getColumnWidth } = useColumnResize<T>({
    columnSizingOverrides,
    setColumnSizingOverrides,
  });

  const editCallbacks = React.useMemo(() => ({ commitCellEdit, setEditingCell, setPendingEditorValue, cancelPopoverEdit }), [commitCellEdit, setEditingCell, setPendingEditorValue, cancelPopoverEdit]);
  const interactionHandlers = React.useMemo(() => ({ handleCellMouseDown, setActiveCell, setEditingCell, handleCellContextMenu }), [handleCellMouseDown, setActiveCell, setEditingCell, handleCellContextMenu]);

  const renderCellContent = useCallback(
    (item: T, col: IColumnDef<T>, rowIndex: number, colIdx: number): React.ReactNode => {
      const descriptor = getCellRenderDescriptor(item, col, rowIndex, colIdx, cellDescriptorInput);

      if (descriptor.mode === 'editing-inline') {
        return <InlineCellEditor<T> {...buildInlineEditorProps(item, col, descriptor, editCallbacks)} />;
      }

      if (descriptor.mode === 'editing-popover' && typeof col.cellEditor === 'function') {
        const editorProps = buildPopoverEditorProps(item, col, descriptor, pendingEditorValue, editCallbacks);
        const CustomEditor = col.cellEditor as React.ComponentType<ICellEditorProps<T>>;
        return (
          <Popover.Root open={!!popoverAnchorEl} onOpenChange={(open: boolean) => { if (!open) cancelPopoverEdit(); }}>
            <Popover.Anchor asChild>
              <div ref={(el) => el && setPopoverAnchorEl(el)} style={{ minHeight: '100%', minWidth: 40 }} aria-hidden />
            </Popover.Anchor>
            <Popover.Portal>
              <Popover.Content sideOffset={4} onOpenAutoFocus={(e: Event) => e.preventDefault()}>
                <CustomEditor {...editorProps} />
              </Popover.Content>
            </Popover.Portal>
          </Popover.Root>
        );
      }

      const content = resolveCellDisplayContent(col, item, descriptor.displayValue);
      const cellStyle = resolveCellStyle(col, item);
      const styledContent = cellStyle ? <span style={cellStyle}>{content}</span> : content;

      const cellClassNames = [
        styles.cellContent,
        descriptor.isActive && !descriptor.isInRange ? styles.activeCellContent : '',
        descriptor.isInRange ? styles.cellInRange : '',
        descriptor.isInCutRange ? styles.cellCut : '',
        descriptor.isInCopyRange ? styles.cellCopied : '',
      ].filter(Boolean).join(' ');

      const interactionProps = getCellInteractionProps(descriptor, col.columnId, interactionHandlers);

      return (
        <div
          className={cellClassNames}
          {...interactionProps}
          style={descriptor.canEditAny ? { cursor: 'cell' } : undefined}
        >
          {styledContent}
          {descriptor.canEditAny && descriptor.isSelectionEndCell && (
            <div
              className={styles.fillHandle}
              onMouseDown={handleFillHandleMouseDown}
              aria-label="Fill handle"
            />
          )}
        </div>
      );
    },
    [cellDescriptorInput, pendingEditorValue, popoverAnchorEl, editCallbacks, interactionHandlers, handleFillHandleMouseDown, setPopoverAnchorEl, cancelPopoverEdit]
  );

  return (
    <div
      ref={wrapperRef}
      tabIndex={0}
      onMouseDown={(e) => { lastMouseShiftRef.current = e.shiftKey; }}
      className={`${styles.tableWrapper} ${rowSelection !== 'none' ? styles.selectableGrid : ''}`}
      role="region"
      aria-label={ariaLabel ?? (ariaLabelledBy ? undefined : 'Data grid')}
      aria-labelledby={ariaLabelledBy}
      data-empty={showEmptyInGrid ? 'true' : undefined}
      data-column-count={totalColCount}
      data-freeze-rows={freezeRows != null && freezeRows >= 1 ? freezeRows : undefined}
      data-freeze-cols={freezeCols != null && freezeCols >= 1 ? freezeCols : undefined}
      data-overflow-x={allowOverflowX ? 'true' : 'false'}
      data-container-width={containerWidth}
      data-min-table-width={Math.round(minTableWidth)}
      data-has-selection={rowSelection !== 'none' ? 'true' : undefined}
      onContextMenu={(e) => { e.preventDefault(); }}
      onKeyDown={handleGridKeyDown}
      style={{
        ['--data-table-column-count' as string]: totalColCount,
        ['--data-table-width' as string]: showEmptyInGrid ? '100%' : allowOverflowX ? 'fit-content' : fitToContent ? 'fit-content' : '100%',
        ['--data-table-min-width' as string]: showEmptyInGrid ? '100%' : allowOverflowX ? 'max-content' : fitToContent ? 'max-content' : '100%',
        ['--data-table-total-min-width' as string]: `${minTableWidth}px`,
      } as React.CSSProperties}
    >
      {isLoading && items.length > 0 && (
        <div className={styles.loadingOverlay} aria-live="polite">
          <div className={styles.loadingOverlayContent}>
            <div className={styles.spinner} />
            <span className={styles.loadingOverlayText}>{loadingMessage}</span>
          </div>
        </div>
      )}
      <div className={styles.tableScrollContent}>
        <div className={isLoading && items.length > 0 ? styles.loadingDimmed : undefined}>
          <div className={styles.tableWidthAnchor} ref={tableContainerRef}>
              <table className={styles.dataTable}>
                <thead
                  className={styles.stickyHeader}
                >
                  {headerRows.map((row, rowIdx) => (
                    <tr key={rowIdx}>
                      {/* Checkbox header: show in last row (leaf row) */}
                      {rowIdx === headerRows.length - 1 && hasCheckboxCol && (
                        <th className={styles.selectionHeaderCell} scope="col" rowSpan={1}>
                          <div className={styles.selectionHeaderCellInner}>
                            <Checkbox.Root
                              className={styles.rowCheckbox}
                              checked={allSelected ? true : someSelected ? 'indeterminate' : false}
                              onCheckedChange={(c: boolean | 'indeterminate') => handleSelectAll(!!c)}
                              aria-label="Select all rows"
                            >
                              <Checkbox.Indicator className={styles.rowCheckboxIndicator}>
                                {someSelected && !allSelected ? '–' : '✓'}
                              </Checkbox.Indicator>
                            </Checkbox.Root>
                          </div>
                        </th>
                      )}
                      {/* Empty placeholder for checkbox alignment in non-leaf rows */}
                      {rowIdx === 0 && rowIdx < headerRows.length - 1 && hasCheckboxCol && (
                        <th rowSpan={headerRows.length - 1} />
                      )}
                      {row.map((cell, cellIdx) => {
                        if (cell.isGroup) {
                          return (
                            <th key={cellIdx} colSpan={cell.colSpan} className={styles.groupHeaderCell} scope="colgroup">
                              {cell.label}
                            </th>
                          );
                        }
                        // Leaf cell
                        const col = cell.columnDef!;
                        const colIdx = visibleCols.indexOf(col);
                        const isFreezeCol =
                          freezeCols != null && freezeCols >= 1 && colIdx < freezeCols;
                        const isPinnedLeft = col.pinned === 'left';
                        const isPinnedRight = col.pinned === 'right';
                        const columnWidth = getColumnWidth(col);
                        const hasExplicitWidth = !!(columnSizingOverrides[col.columnId] || col.idealWidth != null || col.defaultWidth != null);
                        const leafRowSpan = headerRows.length > 1 && rowIdx < headerRows.length - 1
                          ? headerRows.length - rowIdx
                          : undefined;
                        return (
                          <th
                            key={col.columnId}
                            scope="col"
                            data-column-id={col.columnId}
                            rowSpan={leafRowSpan}
                            className={[
                              isFreezeCol ? styles.freezeCol : '',
                              isFreezeCol && colIdx === 0 ? styles.freezeColFirst : '',
                              isPinnedLeft ? styles.pinnedColLeft : '',
                              isPinnedRight ? styles.pinnedColRight : '',
                            ].filter(Boolean).join(' ')}
                            style={{
                              minWidth: col.minWidth ?? 80,
                              width: hasExplicitWidth ? columnWidth : undefined,
                              maxWidth: hasExplicitWidth ? columnWidth : undefined,
                            }}
                          >
                            <ColumnHeaderFilter {...getHeaderFilterConfig(col, headerFilterInput)} />
                            <div
                              className={styles.resizeHandle}
                              onMouseDown={(e) => handleResizeStart(e, col)}
                              aria-label={`Resize ${col.name}`}
                            />
                          </th>
                        );
                      })}
                    </tr>
                  ))}
                </thead>
                {!showEmptyInGrid && (
                  <tbody>
                    {items.map((item, rowIndex) => {
                      const rowIdStr = getRowId(item);
                      const isSelected = selectedRowIds.has(rowIdStr);
                      return (
                        <tr
                          key={rowIdStr}
                          className={isSelected ? styles.selectedRow : ''}
                          onClick={() => {
                            if (rowSelection === 'single') {
                              const id = getRowId(item);
                              updateSelection(selectedRowIds.has(id) ? new Set() : new Set([id]));
                            }
                          }}
                        >
                          {hasCheckboxCol && (
                            <td className={styles.selectionCell}>
                              <div
                                className={styles.selectionCellInner}
                                data-row-index={rowIndex}
                                data-col-index={0}
                                onClick={(e) => e.stopPropagation()}
                              >
                                <Checkbox.Root
                                  className={styles.rowCheckbox}
                                  checked={selectedRowIds.has(rowIdStr)}
                                  onCheckedChange={(c: boolean | 'indeterminate') => handleRowCheckboxChange(rowIdStr, !!c, rowIndex, lastMouseShiftRef.current)}
                                  aria-label={`Select row ${rowIndex + 1}`}
                                >
                                  <Checkbox.Indicator className={styles.rowCheckboxIndicator}>✓</Checkbox.Indicator>
                                </Checkbox.Root>
                              </div>
                            </td>
                          )}
                          {visibleCols.map((col, colIdx) => {
                            const isFreezeCol =
                              freezeCols != null && freezeCols >= 1 && colIdx < freezeCols;
                            const isPinnedLeft = col.pinned === 'left';
                            const isPinnedRight = col.pinned === 'right';
                            const columnWidth = getColumnWidth(col);
                            const hasExplicitWidth = !!(columnSizingOverrides[col.columnId] || col.idealWidth != null || col.defaultWidth != null);
                            return (
                              <td
                                key={col.columnId}
                                className={[
                                  isFreezeCol ? styles.freezeCol : '',
                                  isFreezeCol && colIdx === 0 ? styles.freezeColFirst : '',
                                  isPinnedLeft ? styles.pinnedColLeft : '',
                                  isPinnedRight ? styles.pinnedColRight : '',
                                ].filter(Boolean).join(' ')}
                                style={{
                                  minWidth: col.minWidth ?? 80,
                                  width: hasExplicitWidth ? columnWidth : undefined,
                                  maxWidth: hasExplicitWidth ? columnWidth : undefined,
                                  textAlign: col.type === 'numeric' ? 'right' : col.type === 'boolean' ? 'center' : undefined,
                                }}
                              >
                                {renderCellContent(item, col, rowIndex, colIdx)}
                              </td>
                            );
                          })}
                        </tr>
                      );
                    })}
                  </tbody>
                )}
              </table>
              <MarchingAntsOverlay
                containerRef={tableContainerRef}
                selectionRange={selectionRange}
                copyRange={copyRange}
                cutRange={cutRange}
                colOffset={colOffset}
              />
              {showEmptyInGrid && emptyState && (
                <div className={styles.emptyStateInGrid}>
                  <div>
                    {emptyState.render ? (
                      emptyState.render()
                    ) : (
                      <>
                        <div className={styles.emptyStateInGridTitle}>No results found</div>
                        <div className={styles.emptyStateInGridMessage}>
                          {emptyState.message != null ? (
                            emptyState.message
                          ) : emptyState.hasActiveFilters ? (
                            <>
                              No items match your current filters. Try adjusting your search or{' '}
                              <button type="button" className={styles.emptyStateInGridLink} onClick={emptyState.onClearAll}>
                                clear all filters
                              </button>{' '}
                              to see all items.
                            </>
                          ) : (
                            'There are no items available at this time.'
                          )}
                        </div>
                      </>
                    )}
                  </div>
                </div>
              )}
            </div>
          </div>
        {statusBarConfig && (
          <StatusBar
            totalCount={statusBarConfig.totalCount}
            filteredCount={statusBarConfig.filteredCount}
            selectedCount={statusBarConfig.selectedCount ?? selectedRowIds.size}
            selectedCellCount={selectionRange ? (Math.abs(selectionRange.endRow - selectionRange.startRow) + 1) * (Math.abs(selectionRange.endCol - selectionRange.startCol) + 1) : undefined}
            aggregation={statusBarConfig.aggregation}
            suppressRowCount={statusBarConfig.suppressRowCount}
          />
        )}
      </div>

      {menuPosition &&
        createPortal(
          <GridContextMenu
            x={menuPosition.x}
            y={menuPosition.y}
            hasSelection={hasCellSelection}
            canUndo={canUndo}
            canRedo={canRedo}
            onUndo={onUndo ?? (() => {})}
            onRedo={onRedo ?? (() => {})}
            onCopy={handleCopy}
            onCut={handleCut}
            onPaste={() => void handlePaste()}
            onSelectAll={handleSelectAllCells}
            onClose={closeContextMenu}
          />,
          document.body
        )}
    </div>
  );
}

export const DataGridTable = React.memo(DataGridTableInner) as typeof DataGridTableInner;

// packages/angular-radix/src/datagrid-table/datagrid-table.component.ts
import {
  Component, input, ElementRef, viewChild,
  ChangeDetectionStrategy,
} from '@angular/core';
import {
  BaseDataGridTableComponent,
  DataGridStateService,
  StatusBarComponent,
  GridContextMenuComponent,
  MarchingAntsOverlayComponent,
  EmptyStateComponent,
} from '@alaarab/ogrid-angular';
import type {
  IOGridDataGridProps,
} from '@alaarab/ogrid-angular';
import { ColumnHeaderFilterComponent } from '../column-header-filter/column-header-filter.component';

/**
 * DataGridTable component for Angular Radix using native HTML table.
 * Standalone component with lightweight styling and CSS variables.
 */
@Component({
  selector: 'ogrid-datagrid-table',
  standalone: true,
  imports: [ColumnHeaderFilterComponent, StatusBarComponent, GridContextMenuComponent, MarchingAntsOverlayComponent, EmptyStateComponent],
  providers: [DataGridStateService],
  changeDetection: ChangeDetectionStrategy.OnPush,
  styleUrl: './datagrid-table.component.scss',
  template: `
    <div class="ogrid-datagrid-root">
      <div
        #wrapperEl
        class="ogrid-datagrid-wrapper"
        [class.ogrid-datagrid-wrapper--fit]="layoutModeFit()"
        [class.ogrid-datagrid-wrapper--overflow-x]="allowOverflowX()"
        tabindex="0"
        role="region"
        [attr.aria-label]="ariaLabel()"
        [attr.aria-labelledby]="ariaLabelledBy()"
        (mousedown)="onWrapperMouseDown($event)"
        (keydown)="onGridKeyDown($event)"
        (contextmenu)="$event.preventDefault()"
        [attr.data-overflow-x]="allowOverflowX() ? 'true' : 'false'"
      >
        <div class="ogrid-datagrid-scroll-wrapper">
          <div [style.minWidth.px]="allowOverflowX() ? minTableWidth() : undefined">
            <div [class.ogrid-datagrid-table-wrapper--loading]="isLoading() && items().length > 0" #tableContainerEl>
              <table class="ogrid-datagrid-table" [style.minWidth.px]="minTableWidth()"
                [attr.data-freeze-rows]="freezeRows()"
                [attr.data-freeze-cols]="freezeCols()"
              >
                <thead class="ogrid-datagrid-thead">
                  @for (row of headerRows(); track $index; let rowIdx = $index) {
                    <tr class="ogrid-datagrid-header-row">
                      @if (rowIdx === headerRows().length - 1 && hasCheckboxCol()) {
                        <th class="ogrid-datagrid-th ogrid-datagrid-checkbox-col" [attr.rowSpan]="headerRows().length > 1 ? 1 : null">
                          <div class="ogrid-datagrid-checkbox-wrapper">
                            <input
                              type="checkbox"
                              [checked]="allSelected()"
                              [indeterminate]="someSelected()"
                              (change)="onSelectAllChange($event)"
                              aria-label="Select all rows"
                            />
                          </div>
                        </th>
                      }
                      @if (rowIdx === 0 && rowIdx < headerRows().length - 1 && hasCheckboxCol()) {
                        <th [attr.rowSpan]="headerRows().length - 1" class="ogrid-datagrid-th ogrid-datagrid-checkbox-spacer"></th>
                      }
                      @for (cell of row; track $index; let cellIdx = $index) {
                        @if (cell.isGroup) {
                          <th [attr.colSpan]="cell.colSpan" scope="colgroup" class="ogrid-datagrid-th ogrid-datagrid-group-header">
                            {{ cell.label }}
                          </th>
                        } @else {
                          @let col = asColumnDef(cell.columnDef);
                          @let colIdx = visibleColIndex(col);
                          @let isFreezeCol = freezeCols() != null && (freezeCols() ?? 0) >= 1 && colIdx < (freezeCols() ?? 0);
                          @let colW = getColumnWidth(col);
                          <th scope="col"
                            class="ogrid-datagrid-th"
                            [class.ogrid-datagrid-th--pinned-left]="col.pinned === 'left' || (isFreezeCol && colIdx === 0)"
                            [class.ogrid-datagrid-th--pinned-right]="col.pinned === 'right'"
                            [attr.rowSpan]="headerRows().length > 1 ? headerRows().length - rowIdx : null"
                            [attr.data-column-id]="col.columnId"
                            [style.minWidth.px]="col.minWidth ?? 80"
                            [style.width.px]="colW"
                            [style.maxWidth.px]="colW"
                            [class.ogrid-datagrid-th--reorderable]="!columnReorderService.isDragging()"
                            [class.ogrid-datagrid-th--dragging]="columnReorderService.isDragging()"
                            (mousedown)="onHeaderMouseDown(col.columnId, $event)"
                          >
                            <column-header-filter
                              [columnKey]="col.columnId"
                              [columnName]="col.name"
                              [filterType]="getFilterConfig(col).filterType"
                              [isSorted]="getFilterConfig(col).isSorted"
                              [isSortedDescending]="getFilterConfig(col).isSortedDescending"
                              [onSort]="getFilterConfig(col).onSort"
                              [selectedValues]="getFilterConfig(col).selectedValues"
                              [onFilterChange]="getFilterConfig(col).onFilterChange"
                              [options]="getFilterConfig(col).options"
                              [isLoadingOptions]="getFilterConfig(col).isLoadingOptions ?? false"
                              [textValue]="getFilterConfig(col).textValue ?? ''"
                              [onTextChange]="getFilterConfig(col).onTextChange"
                              [selectedUser]="getFilterConfig(col).selectedUser"
                              [onUserChange]="getFilterConfig(col).onUserChange"
                              [peopleSearch]="getFilterConfig(col).peopleSearch"
                              [dateValue]="getFilterConfig(col).dateValue"
                              [onDateChange]="getFilterConfig(col).onDateChange"
                            />
                            <div class="ogrid-datagrid-resize-handle" (mousedown)="onResizeStart($event, col)"></div>
                          </th>
                        }
                      }
                    </tr>
                  }
                </thead>
                @if (!showEmptyInGrid()) {
                  <tbody>
                    @for (item of items(); track getRowId()(item); let rowIndex = $index) {
                      @let rowId = getRowId()(item);
                      @let isSelected = selectedRowIds().has(rowId);
                      <tr
                        class="ogrid-datagrid-row"
                        [class.ogrid-datagrid-row--selected]="isSelected"
                        [attr.data-row-id]="rowId"
                        (click)="onRowClick($event, rowId)"
                      >
                        @if (hasCheckboxCol()) {
                          <td class="ogrid-datagrid-td ogrid-datagrid-checkbox-col">
                            <div
                              class="ogrid-datagrid-checkbox-wrapper"
                              [attr.data-row-index]="rowIndex"
                              [attr.data-col-index]="0"
                              (click)="$event.stopPropagation()"
                            >
                              <input
                                type="checkbox"
                                [checked]="isSelected"
                                (change)="onRowCheckboxChange(rowId, $event, rowIndex)"
                                [attr.aria-label]="'Select row ' + (rowIndex + 1)"
                              />
                            </div>
                          </td>
                        }
                        @for (colLayout of columnLayouts(); track colLayout.col.columnId; let colIdx = $index) {
                          <td
                            class="ogrid-datagrid-td"
                            [class.ogrid-datagrid-td--pinned-left]="colLayout.pinnedLeft"
                            [class.ogrid-datagrid-td--pinned-right]="colLayout.pinnedRight"
                            [style.minWidth.px]="colLayout.minWidth"
                            [style.width.px]="colLayout.width"
                            [style.maxWidth.px]="colLayout.width"
                          >
                            @let descriptor = getCellDescriptor(item, colLayout.col, rowIndex, colIdx);
                            @if (descriptor.mode === 'editing-inline') {
                              <div class="ogrid-datagrid-cell ogrid-datagrid-cell--editing">
                                @switch (descriptor.editorType) {
                                  @case ('checkbox') {
                                    <input
                                      type="checkbox"
                                      [checked]="!!descriptor.value"
                                      (change)="commitEdit(item, colLayout.col.columnId, descriptor.value, ($event.target as HTMLInputElement).checked, rowIndex, descriptor.globalColIndex)"
                                      (keydown)="$event.key === 'Escape' && cancelEdit()"
                                    />
                                  }
                                  @case ('select') {
                                    <select
                                      class="ogrid-datagrid-editor-select"
                                      [value]="descriptor.value != null ? '' + descriptor.value : ''"
                                      (change)="commitEdit(item, colLayout.col.columnId, descriptor.value, ($event.target as HTMLSelectElement).value, rowIndex, descriptor.globalColIndex)"
                                      (keydown)="$event.key === 'Escape' && cancelEdit()"
                                    >
                                      @for (v of getSelectValues(colLayout.col); track v) {
                                        <option [value]="v">{{ v }}</option>
                                      }
                                    </select>
                                  }
                                  @case ('date') {
                                    <input
                                      type="date"
                                      class="ogrid-datagrid-editor-input"
                                      [value]="formatDateForInput(descriptor.value)"
                                      (change)="commitEdit(item, colLayout.col.columnId, descriptor.value, ($event.target as HTMLInputElement).value, rowIndex, descriptor.globalColIndex)"
                                      (keydown)="onEditorKeydown($event, item, colLayout.col.columnId, descriptor.value, rowIndex, descriptor.globalColIndex)"
                                    />
                                  }
                                  @default {
                                    <input
                                      type="text"
                                      class="ogrid-datagrid-editor-input"
                                      [value]="descriptor.value != null ? '' + descriptor.value : ''"
                                      (keydown)="onEditorKeydown($event, item, colLayout.col.columnId, descriptor.value, rowIndex, descriptor.globalColIndex)"
                                    />
                                  }
                                }
                              </div>
                            } @else {
                              @let content = resolveCellContent(colLayout.col, item, descriptor.displayValue);
                              @let cellStyle = resolveCellStyleFn(colLayout.col, item);
                              <div
                                class="ogrid-datagrid-cell"
                                [class.ogrid-datagrid-cell--active]="descriptor.isActive && !descriptor.isInRange"
                                [class.ogrid-datagrid-cell--in-range]="descriptor.isInRange"
                                [class.ogrid-datagrid-cell--in-cut-range]="descriptor.isInCutRange"
                                [class.ogrid-datagrid-cell--editable]="descriptor.canEditAny"
                                [class.ogrid-datagrid-cell--numeric]="colLayout.col.type === 'numeric'"
                                [class.ogrid-datagrid-cell--boolean]="colLayout.col.type === 'boolean'"
                                [attr.data-row-index]="rowIndex"
                                [attr.data-col-index]="descriptor.globalColIndex"
                                [attr.data-in-range]="descriptor.isInRange ? 'true' : null"
                                [attr.tabindex]="descriptor.isActive ? 0 : -1"
                                (mousedown)="onCellMouseDown($event, rowIndex, descriptor.globalColIndex)"
                                (click)="onCellClick(rowIndex, descriptor.globalColIndex)"
                                (contextmenu)="onCellContextMenu($event)"
                                (dblclick)="descriptor.canEditAny ? onCellDblClick(descriptor.rowId, colLayout.col.columnId) : null"
                                [attr.role]="descriptor.canEditAny ? 'button' : null"
                                [style]="cellStyle ?? undefined"
                              >
                                {{ content }}
                                @if (descriptor.canEditAny && descriptor.isSelectionEndCell) {
                                  <div
                                    class="ogrid-datagrid-fill-handle"
                                    (mousedown)="onFillHandleMouseDown($event)"
                                    aria-label="Fill handle"
                                  ></div>
                                }
                              </div>
                            }
                          </td>
                        }
                      </tr>
                    }
                  </tbody>
                }
              </table>

              <ogrid-marching-ants-overlay
                [containerEl]="tableContainerEl()"
                [selectionRange]="state().interaction.selectionRange"
                [copyRange]="state().interaction.copyRange"
                [cutRange]="state().interaction.cutRange"
                [colOffset]="state().layout.colOffset"
                [columnSizingVersion]="columnSizingVersion()"
              ></ogrid-marching-ants-overlay>

              @if (showEmptyInGrid() && emptyState()) {
                <div class="ogrid-datagrid-empty">
                  <div class="ogrid-datagrid-empty__title">No results found</div>
                  <div class="ogrid-datagrid-empty__message">
                    @if (emptyState()!.message != null) {
                      {{ emptyState()!.message }}
                    } @else if (emptyState()!.hasActiveFilters) {
                      No items match your current filters. Try adjusting your search or
                      <button class="ogrid-datagrid-empty__clear" (click)="emptyState()!.onClearAll?.()">clear all filters</button>
                      to see all items.
                    } @else {
                      There are no items available at this time.
                    }
                  </div>
                </div>
              }
            </div>
          </div>
        </div>

        @if (columnReorderService.isDragging() && columnReorderService.dropIndicatorX() !== null) {
          <div class="ogrid-datagrid-drop-indicator" [style.left.px]="columnReorderService.dropIndicatorX()"></div>
        }

        @if (menuPosition()) {
          <div
            class="ogrid-datagrid-context-menu-overlay"
            (click)="closeContextMenu()"
            (contextmenu)="$event.preventDefault(); closeContextMenu()"
          >
            <ogrid-grid-context-menu
              [x]="menuPosition()!.x"
              [y]="menuPosition()!.y"
              [hasSelection]="hasCellSelection()"
              [canUndo]="canUndo()"
              [canRedo]="canRedo()"
              (undoAction)="onUndo()"
              (redoAction)="onRedo()"
              (copyAction)="handleCopy()"
              (cutAction)="handleCut()"
              (pasteAction)="handlePaste()"
              (selectAllAction)="handleSelectAllCells()"
              (closeAction)="closeContextMenu()"
            />
          </div>
        }
      </div>

      @if (statusBarConfig()) {
        <ogrid-status-bar
          [totalCount]="statusBarConfig()!.totalCount"
          [filteredCount]="statusBarConfig()!.filteredCount"
          [selectedCount]="statusBarConfig()!.selectedCount ?? selectedRowIds().size"
          [selectedCellCount]="selectionCellCount()"
          [aggregation]="statusBarConfig()!.aggregation"
          [suppressRowCount]="statusBarConfig()!.suppressRowCount"
        />
      }

      @if (isLoading()) {
        <div class="ogrid-datagrid-loading-overlay">
          <div class="ogrid-datagrid-loading-inner">
            <div class="ogrid-datagrid-spinner"></div>
            <span>{{ loadingMessage() }}</span>
          </div>
        </div>
      }
    </div>
  `,
})
export class DataGridTableComponent<T> extends BaseDataGridTableComponent<T> {
  readonly propsInput = input.required<IOGridDataGridProps<T>>({ alias: 'props' });

  private readonly wrapperRef = viewChild<ElementRef<HTMLElement>>('wrapperEl');
  private readonly tableContainerRef = viewChild<ElementRef<HTMLElement>>('tableContainerEl');

  constructor() {
    super();
    this.initBase();
  }

  protected getProps(): IOGridDataGridProps<T> | undefined {
    return this.propsInput();
  }

  protected getWrapperRef(): ElementRef<HTMLElement> | undefined {
    return this.wrapperRef();
  }

  protected getTableContainerRef(): ElementRef<HTMLElement> | undefined {
    return this.tableContainerRef();
  }
}
