// packages/angular/src/components/ogrid-layout.component.ts
import { Component, Input } from '@angular/core';
import { CommonModule } from '@angular/common';
import { SideBarComponent } from './sidebar.component';
import type { SideBarProps } from './sidebar.component';
import { GRID_BORDER_RADIUS } from '@alaarab/ogrid-core';

@Component({
  selector: 'ogrid-layout',
  standalone: true,
  imports: [CommonModule, SideBarComponent],
  styles: [`
    .ogrid-layout-root { display: flex; flex-direction: column; height: 100%; }
    .ogrid-layout-container {
      border: 1px solid var(--ogrid-border, #e0e0e0);
      overflow: hidden; display: flex; flex-direction: column;
      flex: 1; min-height: 0; background: var(--ogrid-bg, #fff);
    }
    .ogrid-layout-toolbar {
      display: flex; justify-content: space-between; align-items: center;
      padding: 6px 12px; background: var(--ogrid-header-bg, #f5f5f5);
      gap: 8px; flex-wrap: wrap; min-height: 0;
    }
    .ogrid-layout-toolbar--has-below { border-bottom: none; }
    .ogrid-layout-toolbar--no-below { border-bottom: 1px solid var(--ogrid-border, #e0e0e0); }
    .ogrid-layout-toolbar-left { display: flex; align-items: center; gap: 8px; }
    .ogrid-layout-toolbar-right { display: flex; align-items: center; gap: 8px; }
    .ogrid-layout-toolbar-below {
      border-bottom: 1px solid var(--ogrid-border, #e0e0e0);
      padding: 6px 12px; background: var(--ogrid-header-bg, #f5f5f5);
    }
    .ogrid-layout-grid-area { width: 100%; min-width: 0; min-height: 0; flex: 1; display: flex; }
    .ogrid-layout-grid-content { flex: 1; min-width: 0; min-height: 0; display: flex; flex-direction: column; }
    .ogrid-layout-footer {
      border-top: 1px solid var(--ogrid-border, #e0e0e0);
      background: var(--ogrid-header-bg, #f5f5f5); padding: 6px 12px;
    }
  `],
  template: `
    <div [class]="(className ?? '') + ' ogrid-layout-root'">
      <div class="ogrid-layout-container" [style.border-radius.px]="borderRadius">
        <!-- Toolbar strip -->
        @if (hasToolbar) {
          <div
            class="ogrid-layout-toolbar"
            [class.ogrid-layout-toolbar--has-below]="hasToolbarBelow"
            [class.ogrid-layout-toolbar--no-below]="!hasToolbarBelow"
          >
            <div class="ogrid-layout-toolbar-left">
              <ng-content select="[toolbar]"></ng-content>
            </div>
            <div class="ogrid-layout-toolbar-right">
              <ng-content select="[toolbarEnd]"></ng-content>
            </div>
          </div>
        }

        <!-- Secondary toolbar row -->
        @if (hasToolbarBelow) {
          <div class="ogrid-layout-toolbar-below">
            <ng-content select="[toolbarBelow]"></ng-content>
          </div>
        }

        <!-- Grid area -->
        @if (sideBar) {
          <div class="ogrid-layout-grid-area">
            @if (sideBar?.position === 'left') {
              <ogrid-sidebar [sideBarProps]="sideBar"></ogrid-sidebar>
            }
            <div class="ogrid-layout-grid-content">
              <ng-content></ng-content>
            </div>
            @if (sideBar?.position !== 'left') {
              <ogrid-sidebar [sideBarProps]="sideBar"></ogrid-sidebar>
            }
          </div>
        } @else {
          <div class="ogrid-layout-grid-content">
            <ng-content></ng-content>
          </div>
        }

        <!-- Footer strip (pagination) -->
        @if (hasPagination) {
          <div class="ogrid-layout-footer">
            <ng-content select="[pagination]"></ng-content>
          </div>
        }
      </div>
    </div>
  `,
})
export class OGridLayoutComponent {
  @Input() className?: string;
  @Input() hasToolbar = false;
  @Input() hasToolbarBelow = false;
  @Input() hasPagination = false;
  @Input() sideBar: SideBarProps | null = null;

  readonly borderRadius = GRID_BORDER_RADIUS;
}

// packages/core/src/components/OGridLayout.tsx
/**
 * Single layout structure for OGrid: unified bordered container with
 * toolbar strip, grid area (optionally with sidebar), and footer strip.
 * UI packages supply Container (Fluent/Radix: div, Material: Box).
 */

import * as React from 'react';
import { SideBar } from './SideBar';
import type { SideBarProps } from './SideBar';

export interface OGridLayoutProps {
  /** Root container element (default: 'div'). Material can pass Box. */
  containerComponent?: React.ElementType;
  /** Extra props for the root container (e.g. sx for MUI Box). */
  containerProps?: Record<string, unknown>;
  className?: string;
  /** Custom toolbar content (left-aligned in toolbar strip). */
  toolbar?: React.ReactNode;
  /** Built-in toolbar items rendered on the right side (column chooser, etc.). */
  toolbarEnd?: React.ReactNode;
  /** Secondary toolbar row below the primary toolbar (e.g. active filter chips). Full width. */
  toolbarBelow?: React.ReactNode;
  /** Grid content (DataGridTable). */
  children: React.ReactNode;
  /** Pagination controls (rendered in footer strip inside the bordered container). */
  pagination?: React.ReactNode;
  /** Side bar props. When provided, renders SideBar alongside the grid. */
  sideBar?: SideBarProps | null;
}

// Stable style objects (avoid re-creating on every render)
const borderedContainerStyle: React.CSSProperties = {
  border: '1px solid var(--ogrid-border, #e0e0e0)',
  borderRadius: 6,
  overflow: 'hidden',
  display: 'flex',
  flexDirection: 'column',
  flex: 1,
  minHeight: 0,
  background: 'var(--ogrid-bg, #fff)',
};

const toolbarStripStyle: React.CSSProperties = {
  display: 'flex',
  justifyContent: 'space-between',
  alignItems: 'center',
  padding: '6px 12px',
  borderBottom: '1px solid var(--ogrid-border, #e0e0e0)',
  background: 'var(--ogrid-header-bg, #f5f5f5)',
  gap: 8,
  flexWrap: 'wrap',
  minHeight: 0,
};

const toolbarSectionStyle: React.CSSProperties = {
  display: 'flex',
  alignItems: 'center',
  gap: 8,
};

const toolbarBelowStyle: React.CSSProperties = {
  padding: '6px 12px',
  borderBottom: '1px solid var(--ogrid-border, #e0e0e0)',
  background: 'var(--ogrid-header-bg, #f5f5f5)',
};

const footerStripStyle: React.CSSProperties = {
  borderTop: '1px solid var(--ogrid-border, #e0e0e0)',
  background: 'var(--ogrid-header-bg, #f5f5f5)',
  padding: '6px 12px',
};

const gridAreaFlexStyle: React.CSSProperties = {
  width: '100%',
  minWidth: 0,
  minHeight: 0,
  flex: 1,
  display: 'flex',
};

const gridAreaSoloStyle: React.CSSProperties = {
  width: '100%',
  minWidth: 0,
  minHeight: 0,
  flex: 1,
  display: 'flex',
  flexDirection: 'column',
};

const gridChildStyle: React.CSSProperties = {
  flex: 1,
  minWidth: 0,
  minHeight: 0,
  display: 'flex',
  flexDirection: 'column',
};

/**
 * Renders OGrid layout as a unified bordered container:
 *   ┌────────────────────────────────────┐
 *   │ [toolbar strip]                    │
 *   ├────────────────────────────────────┤
 *   │ [sidebar]? [grid]                  │
 *   ├────────────────────────────────────┤
 *   │ [footer strip / pagination]        │
 *   └────────────────────────────────────┘
 */
export function OGridLayout(props: OGridLayoutProps): React.ReactElement {
  const {
    containerComponent: Container = 'div',
    containerProps = {},
    className,
    toolbar,
    toolbarEnd,
    toolbarBelow,
    children,
    pagination,
    sideBar,
  } = props;

  const hasSideBar = sideBar != null;
  const sideBarPosition = sideBar?.position ?? 'right';
  const hasToolbar = toolbar != null || toolbarEnd != null;

  const rootStyle: React.CSSProperties = {
    display: 'flex',
    flexDirection: 'column',
    height: '100%',
  };

  return (
    <Container
      className={className}
      style={rootStyle}
      {...containerProps}
    >
      {/* === Bordered container === */}
      <div style={borderedContainerStyle}>
        {/* Toolbar strip */}
        {hasToolbar && (
          <div style={toolbarStripStyle}>
            <div style={toolbarSectionStyle}>{toolbar}</div>
            <div style={toolbarSectionStyle}>{toolbarEnd}</div>
          </div>
        )}

        {/* Secondary toolbar row (filter chips, etc.) */}
        {toolbarBelow && (
          <div style={toolbarBelowStyle}>{toolbarBelow}</div>
        )}

        {/* Grid area (with optional sidebar) */}
        {hasSideBar ? (
          <div style={gridAreaFlexStyle}>
            {sideBarPosition === 'left' && <SideBar {...sideBar} />}
            <div style={gridChildStyle}>{children}</div>
            {sideBarPosition !== 'left' && <SideBar {...sideBar} />}
          </div>
        ) : (
          <div style={gridAreaSoloStyle}>{children}</div>
        )}

        {/* Footer strip (pagination) */}
        {pagination && (
          <div style={footerStripStyle}>{pagination}</div>
        )}
      </div>
    </Container>
  );
}
